# scripts/generators/datascience_data.py
"""
90 Days of Course-Specific Placement Accelerator Content for Data Science (track: datascience)
Phases:
1. Days 1-15: Python for Data Science, NumPy, Pandas, Data Cleaning & Descriptive Stats
2. Days 16-30: Exploratory Data Analysis (EDA), Visualization, Probability Distributions & Hypothesis Testing
3. Days 31-45: Feature Engineering, Scikit-Learn, Regression, Classification & Evaluation Metrics
4. Days 46-60: Ensemble Methods (Random Forest, XGBoost), Cross-Validation, SMOTE & PCA
5. Days 61-75: Unsupervised Clustering, Time Series Forecasting, Model Interpretability (SHAP) & SQL Window Functions
6. Days 76-89: A/B Testing Experimentation, Model Drift, MLOps Pipelines & Business ROI Presentation
Day 90: Final Placement Challenge
"""

COMM_TYPES = [
    "interview-question", "technical-explanation", "client-conversation",
    "team-communication", "workplace-scenario", "problem-explanation",
    "project-explanation", "technical-presentation", "email-response",
    "manager-conversation", "hr-question", "conflict-resolution",
    "requirement-clarification", "technical-to-nontechnical",
]

APT_TOPICS = [
    "Percentages & Growth", "Ratios & Proportions", "Averages & Distributions",
    "Profit, Margin & ROI", "Time, Work & Capacity", "Speed, Latency & Distance",
    "Probability & Reliability", "Combinatorics & Permutations", "Number Systems & Units",
    "Data Interpretation & Metrics", "Statistics & Dispersion", "Financial & Business Math",
]

LOGIC_TYPES = [
    "Sequence Reasoning", "Workflow Ordering", "Deductive Analysis",
    "Constraint Solving", "Debugging Logic", "Process Flow",
    "Cause & Effect", "Decision Architecture",
]

def get_datascience_days():
    days = []

    # 15 Detailed Foundations Days
    foundations = [
        (1, "technical-to-nontechnical", "Explaining Missing Data Imputation to a Business Stakeholder",
         "A retail business manager notices that 15% of customer records have missing annual income values and asks why you didn't simply delete those customer profiles.",
         "Explain the risk of selection bias when dropping records, and describe why intelligent imputation preserves statistical representativeness.",
         ["Missing Completely at Random (MCAR)", "Imputation (Median vs MICE)", "Sample Selection Bias"],
         "The Business Integrity Principle (Preserving valuable transactional history while mitigating data gaps)",
         "If we drop rows with missing income, our dataset gets smaller. So we just fill them in with the average income so the code doesn't crash.",
         "Too simplistic and dismissive. Imputing the simple mean can distort variance, and failing to explain selection bias undermines executive trust.",
         "Deleting records with missing income would discard over 15,000 active customer transaction histories, introducing severe survivorship bias—for example, customers who omit income might systematically represent younger demographics. Instead, we use multivariate imputation by chained equations (MICE), estimating income from zip code, purchase frequency, and basket size. This preserves 100% of our transactional training signal without distorting underlying demographic variances.",
         "Exemplary executive explanation: connects missingness mechanisms to business revenue insights and defends methodological rigor.",
         "Frame data preprocessing not as a technical cleanup chore, but as an insurance policy against biased business decisions.",
         "Data Interpretation & Metrics", "Dataset Missing Value Volume Calculation",
         "An enterprise churn dataset contains 12,500 customer records. During data profiling, you discover that 12% of records have missing payment methods and an additional 4% have missing tenure values (non-overlapping). How many total records contain missing values in these two fields?",
         ["2,000 records", "1,800 records", "2,200 records", "1,500 records"], 0,
         "Calculation: Total percentage missing = 12% + 4% = 16%. Total missing records = 12,500 * 0.16 = 2,000 records.",
         "Missing Volume = Total Rows * Cumulative Missing Rate",
         "Workflow Ordering", "Data Science Preprocessing Sequence",
         "Which sequence accurately represents the fundamental data preparation pipeline before training a machine learning model?",
         ["Raw Data Ingestion -> Missing Value Handling -> Outlier Detection -> Feature Scaling -> Train/Test Split",
          "Raw Data Ingestion -> Feature Scaling -> Model Training -> Train/Test Split -> Missing Value Imputation",
          "Feature Scaling -> Outlier Removal -> Raw Data Ingestion -> Train/Test Split -> Hyperparameter Tuning",
          "Model Training -> Missing Value Imputation -> Train/Test Split -> Feature Scaling -> Evaluation"], 0,
         "Standard data science pipelines require ingesting raw data, resolving missing values and anomalous outliers, performing scaling, and splitting into train/test sets (or fitting scalers strictly on training splits to prevent data leakage)."),

        (2, "interview-question", "Defending Correlation vs Causation in an Executive Interview",
         "An interviewer asks: 'Your analysis shows that ice cream sales and sunscreen sales have a 0.89 correlation. How do you explain why increasing ice cream promotions won't boost sunscreen sales?'",
         "Articulate the concept of confounding variables, spurious correlation, and how causal inference or randomized experiments differ from observational correlation.",
         ["Confounding Variable", "Spurious Correlation", "Causal Inference / A/B Testing"],
         "The Causal Rigor Principle (Distinguish predictive association from mechanistic intervention)",
         "Correlation doesn't equal causation. Ice cream and sunscreen both happen in summer because it's hot, so buying one doesn't make someone buy the other.",
         "Informally correct but lacks professional statistical vocabulary, experimental design recommendations, and enterprise rigor.",
         "A high correlation coefficient of 0.89 merely indicates statistical co-movement in observational data, driven by temperature as a common confounding variable. Neither variable has a causal mechanism over the other. If leadership desires to drive sunscreen revenue, intervening on ice cream prices would waste capital. In enterprise analytics, before recommending budget allocation, we test hypotheses using randomized controlled trials (A/B testing) or causal diagramming (DAGs) to isolate true incremental treatment effects.",
         "Demonstrates statistical maturity, clearly illustrates confounders, and prescribes A/B testing as the proper decision-making standard.",
         "Whenever discussing correlation in interviews, immediately introduce confounding factors and recommend randomized experimentation.",
         "Percentages & Growth", "Predictive Model Precision Calculation",
         "An e-commerce fraud detection model flags 400 suspicious transactions. Upon human audit, 320 of those transactions were confirmed fraudulent, while 80 were false positives. What is the precision of this model?",
         ["80.0%", "75.0%", "85.0%", "82.5%"], 0,
         "Calculation: Precision = True Positives / (True Positives + False Positives) = 320 / (320 + 80) = 320 / 400 = 0.80 or 80.0%.",
         "Precision = TP / (TP + FP)",
         "Deductive Analysis", "Identifying Data Leakage in Preprocessing",
         "A data scientist computes the mean and standard deviation of the entire dataset and normalizes all numerical features BEFORE performing a 70/30 train/test split. What methodological error has occurred?",
         ["Data Leakage: Information from the test distribution contaminated the training distribution, leading to overly optimistic test performance.",
          "Overfitting: The model has too many parameters relative to the number of sample observations.",
          "Underfitting: The model lacks the capacity to capture non-linear relationships in the training set.",
          "Target Drift: The distribution of the target variable changed over time due to external market conditions."], 0,
         "Computing preprocessing statistics across the full dataset before splitting leaks test set characteristics into the training set, violating independence and leading to unrealistically optimistic validation metrics."),

        (3, "team-communication", "Coaching a Junior Analyst on Vectorized Pandas vs Iterative Loops",
         "A junior analyst wrote a `.iterrows()` for-loop over 800,000 rows to calculate tax amounts, taking 14 minutes to run.",
         "Constructively explain why looping in Python is slow compared to vectorized NumPy/Pandas operations, and guide them through a refactor.",
         ["Vectorization", "Cython/C Underpinnings", "Broadcast Operations"],
         "Performance Mentorship (Highlight hardware efficiency and demonstrate 100x speedup)",
         "Don't use iterrows in Pandas, it's really slow. Use a vectorized column multiplication instead.",
         "Too curt. Fails to explain the underlying GIL/C-array memory architecture that makes vectorization fast.",
         "Great effort getting the tax calculation logic working! The reason it takes 14 minutes is that `.iterrows()` creates a Python Series object on every row, triggering dynamic type checking in the Python virtual machine 800,000 times. Pandas columns are backed by contiguous C memory arrays in NumPy. By writing `df['tax'] = df['amount'] * 0.18`, Pandas executes the multiplication in optimized C code across the entire array at once. This reduces runtime from 14 minutes to under 50 milliseconds.",
         "Instructive, respectful, and provides architectural clarity on why C-backed array memory produces orders-of-magnitude acceleration.",
         "Always explain the 'why' behind performance tips: connecting high-level Python code to underlying C-contiguous memory structures builds true engineering intuition.",
         "Speed, Latency & Distance", "Data Pipeline Processing Throughput",
         "A data ingestion worker processes 15,000 JSON records in 2.5 minutes using single-threaded parsing. After migrating to vectorized chunking, the same batch finishes in 15 seconds. By what factor did throughput increase?",
         ["10x faster", "8x faster", "12x faster", "6x faster"], 0,
         "Calculation: Initial time = 2.5 mins = 150 seconds. New time = 15 seconds. Speedup factor = 150 / 15 = 10x faster.",
         "Speedup = Old Runtime / New Runtime",
         "Debugging Logic", "Resolving SettingWithCopyWarning in Pandas",
         "When executing `df_filtered['new_metric'] = df_filtered['raw_metric'] * 2`, Pandas raises `SettingWithCopyWarning`. What is the correct idiomatic fix?",
         ["Explicitly create a deep copy using `df_filtered = df[condition].copy()` before modifying columns.",
          "Suppress all Python warnings globally using `warnings.filterwarnings('ignore')`.",
          "Switch the column assignment to use a Python for loop over indices.",
          "Convert the DataFrame into a Python dictionary and back to a DataFrame."], 0,
         "The warning signals that `df_filtered` might be a view rather than an independent object. Using `.copy()` explicitly allocates separate memory, preventing unintended mutations to the source DataFrame."),

        (4, "client-conversation", "Explaining Model Accuracy vs Recall in Healthcare Analytics",
         "A hospital administrator questions why a 98% accurate cancer screening algorithm was rejected by your team in favor of an algorithm with 94% accuracy.",
         "Articulate class imbalance in healthcare diagnostics and why maximizing recall (sensitivity) prevents fatal false negatives.",
         ["Class Imbalance", "Sensitivity / Recall", "Cost of False Negatives vs False Positives"],
         "Stakeholder Alignment (Frame metrics around patient safety and business risk)",
         "98% accuracy is deceptive because most people don't have cancer, so guessing 'no cancer' gives high accuracy. We need recall instead.",
         "Accurate in premise but lacks empathy, professional framing, and executive reassurance regarding clinical outcomes.",
         "In a population where only 2% of patients have early-stage malignancy, a trivial algorithm that predicts 'healthy' for everyone achieves 98% accuracy—yet misses 100% of cancer cases. For our hospital, a false positive triggers an ultrasound confirmation, but a false negative sends an undiagnosed patient home with fatal consequences. Our 94% accuracy model achieves 99.2% recall, capturing virtually every positive case early when interventions are most effective.",
         "Brilliantly connects statistical mechanics to clinical stakes, transforming perceived performance loss into patient-safety leadership.",
         "In healthcare and fraud domains, always emphasize the asymmetric cost of errors: false negatives are often catastrophic.",
         "Percentages & Growth", "Class Imbalance Minority Representation",
         "A clinical dataset of 40,000 patient admission records contains 600 confirmed sepsis cases. What is the percentage prevalence of the positive sepsis class in this dataset?",
         ["1.5%", "2.0%", "1.2%", "2.5%"], 0,
         "Calculation: Prevalence = (600 / 40,000) * 100% = 0.015 * 100% = 1.5%.",
         "Prevalence (%) = (Target Cases / Total Population) * 100",
         "Decision Architecture", "Metric Selection for Severe Class Imbalance",
         "When evaluating a fraud prediction model on a dataset where fraud occurs in only 0.2% of transactions, which metric should serve as the primary optimization objective?",
         ["PR-AUC (Precision-Recall Area Under Curve)",
          "Standard Accuracy Score",
          "Mean Squared Error (MSE)",
          "Silhouette Coefficient"], 0,
         "Under extreme class imbalance, ROC-AUC and Accuracy can be deceptive due to massive true negative counts. PR-AUC focuses exclusively on the minority positive class, providing an honest measure of precision and recall trade-offs."),

        (5, "problem-explanation", "Explaining Multicollinearity to Risk Management",
         "A financial risk committee asks why two credit score variables with positive business effects ended up with negative regression coefficients in your scorecard model.",
         "Explain multicollinearity, variance inflation, and how correlated predictors destabilize regression coefficients.",
         ["Multicollinearity", "Variance Inflation Factor (VIF)", "Coefficient Instability"],
         "Statistical Integrity (De-mystify mathematical artifacts to preserve model credibility)",
         "The variables are correlated so the math got confused and flipped the sign. We just need to drop one.",
         "Unprofessional phrasing ('math got confused') that erodes confidence in the modeling process.",
         "When two predictor variables—such as FICO score and Vantage score—share a 0.94 correlation, they introduce high multicollinearity. Mathematically, the regression algorithm attempts to isolate the unique marginal contribution of each variable holding the other constant, which inflates the standard errors and can cause coefficients to flip sign erratically. We evaluated Variance Inflation Factors (VIF > 12) and eliminated the redundant score, which restored logical positive coefficients and stabilized our risk scorecard.",
         "Clear mathematical explanation with tangible remedial action (VIF inspection) that satisfies compliance and risk officers.",
         "When regression coefficients defy business intuition, immediately evaluate multicollinearity and present VIF diagnostic results.",
         "Averages & Distributions", "Standard Deviation and Outlier Z-Score Calculation",
         "A sample of 500 server response times has a mean of 120 ms and a standard deviation of 15 ms. An anomalous query records a latency of 165 ms. What is the Z-score of this query?",
         ["+3.0", "+2.5", "+3.5", "+2.0"], 0,
         "Calculation: Z = (X - Mean) / StdDev = (165 - 120) / 15 = 45 / 15 = +3.0.",
         "Z-score = (Value - Mean) / Standard Deviation",
         "Cause & Effect", "Impact of Outliers on Parametric Models",
         "A dataset contains extreme positive outliers in customer transaction amounts. If a data scientist fits an Ordinary Least Squares (OLS) linear regression model without transforming or capping the data, what will happen to the regression line?",
         ["The OLS line will be disproportionately pulled toward the extreme outliers because squared error penalties heavily penalize large deviations.",
          "The regression line will automatically ignore points beyond 2 standard deviations.",
          "The intercept will stay identical while the R-squared value drops to exactly 0.0.",
          "The regression coefficients will uniformly shrink toward zero due to L2 regularization."], 0,
         "OLS minimizes the sum of squared residuals, meaning a single outlier with a residual of 10 creates a penalty of 100, exerting high leverage and distorting the slope away from the general population pattern."),

        (6, "interview-question", "Explaining Central Limit Theorem in a Senior Data Science Interview",
         "The interviewer asks: 'Why can we use normal distribution assumptions in hypothesis testing even when our underlying transaction data is heavily skewed?'",
         "Explain the Central Limit Theorem (CLT) specifically differentiating the distribution of individual data points from the sampling distribution of the sample mean.",
         ["Sampling Distribution of the Mean", "Sample Size (n >= 30)", "Standard Error"],
         "Theoretical Precision (Differentiate population distribution from estimator distribution)",
         "Because of the Central Limit Theorem, if your sample is over 30, any data becomes a normal bell curve.",
         "Factually wrong: raw data does not magically become normal; only the distribution of sample averages approaches normality.",
         "The Central Limit Theorem does not claim that the raw population data transforms into a normal distribution. Rather, it proves that if we draw repeated random samples of size n (typically n >= 30) from any population with finite variance, the sampling distribution of the sample mean approaches a Gaussian normal distribution regardless of the underlying skewness. This mathematical property allows us to compute confidence intervals and conduct parametric hypothesis tests on population means with valid probabilistic guarantees.",
         "Crisp, statistically rigorous definition that avoids the classic candidate misconception regarding raw vs sampling distributions.",
         "Never say 'raw data becomes normal'. Always specify that the *sampling distribution of the mean* becomes normal.",
         "Probability & Reliability", "Normal Distribution Empirical Rule Probability",
         "Daily active user signups follow an approximately normal distribution with a mean of 5,000 users and a standard deviation of 400. Using the 68-95-99.7 empirical rule, what is the probability that tomorrow's signups will fall between 4,200 and 5,800?",
         ["95.0%", "68.0%", "99.7%", "90.0%"], 0,
         "Calculation: 4,200 is Mean - 2*StdDev (5,000 - 800) and 5,800 is Mean + 2*StdDev (5,000 + 800). Under the empirical rule, exactly ~95% of data falls within 2 standard deviations of the mean.",
         "P(Mean - 2*sigma <= X <= Mean + 2*sigma) ~= 95%",
         "Workflow Ordering", "Hypothesis Testing Workflow Sequence",
         "Arrange the steps of an A/B test hypothesis testing procedure in correct statistical order:",
         ["Formulate Null & Alternative Hypotheses -> Set Significance Level (alpha) -> Collect Sample Data -> Calculate Test Statistic & P-value -> Make Decision (Reject / Fail to Reject)",
          "Calculate P-value -> Collect Sample Data -> Formulate Null Hypothesis -> Set Significance Level -> Make Decision",
          "Collect Sample Data -> Make Decision -> Formulate Hypotheses -> Set alpha -> Calculate Test Statistic",
          "Set alpha -> Reject Null Hypothesis -> Collect Sample Data -> Calculate Test Statistic -> Formulate Hypotheses"], 0,
         "Statistical hypothesis testing strictly requires establishing the null/alternative hypotheses and significance threshold (alpha) before data collection to prevent p-hacking and biased decision thresholds."),

        (7, "workplace-scenario", "Managing Data Drift Discussion with Machine Learning Engineering",
         "A customer propensity model deployed 6 months ago has seen its F1-score drop from 0.84 to 0.61. The product team claims the model is 'broken'.",
         "Explain covariate shift and concept drift constructively, and propose a continuous monitoring and retraining cadence.",
         ["Covariate Shift", "Concept Drift", "Population Stability Index (PSI)"],
         "Collaborative Problem Solving (Shift blame from the algorithm to external environment changes)",
         "The model isn't broken, the market changed after our marketing campaign so you guys need to collect new data.",
         "Defensive and adversarial. Lacks concrete monitoring metrics and production observability strategies.",
         "The model architecture itself is functioning as designed, but its inference context has experienced data and concept drift. Following our recent product redesign, user browsing behaviors shifted (covariate shift), and the relationship between time-on-page and checkout probability altered (concept drift). By measuring our Population Stability Index (PSI > 0.25) across key input features, we can quantify exactly where user behavior diverged. I propose implementing automated monthly retraining triggers and drift alerting to maintain F1-scores above 0.80 consistently.",
         "Professional, diagnostic, and outlines concrete metric-driven monitoring (PSI) and retraining architecture.",
         "Treat model degradation as a natural consequence of dynamic markets, proposing automated drift metrics (PSI/KS tests) to resolve it.",
         "Ratios & Proportions", "Train / Validation / Test Split Sizing",
         "A customer analytics dataset contains 120,000 cleaned rows. The team mandates a 70% Train, 15% Validation, and 15% Test split. How many total samples are allocated strictly to the training partition?",
         ["84,000 samples", "80,000 samples", "90,000 samples", "75,000 samples"], 0,
         "Calculation: Training rows = 120,000 * 0.70 = 84,000 samples.",
         "Train Split = Total Size * Train Percentage",
         "Constraint Solving", "Detecting High Variance vs High Bias",
         "A decision tree model achieves 99.8% accuracy on the training set but drops to 64.2% accuracy on the unseen test set. What is the diagnosis and appropriate remediation?",
         ["High Variance (Overfitting): Prune the tree depth, increase min_samples_split, or switch to an ensemble like Random Forest.",
          "High Bias (Underfitting): Increase polynomial features and train on fewer observations.",
          "Target Leakage: The target variable was accidentally included in the input feature matrix.",
          "Covariate Shift: The test set features have a fundamentally different standard deviation than the training set."], 0,
         "A near-perfect training score coupled with poor generalization on the test set is the hallmark of high variance (overfitting), solved by regularization, pruning, and ensembling."),

        (8, "technical-presentation", "Presenting Feature Importance with SHAP to Non-Technical Leadership",
         "Presenting a customer churn model to the Chief Customer Officer who wants to know why specific high-value accounts were flagged for churn.",
         "Explain SHAP (Shapley Additive exPlanations) values in intuitive business terms, showing how features push a prediction up or down from the baseline.",
         ["SHAP Values", "Game Theory / Fair Attribution", "Directional Impact"],
         "Intuitive Visualization (Explain collaborative feature contributions with financial analogies)",
         "SHAP comes from cooperative game theory and uses Shapley values to calculate the marginal contribution of features.",
         "Technically accurate but mathematically dry; leaves the CCO unable to take operational customer retention actions.",
         "Think of our churn model like a team of detectives examining an account. The baseline average churn rate across the company is 15%. For this specific VIP client, their 40% drop in login frequency pushed their churn risk up by +25%, while their 3 unresolved support tickets added another +18%. Conversely, their long 4-year tenure pushed their risk down by -12%, resulting in a final 46% churn probability. SHAP gives us exact, transparent reasons for every single customer so your retention team knows exactly what problem to address.",
         "Vivid, actionable, and empowers the executive to deploy targeted operational interventions immediately.",
         "Use the 'tug-of-war' or 'detective' analogy for SHAP: baseline probability plus positive and negative feature pushes.",
         "Percentages & Growth", "A/B Test Relative Conversion Lift Calculation",
         "In an A/B test, Control Version A achieved a conversion rate of 4.0%, while Treatment Version B achieved a conversion rate of 5.2%. What is the relative percentage lift generated by Version B over Control A?",
         ["30.0% lift", "25.0% lift", "1.2% lift", "35.0% lift"], 0,
         "Calculation: Absolute lift = 5.2% - 4.0% = 1.2%. Relative lift = (5.2 - 4.0) / 4.0 = 1.2 / 4.0 = 0.30 or 30.0% relative lift.",
         "Relative Lift (%) = ((Treatment - Control) / Control) * 100",
         "Process Flow", "Tree-Based Feature Importance vs Permutation Importance",
         "A random forest model has a high-cardinality continuous ID-like feature that receives misleadingly high Gini feature importance. What is the recommended methodological fix?",
         ["Evaluate Permutation Feature Importance on an out-of-fold validation set.",
          "Drop all other features and retain only the high-cardinality variable.",
          "Re-train the model using unpruned single decision trees.",
          "Switch the loss function from cross-entropy to mean squared error."], 0,
         "Default Gini impurity-based feature importance is biased toward high-cardinality numerical variables. Permutation importance on validation sets measures true predictive degradation when feature values are shuffled."),

        (9, "manager-conversation", "Negotiating Project Scope and Deliverable Timelines with a VP",
         "A VP of Sales asks for an AI model that predicts quarterly enterprise deal closing with 100% precision within 2 weeks.",
         "Manage expectations constructively, articulate the reality of probabilistic modeling, and deliver an iterative milestone roadmap.",
         ["Probabilistic Modeling", "Iterative Milestones / MVP", "Uncertainty Quantification"],
         "Executive Expectation Management (Offer phased value rather than an outright rejection)",
         "100% precision is impossible in machine learning, and 2 weeks is way too short to build any decent model.",
         "Blunt and confrontational. Shuts down executive sponsorship without providing an actionable alternative.",
         "I share your goal of maximizing pipeline predictability for our sales executives! In data science, human purchasing decisions involve external factors that no model can predict with 100% certainty without severe overfitting. However, within two weeks, we can deliver an MVP rule-augmented lead scoring model that identifies the top 20% of high-intent deals with an estimated 80% precision. We can then iterate over the following month to incorporate CRM behavioral signals and refine deal closing probabilities with calibrated confidence intervals.",
         "Strategic and diplomatic: redirects an unrealistic request into a tangible 2-week MVP that builds organizational momentum.",
         "Never just say 'that is impossible'. Explain the probabilistic nature of data and propose a high-value MVP milestone.",
         "Profit, Margin & ROI", "ROI of Predictive Churn Prevention",
         "A telecommunications company has 50,000 subscribers generating $60/month each. A machine learning model identifies 800 high-risk churning customers. A retention campaign saves 25% of these flagged customers. What is the gross monthly revenue preserved by this model?",
         ["$12,000 / month", "$10,000 / month", "$15,000 / month", "$8,000 / month"], 0,
         "Calculation: Customers saved = 800 * 0.25 = 200 customers. Revenue preserved = 200 * $60 = $12,000 per month.",
         "Preserved Revenue = Flagged Customers * Retention Rate * Monthly ARPU",
         "Debugging Logic", "Diagnosing High Training Loss That Fails to Converge",
         "During gradient descent optimization for a logistic regression model, the cost function oscillates wildly and increases to infinity instead of decreasing. What is the root cause?",
         ["The learning rate (alpha) is set too high, causing gradient steps to overshoot the minimum and diverge.",
          "The number of training iterations is too large.",
          "The dataset has too many training observations.",
          "The target variable was encoded as 0 and 1."], 0,
         "An excessively high learning rate causes gradient descent to take oversized steps, overshooting the loss valley and diverging toward numerical overflow (NaN/infinity)."),

        (10, "email-response", "Writing a Production Incident Summary for Data Corruption in Training Sets",
         "A scheduled ETL pipeline accidentally duplicated 200,000 customer transaction rows in the analytics warehouse, causing tonight's automated demand forecasting model to generate inflated estimates.",
         "Draft a clear, professional incident notification to downstream business heads detailing the impact, containment, and resolution timeline.",
         ["Data Quality Alert", "Rollback / Mitigation", "Post-Mortem Root Cause Analysis"],
         "Crisis Communication (Transparent, structured, accountable, and proactive)",
         "Hey team, the ETL script duplicated some data so don't look at the demand forecasts today, we are trying to fix it.",
         "Informal, lacks clarity on business impact, and offers no timeline for reliable numbers.",
         "Subject: [DATA ALERT] Demand Forecasting Pipeline Delay & Remediation Timeline\n\nDear Commercial Planning Team,\n\nDuring our 03:00 UTC automated data quality validation, our observability framework detected an anomalous row count increase caused by duplicate transaction records in the staging warehouse. Out of an abundance of caution, we have paused the automated publication of today's demand forecasts to prevent skewed procurement orders.\n\nMitigation Steps Taken:\n1. Reverted downstream reporting tables to yesterday's validated snapshot.\n2. Purged staging duplicates and implemented deduplication constraints on transaction IDs.\n3. Model re-training is in progress with validated data; certified forecasts will be published by 11:30 UTC.\n\nA full Root Cause Analysis (RCA) and permanent pipeline assertion safeguard will be shared by end of day. Thank you for your patience.",
         "Executive-level incident transparency: identifies problem, outlines immediate mitigation, and sets clear delivery expectations.",
         "In incident communications, always state: what happened, what business decisions are affected, immediate mitigation, and ETA for resolution.",
         "Time, Work & Capacity", "Distributed Spark Cluster Execution Time",
         "A single-node Python script processes a 240 GB parquet dataset in 12 hours. The pipeline is migrated to an Apache Spark cluster with 8 identical worker nodes operating with 75% parallel scaling efficiency. What is the new estimated execution time?",
         ["2.0 hours", "1.5 hours", "2.5 hours", "3.0 hours"], 0,
         "Calculation: Ideal time with 8 nodes = 12 / 8 = 1.5 hours. At 75% scaling efficiency: Actual time = 1.5 / 0.75 = 2.0 hours.",
         "Parallel Time = (Single Node Time / Nodes) / Efficiency Factor",
         "Workflow Ordering", "Cross-Validation on Time-Series Data",
         "When evaluating a time-series forecasting model, why is standard K-Fold cross-validation invalid, and what is the proper validation scheme?",
         ["Standard K-Fold leaks future information into the past; TimeSeriesSplit (rolling forward-chaining window) must be used.",
          "Standard K-Fold creates folds that are too large for time-series data.",
          "Time-series data cannot be split into training and test sets under any circumstances.",
          "K-Fold only works when all target variables are binary."], 0,
         "Standard K-Fold randomly shuffles data, allowing future observations to train models predicting past dates (temporal leakage). Forward-chaining time-series splits preserve chronological order."),

        (11, "conflict-resolution", "Resolving Feature Selection Disagreements Between Analysts",
         "Two senior analysts argue over whether to include a customer credit score variable in an insurance pricing model: one argues for statistical predictive power, while the other cites regulatory compliance and disparate impact concerns.",
         "Mediate the disagreement with objective frameworks, balancing statistical lift against legal and ethical compliance constraints.",
         ["Regulatory Compliance / Fair Lending", "Disparate Impact Analysis", "Proxy Variables"],
         "Ethical & Legal Governance (Compliance and ethics always supersede marginal statistical lift)",
         "We should just use credit score because it increases R-squared by 3%, and we can let the legal team worry about regulations later.",
         "Dangerous and unacceptable engineering judgment. Violates regulatory compliance and exposes the enterprise to massive legal liability.",
         "I appreciate both perspectives: Analyst A is right that credit score adds 3% predictive lift, but Analyst B is correct that insurance pricing is governed by strict anti-discrimination statutes. If credit score acts as a proxy variable for protected demographic classes, using it exposes the firm to severe regulatory penalties and reputational damage. Let's run a Disparate Impact Ratio test. If the proxy bias exceeds regulatory thresholds, we will exclude it and explore non-protected behavioral features that capture risk without legal exposure.",
         "Diplomatic, authoritative, and correctly identifies that legal compliance and algorithmic fairness are non-negotiable boundaries.",
         "Always uphold algorithmic fairness: legal compliance and ethical constraints supersede marginal R-squared gains.",
         "Financial & Business Math", "Customer Lifetime Value (CLV) Calculation",
         "A subscription SaaS business has an average monthly revenue per user (ARPU) of $50, a gross profit margin of 80%, and a monthly customer churn rate of 2.5%. What is the predicted Customer Lifetime Value (CLV)?",
         ["$1,600", "$1,400", "$1,800", "$1,200"], 0,
         "Calculation: CLV = (ARPU * Gross Margin) / Churn Rate = ($50 * 0.80) / 0.025 = $40 / 0.025 = $1,600.",
         "CLV = (Monthly Revenue * Gross Margin %) / Churn Rate",
         "Deductive Analysis", "Identifying Simpson's Paradox in Aggregate Data",
         "In aggregate data, Drug A shows a higher recovery rate than Drug B. However, when stratified by disease severity (mild vs severe cases), Drug B shows a higher recovery rate in BOTH subgroups. What statistical phenomenon explains this?",
         ["Simpson's Paradox: An uneven distribution of a confounding variable (severity) reverses the aggregate association.",
          "The Gambler's Fallacy: Random variations in sample size created an artificial difference.",
          "Berkson's Bias: Selection bias caused by studying hospitalized patients.",
          "Hawthorne Effect: Subjects altered their behavior because they were aware of being observed."], 0,
         "Simpson's Paradox occurs when a trend appearing in different groups disappears or reverses when these groups are combined, caused by an unadjusted confounding variable."),

        (12, "hr-question", "Answering: 'Describe a Time Your Machine Learning Model Failed'",
         "An executive interviewer asks: 'Tell me about a time a data science model you built failed in production, and what you learned from it.'",
         "Utilize the STAR framework (Situation, Task, Action, Result) demonstrating humility, accountability, rapid remediation, and systemic guardrails.",
         ["STAR Method", "Post-Mortem & Safeguards", "Systemic Resilience"],
         "Accountable Leadership (Own the failure, detail the rapid fix, and highlight long-term architectural improvements)",
         "I built a recommendation model that recommended out-of-stock items, but it was the inventory team's fault for not updating their database in real time.",
         "Blames other teams, avoids personal accountability, and reveals a lack of end-to-end production ownership.",
         "In my previous role, I deployed a dynamic pricing model for seasonal travel packages. During our first flash sale, the model optimized for margin but failed to account for real-time hotel room availability limits, leading to 45 overbooked reservations. I took immediate ownership: we rolled back to static pricing within 20 minutes and personally assisted customer service in rebooking affected guests. To prevent recurrence, I integrated real-time inventory constraint checks directly into the model's loss penalty and instituted a mandatory shadow-mode deployment phase for all future pricing algorithms. That failure taught me that production ML is an end-to-end socio-technical system, not just an isolated optimization script.",
         "Authentic, demonstrates immense leadership under pressure, and proves the candidate creates systemic safeguards from mistakes.",
         "In behavioral failure questions: own the incident immediately, detail your rapid operational containment, and describe the permanent architectural guardrails added.",
         "Combinatorics & Permutations", "A/B/n Multivariate Testing Combinations",
         "A marketing optimization team tests 3 different headline variations, 4 distinct call-to-action buttons, and 2 background hero images simultaneously in a full factorial experiment. How many total unique page combinations are being evaluated?",
         ["24 variations", "18 variations", "32 variations", "12 variations"], 0,
         "Calculation: Total combinations = 3 headlines * 4 CTAs * 2 images = 24 unique page variations.",
         "Total Combinations = Product of factor levels (N1 * N2 * N3)",
         "Constraint Solving", "Sample Size Calculation Trade-offs in A/B Testing",
         "An analytics team wants to detect a smaller Minimum Detectable Effect (MDE) with higher statistical power (1 - beta = 0.90) in an upcoming conversion experiment. What is the necessary consequence for the experiment?",
         ["The required sample size and experiment duration must increase substantially.",
          "The required sample size will decrease because statistical power is higher.",
          "The experiment can terminate as soon as p < 0.05 on day 2.",
          "The team can safely ignore false positive alpha errors."], 0,
         "Detecting subtle treatment differences with high statistical power requires significantly larger sample sizes to overcome natural variance and avoid false negatives."),

        (13, "interview-question", "Explaining Regularization (L1 Lasso vs L2 Ridge) to an Interviewer",
         "The interviewer asks: 'How do L1 (Lasso) and L2 (Ridge) regularization differ mathematically, and when would you choose Lasso over Ridge?'",
         "Explain penalty terms, geometric constraint boundaries (diamond vs circle), and feature selection behavior.",
         ["L1 Penalty (|w|)", "L2 Penalty (w^2)", "Sparsity & Feature Selection"],
         "Mathematical Precision & Practical Utility (Connect geometric loss contours to real-world feature reduction)",
         "L1 is Lasso and gives you zeros. L2 is Ridge and makes weights small. Use Lasso when you want fewer features.",
         "Oversimplified and textbook-level; fails to explain the geometric reason why L1 forces coefficients to exact zero.",
         "Both methods combat overfitting by adding a penalty on weight magnitudes to the loss function. Ridge (L2) adds the sum of squared weights, which shrinks coefficients asymptotically toward zero but never sets them strictly to zero, making it ideal when you have many collinear features that all contribute signal. Lasso (L1) adds the sum of absolute weights. Geometrically, the L1 constraint boundary is a diamond with sharp corners on the coordinate axes. When the elliptical contours of the objective function intersect these sharp corners, weights are driven to exactly zero. Therefore, I choose Lasso when dealing with high-dimensional sparse datasets where automated feature selection is essential.",
         "Masterful technical explanation: incorporates geometric intuition, penalty formulas, and real-world domain application.",
         "Always mention the geometric constraint boundary: the diamond corners of L1 intersect axes at zero, creating true sparsity.",
         "Averages & Distributions", "Weighted Average Customer Score Calculation",
         "A customer satisfaction metric weights three survey categories: Product Quality (weight 0.50), Support Experience (weight 0.30), and Delivery Speed (weight 0.20). A client scores 80 on Quality, 90 on Support, and 70 on Delivery. What is the client's weighted satisfaction score?",
         ["81.0", "80.0", "83.0", "78.5"], 0,
         "Calculation: Weighted Average = (80 * 0.50) + (90 * 0.30) + (70 * 0.20) = 40 + 27 + 14 = 81.0.",
         "Weighted Mean = Sum(Value * Weight) / Sum(Weights)",
         "Debugging Logic", "Diagnosing Vanishing Gradients in Deep Neural Networks",
         "A deep feedforward network with 12 layers using Sigmoid activation functions fails to update its early layer weights during backpropagation. What is the root cause?",
         ["The derivative of the sigmoid function saturates at maximum 0.25; multiplying small decimals across 12 layers causes the gradient to vanish to near-zero.",
          "The learning rate is causing exploding weights in the final classification layer.",
          "The batch size is too large for the GPU memory buffer.",
          "The training data is improperly shuffled."], 0,
         "Sigmoid activations have derivatives bounded between 0 and 0.25. In deep networks, repeated chain-rule multiplications cause backpropagated gradients to shrink exponentially, stalling learning in early layers."),

        (14, "workplace-scenario", "Managing Data Governance and PII Sanitization for Analytics",
         "A business unit wants to load raw customer social security numbers and unhashed email addresses into a centralized data lake for ad-hoc modeling.",
         "Articulate data privacy regulations (GDPR, CCPA), explain pseudonymization/tokenization techniques, and enforce data governance protocols constructively.",
         ["PII (Personally Identifiable Information)", "Tokenization / Hashing (SHA-256)", "Role-Based Access Control (RBAC)"],
         "Governance Stewardship (Protect the enterprise from breach liability while enabling secure analytical workflows)",
         "No, you can't put SSNs in the data lake, it's against company policy and illegal under GDPR.",
         "Rigid, unhelpful roadblock that encourages shadow IT workarounds instead of secure compliance collaboration.",
         "Protecting customer privacy is an absolute corporate priority: storing raw SSNs and unmasked emails in an open analytical lake violates CCPA/GDPR statutes and exposes the firm to severe regulatory penalties. However, data science models rarely need raw SSNs—they only need unique customer identity linkages and demographic patterns. I propose routing this data through our automated tokenization gateway: we will salt and hash emails with SHA-256 and substitute SSNs with synthetic UUIDs before loading into the analytical lake. This gives your team full analytical power while guaranteeing zero PII exposure.",
         "Constructive, solutions-oriented security leadership: defends compliance while facilitating business analytics.",
         "Never just block a data request on compliance grounds. Offer secure tokenization or differential privacy alternatives that meet analytical needs.",
         "Percentages & Growth", "ROC Curve False Positive vs True Positive Trade-off",
         "A binary diagnostic test evaluated on 1,000 disease-free control subjects produces 40 false positive alerts. What is the False Positive Rate (FPR or 1 - Specificity) of this test?",
         ["4.0%", "5.0%", "3.5%", "6.0%"], 0,
         "Calculation: FPR = False Positives / Total Actual Negatives = 40 / 1,000 = 0.04 or 4.0%.",
         "FPR = FP / (FP + TN)",
         "Workflow Ordering", "K-Means Clustering Hyperparameter Selection",
         "What is the standard methodological workflow for selecting the optimal number of clusters (K) in K-Means clustering?",
         ["Calculate Within-Cluster Sum of Squares (WCSS) across candidate K values -> Plot the Elbow Curve -> Compute Silhouette Scores -> Select K at the point of diminishing returns",
          "Set K equal to the number of input features in the raw dataset automatically",
          "Run K-Means with K=100 and delete clusters that have fewer than 10 observations",
          "Compute Pearson correlation between all features and set K to the highest correlation coefficient"], 0,
         "The standard unsupervised workflow evaluates the WCSS elbow curve combined with silhouette coefficient analysis to identify the most natural cluster separation."),

        (15, "technical-explanation", "Explaining SQL Window Functions to a Junior Data Analyst",
         "A junior analyst needs to calculate running total sales and monthly ranking per region, but is struggling to write 5 nested subqueries in SQL.",
         "Explain the power of SQL Window Functions (`OVER (PARTITION BY ... ORDER BY ...)`), comparing them with standard `GROUP BY` aggregations.",
         ["Window Functions", "PARTITION BY vs GROUP BY", "Analytical Aggregation"],
         "Clarity Through Contrast (Show how window functions retain individual row identity while computing aggregate context)",
         "Just use an OVER clause with partition by region and order by sales. It's much simpler than subqueries.",
         "Tells them what to type without explaining the conceptual difference between row-collapsing and row-preserving operations.",
         "The reason nested subqueries feel frustrating is that standard `GROUP BY` collapses individual rows into a single summary row, wiping out the detail. A SQL Window Function gives you the best of both worlds: it computes aggregate statistics over a defined 'window' of records while keeping every single row intact. By writing `SUM(sales) OVER (PARTITION BY region ORDER BY order_date)`, the database calculates a cumulative running total for each region while allowing you to inspect every individual customer transaction side-by-side.",
         "Brilliant pedagogical clarity: highlights the fundamental row-retention distinction that unlocks window function mastery.",
         "When teaching SQL window functions, emphasize: GROUP BY collapses rows; Window Functions compute aggregates while preserving individual rows.",
         "Financial & Business Math", "SQL Query Memory and Scan Cost Estimation",
         "A cloud data warehouse charges $5.00 per Terabyte of data scanned. A data analyst executes an unpartitioned query that scans a 160 GB table 50 times a day during automated dashboard refreshes. What is the total monthly query scan cost (30 days)?",
         ["$1,200.00", "$960.00", "$1,440.00", "$800.00"], 0,
         "Calculation: Daily scan volume = 160 GB * 50 = 8,000 GB = 8 TB/day. Monthly volume = 8 TB * 30 = 240 TB/month. Total cost = 240 TB * $5.00/TB = $1,200.00.",
         "Monthly Cost = (Daily Scanned TB * Days in Month) * Rate per TB",
         "Debugging Logic", "Resolving SQL Cartesian Join Explosions",
         "A SQL analyst joins an Orders table with 10,000 rows to a Customers table with 5,000 rows, but the resulting query returns 50,000,000 rows and crashes the database memory. What happened?",
         ["A Cartesian Product (CROSS JOIN) occurred because the JOIN condition ON clause was missing or mismatched.",
          "The database ran out of disk space due to excessive index fragmentation.",
          "The query used an INNER JOIN instead of a LEFT OUTER JOIN.",
          "The table contained NULL values in the primary key column."], 0,
         "A missing or invalid JOIN condition pairs every row in Table 1 with every row in Table 2 (10,000 * 5,000 = 50,000,000 rows), triggering memory exhaustion via an unintentional Cartesian explosion."),
    ]

    for s in foundations:
        days.append({
            "day": s[0],
            "commType": s[1],
            "commTitle": s[2],
            "commScenario": s[3],
            "commPrompt": s[4],
            "commVocab": s[5],
            "commRule": s[6],
            "commWeakResponse": s[7],
            "commWeakCritique": s[8],
            "commStrongResponse": s[9],
            "commStrongCritique": s[10],
            "commCoachTip": s[11],
            "aptTopic": s[12],
            "aptTitle": s[13],
            "aptQuestion": s[14],
            "aptOptions": s[15],
            "aptAnswer": s[16],
            "aptExplanation": s[17],
            "aptFormula": s[18],
            "logicType": s[19],
            "logicTitle": s[20],
            "logicQuestion": s[21],
            "logicOptions": s[22],
            "logicAnswer": s[23],
            "logicExplanation": s[24],
        })

    # Systematic phase topics for Days 16 to 89
    phase_definitions = [
        # Phase 2: Days 16-30 (EDA, Visualization, Probability & Hypothesis Testing)
        (16, 30, "EDA & Statistics", [
            ("Quantile-Quantile (Q-Q) Plot Interpretation", "Normality Assessment", "Assessing if sample residuals adhere to a Gaussian normal distribution.", ["Q-Q Plot", "Theoretical Quantiles"]),
            ("Box Plot and Interquartile Range (IQR) Outlier Filtering", "Outlier Detection", "Calculating IQR = Q3 - Q1 and setting whiskers at 1.5 * IQR.", ["IQR", "Tukey Whiskers"]),
            ("Heatmaps and Pearson vs Spearman Rank Correlation", "Correlation Analysis", "Comparing linear Pearson with monotonic non-linear Spearman rank correlation.", ["Spearman Rank", "Monotonicity"]),
            ("Two-Sample Independent Student's t-Test", "Hypothesis Testing", "Testing difference in mean conversion between treatment and control groups.", ["t-Statistic", "Degrees of Freedom"]),
            ("Paired Samples t-Test for Before/After Studies", "Statistical Inferences", "Measuring within-subject treatment impact on identical cohort subjects.", ["Paired Differences", "Within-Subject Variance"]),
            ("One-Way ANOVA and Post-Hoc Tukey HSD Tests", "Multiple Group Testing", "Testing variance across three or more test groups while controlling FWER.", ["F-Ratio", "Tukey HSD"]),
            ("Chi-Square Test of Independence for Categorical Variables", "Categorical Analysis", "Testing contingency table independence between user device and churn status.", ["Chi-Square Statistic", "Expected Frequencies"]),
            ("Kernel Density Estimation (KDE) and Bimodal Distributions", "Distribution Modeling", "Identifying mixture populations and multi-modal customer distributions.", ["Bandwidth Parameter", "Multimodality"]),
            ("Logarithmic and Box-Cox Power Transformations", "Feature Engineering", "Stabilizing variance and reducing right-skewness in financial distributions.", ["Box-Cox Lambda", "Variance Stabilization"]),
            ("Type I vs Type II Errors and Statistical Power", "Experimental Rigor", "Balancing false positive alpha rates against false negative beta risks.", ["Alpha / False Positive", "Beta / Statistical Power"]),
            ("Bonferroni and Benjamini-Hochberg P-Value Corrections", "Multiple Testing Correction", "Preventing false discovery inflation across multi-variant A/B tests.", ["Family-Wise Error Rate", "False Discovery Rate"]),
            ("Non-Parametric Mann-Whitney U Test", "Distribution-Free Testing", "Comparing rank sums when data violates normality assumptions.", ["Rank-Sum Test", "Distribution-Free"]),
            ("Handling Zero-Inflated Continuous Distributions", "Advanced Modeling", "Using two-part hurdle models for datasets with excessive zero values.", ["Zero-Inflation", "Hurdle Model"]),
            ("Exploratory Spatial Data Analysis & Geohashing", "Geospatial Analytics", "Aggregating geospatial lat/long coordinates into Uber H3 or S2 hex bins.", ["H3 Hexagonal Grid", "Spatial Autocorrelation"]),
            ("Phase 2 Placement Milestone: Statistical Defense Review", "Interview Presentation", "Defending hypothesis testing and experimental design to senior data leaders.", ["Hypothesis Protocol", "Statistical Rigor"]),
        ]),

        # Phase 3: Days 31-45 (Feature Engineering, Scikit-Learn, Regression & Classification)
        (31, 45, "Feature Engineering & Core ML", [
            ("Target Encoding vs One-Hot Encoding for High Cardinality", "Categorical Encoding", "Preventing feature space explosion while managing target leakage risk.", ["Target Encoding", "Smoothing Weight"]),
            ("Ordinary Least Squares (OLS) Assumptions and Diagnostics", "Linear Regression", "Validating homoscedasticity, normality of residuals, and no multicollinearity.", ["Homoscedasticity", "Durbin-Watson Test"]),
            ("Polynomial Features and the Curse of Dimensionality", "Feature Space", "Balancing interaction terms against exponential dimensionality growth.", ["Polynomial Expansion", "Curse of Dimensionality"]),
            ("Logistic Regression Log-Odds and Sigmoid Transformation", "Classification", "Translating linear decision boundaries into probability estimates.", ["Logit / Log-Odds", "Sigmoid Function"]),
            ("Decision Tree Splitting Criteria: Gini vs Information Gain", "Tree Models", "Measuring node purity reduction using Shannon entropy and Gini index.", ["Gini Impurity", "Information Gain"]),
            ("ROC-AUC vs Precision-Recall Curves for Imbalanced Data", "Model Evaluation", "Selecting evaluation thresholds based on operational cost matrices.", ["ROC Curve", "PR-AUC Curve"]),
            ("F1-Score, Macro-Averaging vs Micro-Averaging", "Multi-Class Metrics", "Evaluating multi-class model performance across unequal category frequencies.", ["Macro F1", "Micro F1"]),
            ("Confusion Matrix Analysis: Cost-Sensitive Classification", "Business Decisioning", "Assigning financial loss weights to False Positives vs False Negatives.", ["Cost Matrix", "Expected Value Framework"]),
            ("Brier Score and Probability Calibration (Platt Scaling)", "Calibrated Probabilities", "Ensuring predicted probability scores reflect true empirical frequencies.", ["Platt Scaling", "Isotonic Regression"]),
            ("Scikit-Learn ColumnTransformer and Pipeline Architecture", "Production Pipelines", "Preventing data leakage by encapsulating scalers and encoders in pipelines.", ["ColumnTransformer", "Pipeline Object"]),
            ("Stratified K-Fold Cross-Validation for Classification", "Model Validation", "Preserving target class proportions across all validation partitions.", ["Stratified K-Fold", "Fold Independence"]),
            ("Recursive Feature Elimination (RFE) with Cross-Validation", "Feature Selection", "Pruning redundant features through backward model-in-the-loop elimination.", ["RFECV", "Feature Ranking"]),
            ("Ridge vs Lasso vs ElasticNet Regularization Tuning", "Regularization", "Balancing L1 feature sparsity with L2 grouped feature selection.", ["ElasticNet L1-Ratio", "Penalty Term"]),
            ("Support Vector Machines (SVM) and the Kernel Trick", "Non-Linear Separation", "Mapping non-separable input spaces into higher dimensions via RBF kernels.", ["RBF Kernel", "Margin Maximization"]),
            ("Phase 3 Placement Milestone: Scikit-Learn Model Defense", "Technical Interview", "Defending model selection, metric choice, and pipeline architecture in an interview.", ["Pipeline Integrity", "Metric Justification"]),
        ]),

        # Phase 4: Days 46-60 (Ensembles, XGBoost, SMOTE & Dimensionality Reduction)
        (46, 60, "Ensembles & Advanced ML", [
            ("Random Forest Bagging and Out-of-Bag (OOB) Score", "Ensemble Learning", "Reducing model variance through bootstrap aggregation and feature bagging.", ["Bootstrap Aggregation", "OOB Error Estimation"]),
            ("Gradient Boosting Machines (GBM): Residual Fitting", "Boosting Algorithms", "Sequentially minimizing pseudo-residuals using gradient descent in function space.", ["Residual Fitting", "Shrinkage Rate"]),
            ("XGBoost Architecture: Regularized Objective & Tree Pruning", "Extreme Gradient Boosting", "Understanding second-order Taylor approximations and sparsity-aware splitting.", ["Hessian Matrix", "Max Depth & Gamma"]),
            ("LightGBM: Leaf-Wise Growth and Histogram-Based Splitting", "High-Throughput ML", "Achieving high training speed via Gradient-Based One-Side Sampling (GOSS).", ["Leaf-Wise Growth", "GOSS Sampling"]),
            ("CatBoost: Ordered Boosting and Categorical Target Encoding", "Categorical Boosting", "Eliminating target leakage in categorical features via online learning.", ["Ordered Boosting", "Categorical Features"]),
            ("Handling Severe Imbalance: SMOTE and ADASYN Oversampling", "Imbalanced Learning", "Generating synthetic minority samples in feature space safely.", ["SMOTE", "Synthetic Interpolation"]),
            ("Class-Weight Cost Adjustment vs Synthetic Resampling", "Imbalanced Strategy", "Balancing algorithmic loss weighting against synthetic data artifacts.", ["class_weight='balanced'", "Loss Re-weighting"]),
            ("Principal Component Analysis (PCA): Eigenvectors & Variance", "Dimensionality Reduction", "Projecting features onto orthogonal axes that maximize explained variance.", ["Eigenvalues", "Explained Variance Ratio"]),
            ("t-SNE vs UMAP for High-Dimensional Visualization", "Non-Linear Projection", "Preserving global vs local data manifold topology in 2D projections.", ["UMAP Manifold", "Perplexity Parameter"]),
            ("Hyperparameter Tuning: Bayesian Optimization vs Random Search", "Model Tuning", "Using Gaussian Processes (Optuna / Hyperopt) to explore parameter spaces.", ["Bayesian Optimization", "Acquisition Function"]),
            ("Stacking and Blending Heterogeneous Model Predictions", "Meta-Learning", "Combining predictions from Ridge, Random Forest, and XGBoost via meta-models.", ["StackingClassifier", "Meta-Learner"]),
            ("Feature Interaction Detection with Friedman's H-Statistic", "Feature Discovery", "Identifying complex non-linear feature interactions in tree ensembles.", ["H-Statistic", "Two-Way Interactions"]),
            ("Model Compression: Pruning and Knowledge Distillation", "Model Efficiency", "Compressing heavy ensemble models into lightweight linear or neural students.", ["Knowledge Distillation", "Student-Teacher Model"]),
            ("Validating Model Stability Across Random Seeds", "Rigor & Reproducibility", "Measuring standard deviation of test scores across 10 random seeds.", ["Seed Variance", "Deterministic Training"]),
            ("Phase 4 Placement Milestone: Advanced Ensemble Defense", "Architecture Review", "Defending XGBoost hyperparameter tuning and oversampling decisions to senior engineers.", ["Tuning Strategy", "Ensemble Trade-offs"]),
        ]),

        # Phase 5: Days 61-75 (Unsupervised, Time Series, Interpretability & SQL)
        (61, 75, "Time Series & Interpretability", [
            ("K-Means++ Initialization and Inertia Convergence", "Clustering Algorithms", "Preventing poor local optima by spacing initial centroids probabilistically.", ["K-Means++", "Centroid Seeding"]),
            ("DBSCAN Density-Based Clustering and Outlier Flagging", "Density Clustering", "Discovering arbitrary cluster shapes without pre-specifying cluster count K.", ["Epsilon (eps)", "MinPts Parameter"]),
            ("Hierarchical Agglomerative Clustering & Dendrograms", "Hierarchical Methods", "Building bottom-up cluster hierarchies using Ward's minimum variance linkage.", ["Dendrogram", "Ward Linkage"]),
            ("Time Series Stationarity and Augmented Dickey-Fuller (ADF) Test", "Time Series Foundations", "Testing for unit roots and differencing non-stationary trends.", ["Stationarity", "ADF Test Statistic"]),
            ("Autocorrelation (ACF) and Partial Autocorrelation (PACF) Plots", "ARIMA Modeling", "Selecting AR(p) and MA(q) terms by inspecting lag correlation cutoffs.", ["ACF Cutoff", "PACF Partial Correlation"]),
            ("ARIMA and SARIMA Seasonal Modeling Framework", "Forecasting", "Configuring seasonal order (P, D, Q)[s] for retail sales forecasting.", ["SARIMA", "Seasonal Differencing"]),
            ("Facebook Prophet: Additive Seasonality and Holiday Effects", "Business Forecasting", "Handling non-linear trends with yearly, weekly, and daily seasonalities.", ["Prophet Additive Model", "Changepoint Prior Scale"]),
            ("Time Series Cross-Validation with Purged and Embargoed Folds", "Financial Time Series", "Preventing information leakage across temporal overlap in trading models.", ["Purged Cross-Validation", "Embargo Window"]),
            ("Model Explainability: Local vs Global SHAP Summary Plots", "XAI (Explainable AI)", "Visualizing feature importance rankings and directionality across entire datasets.", ["SHAP Beeswarm Plot", "Global Attribution"]),
            ("Partial Dependence Plots (PDP) and ICE Curves", "Model Inspection", "Visualizing marginal impact of a feature on model predictions across cohorts.", ["Partial Dependence", "Individual ICE Curves"]),
            ("SQL Window Functions: Cumulative Aggregations and Moving Averages", "Advanced SQL", "Calculating 7-day trailing moving averages using `ROWS BETWEEN 6 PRECEDING`.", ["Moving Average", "Window Frame Specification"]),
            ("SQL Common Table Expressions (CTEs) and Recursive Queries", "Analytical SQL", "Structuring complex multi-stage analytics pipelines cleanly with readable CTEs.", ["WITH Clause (CTE)", "Recursive Hierarchy"]),
            ("SQL Cohort Retention Matrix Construction", "Product Analytics", "Calculating MoM retention curves and cohort drop-off rates in SQL.", ["Cohort Analysis", "Retention Rate"]),
            ("Feature Store Architecture (Feast / Hopsworks)", "Data Infrastructure", "Bridging offline training datasets with online low-latency inference stores.", ["Feature Store", "Point-in-Time Correctness"]),
            ("Phase 5 Placement Milestone: Forecasting & Interpretability Review", "Executive Presentation", "Presenting time series forecast intervals and SHAP feature drivers to business executives.", ["Forecast Confidence", "SHAP Transparency"]),
        ]),

        # Phase 6: Days 76-89 (A/B Testing, MLOps, Business ROI & Strategy)
        (76, 89, "MLOps & Strategy", [
            ("A/B Testing: Sample Size Determination and Power Analysis", "Experimentation Design", "Calculating required sample size using baseline conversion and minimum detectable effect.", ["Power Calculation", "MDE (Minimum Detectable Effect)"]),
            ("Multi-Armed Bandits: Epsilon-Greedy vs Thompson Sampling", "Adaptive Experimentation", "Balancing exploration of new variants against exploitation of winning variants.", ["Thompson Sampling", "Regret Minimization"]),
            ("Addressing Novelty Effects and Primacy Effects in A/B Testing", "Experimentation Pitfalls", "Isolating short-term behavioral spikes caused by UI changes from true long-term lift.", ["Novelty Effect", "Long-Term Holdout"]),
            ("Model Serialization: ONNX vs Joblib vs MLflow Models", "Model Serving", "Exporting models to open format ONNX for cross-platform high-throughput inference.", ["ONNX Runtime", "Serialization"]),
            ("Real-Time REST Model Serving with FastAPI and Docker", "MLOps Engineering", "Containerizing Scikit-Learn pipelines behind asynchronous high-speed REST endpoints.", ["FastAPI Uvicorn", "Docker Containerization"]),
            ("Model Monitoring: Data Drift vs Concept Drift Alerting", "Production Observability", "Configuring Kolmogorov-Smirnov (K-S) and Population Stability Index (PSI) alerts.", ["KS Test", "PSI Alert Threshold"]),
            ("Automated Retraining Triggers and CI/CD for Machine Learning", "Continuous ML", "Orchestrating scheduled retraining pipelines on Apache Airflow or Kubeflow.", ["Airflow DAG", "Retraining Trigger"]),
            ("Data Quality Testing with Great Expectations", "Data Engineering Quality", "Validating table schemas, null percentage thresholds, and range expectations automatically.", ["Great Expectations", "Expectation Suite"]),
            ("Customer Churn Uplift Modeling (Causal ML)", "Causal Analytics", "Targeting 'persuadable' customers while ignoring 'sure things' and 'lost causes'.", ["Uplift Modeling", "Treatment Effect Heterogeneity"]),
            ("Attribution Modeling: First-Touch, Last-Touch, and Markov Chains", "Marketing Analytics", "Calculating multi-channel conversion attribution using transition probability matrices.", ["Markov Chain Attribution", "Shapley Attribution"]),
            ("Translating Model Metrics into Executive Business ROI", "Executive Communication", "Translating 2% AUC lift into $1.8M in annualized inventory holding cost reductions.", ["Financial Impact Model", "ROI Translation"]),
            ("Data Storytelling: Structuring Executive Pitch Decks", "Data Presentation", "Delivering the 'Situation, Complication, Resolution' storytelling framework.", ["SCR Framework", "Data Storytelling"]),
            ("Data Governance, Lineage, and GDPR Right-to-be-Forgotten", "Compliance Architecture", "Architecting data pipelines to purge individual customer records across all models.", ["Data Lineage", "Right to Erasure"]),
            ("Technical Interview Defense: System Design for Machine Learning", "Placement Preparation", "Designing an enterprise recommender system handling 50 million active users.", ["System Design", "Candidate Generation & Ranking"]),
        ]),
    ]

    for p_start, p_end, p_phase, p_topics in phase_definitions:
        for idx, t in enumerate(p_topics):
            d_num = p_start + idx
            t_title, t_cat, t_desc, t_vocab = t
            rate_base = 2500 + (d_num * 120)
            delta_pct = 15 + (d_num % 25)
            result_val = int(rate_base * (1 + delta_pct / 100))

            days.append({
                "day": d_num,
                "commType": COMM_TYPES[d_num % len(COMM_TYPES)],
                "commTitle": t_title,
                "commScenario": f"During a production review for {t_title}, stakeholders request clarification on {t_desc}.",
                "commPrompt": f"Explain the critical data science principles and business trade-offs of {t_title} with clarity.",
                "commVocab": [t_vocab[0], t_vocab[1]],
                "commRule": "Executive Data Articulation & Statistical Precision",
                "commWeakResponse": f"We just applied {t_title} using default settings in Python without checking the underlying distribution.",
                "commWeakCritique": "Vague, passive, and demonstrates a lack of statistical rigor and business awareness.",
                "commStrongResponse": f"In our data science architecture, {t_title} is implemented using {t_vocab[0]} and {t_vocab[1]} to guarantee statistical validity, eliminate data leakage, and deliver measurable business value.",
                "commStrongCritique": "Structured, authoritative, and connects mathematical rigor directly to reliable business outcomes.",
                "commCoachTip": f"Anchor your explanation in operational reliability: explain how {t_vocab[0]} protects downstream model decisions.",
                "aptTopic": APT_TOPICS[d_num % len(APT_TOPICS)],
                "aptTitle": f"{t_title} Analytical Math",
                "aptQuestion": f"A data science pipeline processes {rate_base:,} analytical records per second. After optimizing {t_title}, throughput increases by {delta_pct}%. What is the new processing volume per second?",
                "aptOptions": [f"{result_val:,} records/sec", f"{result_val - 85:,} records/sec", f"{result_val + 120:,} records/sec", f"{result_val - 140:,} records/sec"],
                "aptAnswer": 0,
                "aptExplanation": f"Calculation: Increase = {rate_base} * {delta_pct/100:.2f} = {result_val - rate_base}. New volume = {rate_base} + {result_val - rate_base} = {result_val:,} records/sec.",
                "aptFormula": "New Volume = Base * (1 + Growth Rate)",
                "logicType": LOGIC_TYPES[d_num % len(LOGIC_TYPES)],
                "logicTitle": f"{t_title} Methodological Logic",
                "logicQuestion": f"When configuring {t_title}, which statistical or operational constraint must be enforced to prevent invalid results?",
                "logicOptions": [
                    f"Ensure {t_vocab[0]} is verified and applied before dependent downstream transformations occur.",
                    f"Bypass {t_vocab[1]} completely to minimize computation time regardless of variance inflation.",
                    "Normalize all data across train and test sets simultaneously before splitting.",
                    "Ignore class imbalance and evaluate exclusively with raw accuracy."
                ],
                "logicAnswer": 0,
                "logicExplanation": f"Correct! In {t_title}, ensuring that {t_vocab[0]} is properly verified guarantees unbiased estimators and prevents methodological errors like data leakage.",
            })

    # Day 90: Final Placement Challenge
    days.append({
        "day": 90,
        "commType": "interview-question",
        "commTitle": "FINAL PLACEMENT CHALLENGE: Executive Enterprise Data Science Defense",
        "commScenario": "You are presenting before the Chief Data Officer and the Executive Analytics Committee for a Principal Data Scientist position.",
        "commPrompt": "Deliver an end-to-end architecture defense of an enterprise customer intelligence platform that ingests 50 million daily events, trains automated multi-target churn and LTV models with SHAP interpretability, and executes continuous A/B experimentation with automated drift remediation.",
        "commVocab": ["Enterprise Analytics Platform", "Causal Inference", "Real-Time Feature Store"],
        "commRule": "Executive Boardroom Gravitas & Strategic Data Leadership",
        "commWeakResponse": "We use Pandas and Scikit-Learn to build models, track them with MLflow, and deploy them on AWS so marketing can see who is going to churn.",
        "commWeakCritique": "Lacks distributed scaling mechanics, real-time feature consistency, regulatory governance, and executive financial impact.",
        "commStrongResponse": "Our enterprise customer intelligence architecture bridges real-time stream processing with rigorous statistical governance. Ingestion handles 50 million events daily via Apache Kafka, hydrating a dual-layer Feast feature store that guarantees point-in-time correctness for offline model training while serving sub-10ms features for online inference. We deploy ensemble gradient boosted trees and uplift models via Triton Inference Server, enforcing automated drift monitoring with Kolmogorov-Smirnov thresholds and SHAP value explainability for regulatory transparency. Coupled with multi-armed bandit experimentation, this system delivers an annualized $4.2M retention lift with complete data lineage compliance.",
        "commStrongCritique": "A masterpiece of enterprise data science leadership: seamlessly integrates streaming data, statistical rigor, explainability, and quantifiable financial ROI.",
        "commCoachTip": "In the final placement challenge, synthesize data engineering, statistical modeling, operational MLOps, and P&L impact into a unified executive vision.",
        "aptTopic": "Data Interpretation & Metrics",
        "aptTitle": "Final Assessment: Enterprise Churn Retention Financial Valuation",
        "aptQuestion": "An enterprise subscription platform has 200,000 customers with an average annual contract value of $1,200 each. The annual churn rate is 10%. A data science retention system identifies at-risk accounts with 80% precision and saves 30% of flagged accounts. What is the net annual revenue saved by this system?",
        "aptOptions": ["$5,760,000 / year", "$4,800,000 / year", "$6,400,000 / year", "$5,200,000 / year"],
        "aptAnswer": 0,
        "aptExplanation": "Calculation: Total churners per year = 200,000 * 0.10 = 20,000 customers. Accounts flagged and confirmed at risk = 20,000 * 0.80 = 16,000 customers. Saved accounts = 16,000 * 0.30 = 4,800 customers. Net annual revenue preserved = 4,800 * $1,200 = $5,760,000 per year.",
        "aptFormula": "Preserved Revenue = Churners * Precision * Save Rate * Contract Value",
        "logicType": "Decision Architecture",
        "logicTitle": "Final Assessment: End-to-End Algorithmic System Logic",
        "logicQuestion": "In an automated production loan approval system, an external audit reveals that an ensemble model is rejecting credit applications from a protected demographic group at an unconstitutionally disparate rate, even though demographic features were excluded from training. According to algorithmic fairness and causal inference, what is the mandatory immediate action?",
        "logicOptions": [
            "Halt automated adverse actions immediately, conduct proxy variable analysis to identify and eliminate correlated proxy features (e.g., zip codes), and apply adversarial debiasing or equalized odds constraints before re-deploying.",
            "Continue automated scoring because demographic features were omitted, proving mathematical neutrality.",
            "Lower the credit approval score threshold across all applicants uniformly to increase overall volume.",
            "Delete the audit report and retrain the model with 50 additional unverified internet features."
        ],
        "logicAnswer": 0,
        "logicExplanation": "Correct! Omitting explicit demographic labels does not prevent discrimination if proxy variables encode disparate impact. Algorithmic governance demands halting automated adverse decisions, detecting proxy features, and enforcing calibrated fairness constraints.",
    })

    return days

print("datascience_data module ready.")
