# scripts/generators/marketing_data.py
"""
90 Days of Course-Specific Placement Accelerator Content for Digital Marketing (track: marketing)
Phases:
1. Days 1-15: Digital Marketing Foundations, Personas, Customer Journey, Content Strategy & Social Media
2. Days 16-30: SEO Mastery: Keyword Research, On-Page Optimization, Technical SEO & Backlinks
3. Days 31-45: SEM & Google Ads: Search Campaigns, Quality Score, Bidding Strategies & PMax
4. Days 46-60: Paid Social Media: Meta Ads, TikTok Ads, Pixel/CAPI, Custom Audiences & Retargeting
5. Days 61-75: Analytics & Growth: GA4, Event Tracking, Funnel Optimization, Email Lifecycle & CRM
6. Days 76-89: Performance Strategy: Multi-Touch Attribution, ROAS Scaling, Budget Allocation & Client Defense
Day 90: Final Placement Challenge
"""

COMM_TYPES = [
    "interview-question", "technical-explanation", "client-conversation",
    "team-communication", "workplace-scenario", "problem-explanation",
    "project-explanation", "technical-presentation", "email-response",
    "manager-conversation", "hr-question", "conflict-resolution",
    "requirement-clarification", "technical-to-nontechnical",
]

APT_TOPICS = [
    "Percentages & Growth", "Ratios & Proportions", "Averages & Distributions",
    "Profit, Margin & ROI", "Time, Work & Capacity", "Speed, Latency & Distance",
    "Probability & Reliability", "Combinatorics & Permutations", "Number Systems & Units",
    "Data Interpretation & Metrics", "Statistics & Dispersion", "Financial & Business Math",
]

LOGIC_TYPES = [
    "Sequence Reasoning", "Workflow Ordering", "Deductive Analysis",
    "Constraint Solving", "Debugging Logic", "Process Flow",
    "Cause & Effect", "Decision Architecture",
]

def get_marketing_days():
    days = []

    # 15 Detailed Foundations Days
    foundations = [
        (1, "technical-to-nontechnical", "Explaining CTR vs Conversion Rate to a Small Business Client",
         "A local retail client is excited because their Google ad has a high 8% Click-Through Rate (CTR), but is confused why their actual e-commerce sales have not increased.",
         "Explain the distinct functions of top-of-funnel ad engagement (CTR) versus on-page user conversion rate (CVR) and identify landing page friction.",
         ["Click-Through Rate (CTR)", "Conversion Rate (CVR)", "Landing Page Friction"],
         "The Funnel Decoupling Principle (Separate traffic acquisition efficiency from on-site conversion capability)",
         "CTR just means people clicked the ad. If they don't buy, your website is probably bad or your prices are too high.",
         "Too blunt and accusatory. Fails to educate the client on the conversion funnel or offer constructive testing recommendations.",
         "Think of your digital marketing like a physical storefront on a busy shopping street: Click-Through Rate (CTR) measures how enticing our window display is—it gets shoppers through the front door. An 8% CTR proves our ad creative and targeting are performing exceptionally well. However, Conversion Rate (CVR) measures what happens once they walk inside: is the product easy to find, is checkout seamless, and is shipping transparent? A high CTR paired with flat sales signals that shoppers love the promise of the ad, but encounter friction on the landing page. Let's optimize the product page load speed and streamline the mobile checkout to convert that great traffic into revenue.",
         "Vivid storefront analogy: praises the ad performance while clearly illuminating the post-click on-site experience without blaming the client.",
         "Always separate traffic acquisition (CTR) from on-page conversion (CVR) using the storefront display analogy.",
         "Percentages & Growth", "Click-Through Rate (CTR) Calculation",
         "A Google Search campaign for an enterprise software product registers 25,000 ad impressions and generates 1,250 clicks. What is the Click-Through Rate (CTR) of this campaign?",
         ["5.0%", "4.5%", "6.0%", "5.5%"], 0,
         "Calculation: CTR = (Clicks / Impressions) * 100% = (1,250 / 25,000) * 100% = 0.05 * 100% = 5.0%.",
         "CTR (%) = (Total Clicks / Total Impressions) * 100",
         "Workflow Ordering", "Digital Marketing Full-Funnel Customer Journey Sequence",
         "Which sequence accurately maps the classic marketing funnel stages from initial customer discovery to long-term advocacy?",
         ["Awareness (Top of Funnel) -> Consideration / Interest (Middle of Funnel) -> Decision / Purchase (Bottom of Funnel) -> Retention -> Advocacy / Referral",
          "Purchase -> Awareness -> Retention -> Consideration -> Advocacy",
          "Consideration -> Retention -> Awareness -> Purchase -> Advocacy",
          "Advocacy -> Purchase -> Awareness -> Consideration -> Retention"], 0,
         "The standard customer lifecycle begins with top-of-funnel brand awareness, progresses through middle-of-funnel consideration, bottom-of-funnel conversion/purchase, and culminates in post-purchase retention and customer advocacy."),

        (2, "interview-question", "Defending ROAS vs CAC in a Performance Marketing Interview",
         "The interviewer asks: 'A paid media campaign achieves a 400% Return on Ad Spend (ROAS). Does that guarantee the company is profitable? How does Customer Acquisition Cost (CAC) factor in?'",
         "Explain the limitation of top-line ROAS (gross revenue over spend) versus true unit economics (Cost of Goods Sold, operating overhead, Customer Acquisition Cost, and Customer Lifetime Value).",
         ["Return on Ad Spend (ROAS)", "Customer Acquisition Cost (CAC)", "Unit Economics / Contribution Margin"],
         "Financial Rigor (Connect marketing vanity metrics to bottom-line net contribution margin)",
         "Yes, 400% ROAS means you make 4 dollars for every 1 dollar spent, so you are definitely very profitable.",
         "Superficial and financially naive. Ignores product COGS, shipping, payment processing fees, and operating expenses.",
         "A 400% ROAS (a 4:1 revenue-to-spend ratio) sounds impressive, but it does not guarantee net profitability. ROAS only measures gross top-line revenue against ad spend. If our product gross margin is only 20%, a 4:1 ROAS yields $80 in gross margin on $400 in sales, which fails to even cover the $100 spent on advertising. As performance marketers, we must calculate the Break-even ROAS based on gross margin: Break-even ROAS = 1 / Gross Margin %. Furthermore, evaluating Customer Acquisition Cost (CAC) against Customer Lifetime Value (LTV)—targeting an LTV:CAC ratio of at least 3:1—ensures we are building sustainable enterprise equity rather than burning cash on unprofitable first-order transactions.",
         "Deep financial sophistication: demonstrates exact break-even math and anchors marketing performance in corporate P&L sustainability.",
         "Always calculate Break-even ROAS: 1 / Gross Margin %. Never declare profitability based on top-line ROAS alone.",
         "Financial & Business Math", "Cost Per Click (CPC) and Daily Budget Spend",
         "A paid search campaign operates with a daily budget of $450.00. The average Cost Per Click (CPC) across all target keyword auctions is $1.80. Assuming the full daily budget is efficiently exhausted, how many clicks does the campaign acquire per day?",
         ["250 clicks", "225 clicks", "275 clicks", "300 clicks"], 0,
         "Calculation: Clicks = Daily Budget / Average CPC = $450.00 / $1.80 = 250 clicks per day.",
         "Clicks = Total Spend / Average Cost Per Click",
         "Deductive Analysis", "Diagnosing Ad Fatigue in Paid Social Campaigns",
         "A Meta video ad campaign that ran successfully for 4 weeks experiences a sudden 45% increase in Cost Per Acquisition (CPA) while ad Frequency rises from 1.3 to 4.8. What marketing phenomenon has occurred?",
         ["Ad Fatigue: The target audience has seen the same creative repeatedly, leading to banner blindness, lower CTR, and higher auction bidding penalties.",
          "Platform Bug: Meta Ads Manager experienced a global server crash.",
          "Targeting Expansion: The ad reached millions of brand-new uninterested users.",
          "Search Intent Shift: Google organic rankings cannibalized the Facebook ads."], 0,
         "When ad frequency rises significantly (> 3.5-4.0) alongside declining CTR and surging CPA, the audience is saturated with the same creative (Ad Fatigue), requiring creative refresh and audience expansion."),

        (3, "team-communication", "Coaching a Junior Media Buyer on Meta CAPI vs Browser Pixel",
         "A junior media buyer asks why the team is spending developer resources setting up Meta Conversions API (CAPI) when they already have the Meta browser pixel snippet installed.",
         "Explain the impact of Apple iOS 14.5 ATT (App Tracking Transparency), browser cookie restrictions, ad-blockers, and why server-to-server CAPI restores event data accuracy.",
         ["Meta Conversions API (CAPI)", "Server-Side Tracking", "iOS 14+ Signal Loss / Cookie Depreciation"],
         "Technical Architecture Mentorship (Highlight signal resilience and algorithmic optimization)",
         "We need CAPI because Facebook's pixel doesn't work well anymore after the iPhone updates.",
         "Too vague. Fails to explain the difference between client-side browser cookies and server-to-server event dispatch.",
         "Great question! The standard Meta pixel operates client-side in the user's web browser, which means it is vulnerable to ad-blockers, Safari ITP cookie expirations, and Apple's iOS tracking restrictions, which cause between 20% to 35% of conversion events to be dropped. Conversions API (CAPI) creates a direct server-to-server connection: when an order occurs, our web server sends the purchase event directly to Meta's server, bypassing browser blocking completely. By running CAPI alongside the browser pixel with deduplication, we achieve near 100% event match quality, giving Meta's ad algorithm the accurate data it needs to lower our Cost Per Purchase.",
         "Brilliant technical explanation: contrasts client-side vulnerability with server-side resilience and links data fidelity to algorithm bidding efficiency.",
         "Explain CAPI as an insurance policy against cookie depreciation: server-to-server signals guarantee high Event Match Quality (EMQ).",
         "Percentages & Growth", "Return on Ad Spend (ROAS) Calculation",
         "An e-commerce brand spends $6,000 on a Google Performance Max campaign over a weekend sale. The campaign directly tracks and attributes $27,000 in gross e-commerce purchase revenue. What is the campaign's ROAS percentage?",
         ["450%", "400%", "500%", "350%"], 0,
         "Calculation: ROAS = (Gross Revenue / Ad Spend) * 100% = ($27,000 / $6,000) * 100% = 4.5 * 100% = 450%.",
         "ROAS (%) = (Attributed Revenue / Total Ad Spend) * 100",
         "Debugging Logic", "Resolving High Bounce Rate on Paid Landing Pages",
         "A Google Ads campaign with high commercial intent keywords records an 82% bounce rate on mobile devices, compared to 34% on desktop. What is the most probable root cause?",
         ["Poor mobile page load speed (> 4 seconds) or an unoptimized, non-responsive mobile layout.",
          "The Google Ads bidding algorithm is favoring desktop users.",
          "The keyword match type should be changed from Exact Match to Broad Match.",
          "The brand's logo is too small on mobile screens."], 0,
         "A massive disparity between mobile and desktop bounce rates on identical intent traffic almost invariably points to mobile performance bottlenecks: slow mobile load latency, heavy uncompressed images, or clumsy mobile UX."),

        (4, "client-conversation", "Addressing an SEO Client Panicked by a Google Core Algorithm Update",
         "A client emails in a panic after reading an industry blog about a new Google Core Update, worried their website traffic will be wiped out overnight.",
         "De-escalate the panic professionally, outline search engine volatility cycles, and present a structured 14-day post-update auditing protocol.",
         ["Google Core Algorithm Update", "Search Volatility & Fluctuation", "E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness)"],
         "Calm Advisory Leadership (Instill confidence through methodical diagnostic observation rather than knee-jerk changes)",
         "Don't worry about blogs, Google changes things every day. We will see what happens next month.",
         "Dismissive and passive. Leaves the client feeling ignored and uncertain about their digital investment.",
         "I completely understand your concern—announcements of Google Core Updates can certainly sound alarming. Core updates typically roll out over a 14-day period, during which search engine rankings experience temporary volatility as Google re-indexes web pages globally. Making hasty changes during the rollout can do more harm than good. Our strategy has always adhered to Google's fundamental E-E-A-T guidelines: publishing original, authoritative content with clean technical architecture. We have our monitoring tools tracking your top commercial keywords daily. Once the rollout stabilizes in 10 days, we will deliver a comprehensive performance impact audit and strategic adjustments.",
         "Reassuring, authoritative, cites Google's official E-E-A-T framework, and outlines a measured 14-day observation and audit plan.",
         "During search algorithm updates: counsel patience during the 14-day rollout and anchor long-term SEO in E-E-A-T fundamentals.",
         "Data Interpretation & Metrics", "Cost Per Acquisition (CPA) Metric",
         "A B2B SaaS startup spends $14,000 on LinkedIn Lead Generation ads in a month. The campaign generates 350 qualified enterprise demo requests. What is the Cost Per Acquisition (CPA) for a qualified demo?",
         ["$40.00", "$35.00", "$45.00", "$50.00"], 0,
         "Calculation: CPA = Total Ad Spend / Total Acquired Conversions = $14,000 / 350 = $40.00 per demo request.",
         "CPA = Total Spend / Total Conversions",
         "Cause & Effect", "Impact of Canonical Tags on Duplicate Content",
         "An e-commerce site generates separate URLs for product color variations (`/shoes?color=red`, `/shoes?color=blue`) containing identical descriptions. If no rel=canonical tags are specified, what search engine penalty occurs?",
         ["Keyword Cannibalization & Dilution: Search engines split ranking authority across multiple URLs, causing overall search rankings for the product to drop.",
          "The website domain will be permanently de-indexed from Google within 24 hours.",
          "The website server will experience a Denial of Service attack from Googlebot.",
          "Google will automatically convert all query strings into subdomains."], 0,
         "Without rel=canonical tags, search crawlers treat identical parameterized URLs as duplicate content, diluting link equity and splitting ranking signals among duplicate pages."),

        (5, "problem-explanation", "Explaining Google Ads Quality Score Components to a Stakeholder",
         "A marketing director wants to know why their competitor is paying less per click while appearing higher on the Google Search results page.",
         "Explain Google Ads Ad Rank formula (Ad Rank = Max CPC * Quality Score) and break down the three core components of Quality Score.",
         ["Quality Score (1-10)", "Expected CTR", "Ad Relevance & Landing Page Experience"],
         "Auction Economics (Demonstrate how quality beats pure budget in search auction dynamics)",
         "Google prefers competitors because their budget is higher or they have been advertising longer than us.",
         "Factually incorrect. Fails to understand Google's Ad Rank auction mechanics and discourages optimization.",
         "In Google Search auctions, the highest bidder does not automatically win top placement. Google uses an 'Ad Rank' formula: Ad Rank = Maximum CPC Bid * Quality Score. Quality Score is rated from 1 to 10 based on three components: Expected Click-Through Rate, Ad Copy Relevance to the keyword, and Landing Page Experience (speed, mobile responsiveness, and content match). A competitor with a Quality Score of 9 can bid $2.00 and achieve an Ad Rank of 18, beating an advertiser bidding $3.00 with a Quality Score of 5 (Ad Rank 15). By improving our ad copy relevance and landing page speed, we can rank higher while lowering our Cost Per Click.",
         "Brilliant demonstration of auction theory: proves mathematical efficiency and provides a clear roadmap to lower advertising costs.",
         "Remember the golden rule of Google Ads: Ad Rank = Bid * Quality Score. Higher quality lowers required CPC.",
         "Percentages & Growth", "Landing Page Conversion Rate Improvement Lift",
         "An e-commerce landing page currently converts 1,000 visitors into 25 buyers (2.5% CVR). After implementing single-click Apple Pay checkout, conversions rise to 40 buyers from 1,000 visitors. What is the relative percentage improvement in Conversion Rate?",
         ["60.0% lift", "50.0% lift", "15.0% lift", "40.0% lift"], 0,
         "Calculation: Old CVR = 2.5%, New CVR = (40 / 1,000) * 100% = 4.0%. Relative lift = ((4.0 - 2.5) / 2.5) * 100% = (1.5 / 2.5) * 100% = 60.0%.",
         "Relative Improvement (%) = ((New CVR - Old CVR) / Old CVR) * 100",
         "Decision Architecture", "Google Ads Bidding Strategy Selection",
         "An established e-commerce business has tracked over 200 reliable purchase conversions per month in Google Ads and has strict profitability targets based on product margin. Which automated bidding strategy should be deployed?",
         ["Target ROAS (Target Return on Ad Spend)",
          "Maximize Clicks",
          "Manual CPC without Enhanced Bidding",
          "Target Impression Share (100% Absolute Top of Page)"], 0,
         "With high historical conversion volume (> 30-50 conversions/month) and strict margin goals, Target ROAS leverages Google's machine learning to optimize bids specifically for revenue value rather than click volume."),

        (6, "interview-question", "Explaining Multi-Touch Attribution (MTA) Models in an Interview",
         "The interviewer asks: 'Why is Last-Click attribution fundamentally flawed for brands running omnichannel campaigns across paid search, social, and display?'",
         "Explain Last-Click bias (over-crediting bottom-funnel search while starving top-of-funnel discovery), and compare with Data-Driven Attribution (DDA) or Shapley value models.",
         ["Last-Click Attribution Bias", "Data-Driven Attribution (DDA)", "Full-Funnel Value Distribution"],
         "Strategic Evaluation (Demonstrate full-funnel vision and multi-touch attribution mechanics)",
         "Last click is bad because it only gives credit to the last ad. We should use first click instead so social media gets credit.",
         "Simply replaces one flawed single-touch attribution model with another opposite single-touch model.",
         "Last-Click attribution creates an extreme distortion in budget allocation: it awards 100% of the conversion credit to the final touchpoint—typically a branded Google search or direct visit. This starves top-of-funnel channels like Meta video ads or TikTok discovery that initially introduced the customer to the brand. If leadership cuts top-of-funnel budget because 'last-click ROAS looks low', bottom-funnel branded search volume collapses weeks later because no new demand was generated. In modern marketing, we employ Google's Data-Driven Attribution (DDA) or algorithmic fractional attribution, which analyzes touchpoint combinations to assign fair fractional credit across the entire conversion path.",
         "Comprehensive, strategic answer: exposes the danger of starving top-of-funnel discovery and defends data-driven attribution.",
         "Never rely on Last-Click: it starves top-of-funnel awareness channels and leads to catastrophic demand collapse.",
         "Financial & Business Math", "Customer Lifetime Value to CAC Ratio (LTV:CAC)",
         "A subscription fitness app calculates its average Customer Lifetime Value (LTV) at $240.00. The performance marketing team reports an average Blended Customer Acquisition Cost (CAC) of $60.00. What is the company's LTV:CAC ratio?",
         ["4.0 : 1", "3.0 : 1", "2.5 : 1", "5.0 : 1"], 0,
         "Calculation: LTV:CAC Ratio = LTV / CAC = $240.00 / $60.00 = 4.0 to 1.",
         "LTV:CAC Ratio = Customer Lifetime Value / Customer Acquisition Cost",
         "Constraint Solving", "A/B Testing Statistical Sample Size Constraints",
         "A conversion rate optimization specialist runs an A/B test on a checkout button color. After 2 days and 80 total visitors, Version B has 4 conversions and Version A has 1 conversion (p-value 0.18). Should the team terminate the test and declare Version B the winner?",
         ["No: The sample size is far too small, the result is not statistically significant (p > 0.05), and early stopping risks high False Discovery Rates.",
          "Yes: Version B has 4x the conversions of Version A, proving superiority.",
          "Yes: Digital marketing tests should always conclude within 48 hours to save money.",
          "No: But they should immediately route 100% of ad spend to Version B anyway."], 0,
         "Underpowered tests evaluated prematurely suffer from random variance and peeking bias. Rigorous experimentation requires pre-calculated sample sizes and running through full business cycles."),

        (7, "workplace-scenario", "Managing Client Budget Reallocation from Underperforming Ads",
         "During a monthly review, an e-commerce client demands to cancel all Meta ad spend because its tracked ROAS is 1.8x, while Google Brand Search is generating a 9.2x ROAS.",
         "Educate the client on demand generation versus demand capture, explain branded search cannibalization, and negotiate a balanced blended media budget.",
         ["Demand Generation vs Demand Capture", "Branded Search Cannibalization", "Blended MER (Marketing Efficiency Ratio)"],
         "Strategic Client Counseling (Protect the client from self-sabotaging their customer acquisition pipeline)",
         "Fine, if you want to turn off Meta ads, we will move all your budget into Google Brand Search.",
         "Dangerous compliance that will destroy client revenue within 60 days as top-of-funnel discovery evaporates.",
         "I completely understand why a 9.2x ROAS on Google Brand Search looks far more attractive than a 1.8x on Meta. However, it is essential to distinguish between *demand capture* and *demand generation*. Google Brand Search captures users who *already know your brand name*—and our data shows that 68% of those users first discovered your brand through a Meta video ad. If we turn off Meta ads, you turn off the faucet of new prospects. Within 6 to 8 weeks, your branded search volume will dry up because nobody new is searching for you. Instead, let's evaluate our Blended Marketing Efficiency Ratio (MER = Total Revenue / Total Ad Spend), and reallocate 15% from Meta into high-intent Google Non-Brand search while refreshing our top-of-funnel Meta creatives.",
         "Masterful client consulting: exposes branded search as demand capture, warns of pipeline starvation, and introduces Blended MER.",
         "Remember: Branded search *captures* existing demand; Paid Social *generates* new demand. Never let a client turn off top-of-funnel discovery.",
         "Profit, Margin & ROI", "Blended Marketing Efficiency Ratio (MER) Calculation",
         "An apparel brand generates $120,000 in total net e-commerce sales across a month. Across all paid channels (Google Ads $15,000, Meta Ads $12,000, TikTok Ads $3,000), total advertising expenditure was $30,000. What is the brand's Blended Marketing Efficiency Ratio (MER)?",
         ["4.0x MER", "3.5x MER", "4.5x MER", "3.0x MER"], 0,
         "Calculation: Total Spend = $15,000 + $12,000 + $3,000 = $30,000. MER = Total Revenue / Total Ad Spend = $120,000 / $30,000 = 4.0x MER.",
         "MER = Total E-Commerce Revenue / Total Paid Media Spend",
         "Workflow Ordering", "Technical SEO Site Audit Execution Sequence",
         "When conducting an end-to-end technical SEO audit for an enterprise website, in what order should issues be diagnosed and prioritized?",
         ["Crawlability (Robots.txt, Server 5xx) -> Indexability (Meta Robots, Canonical Tags) -> Architecture & Internal Linking -> Page Speed & Core Web Vitals -> On-Page Content & Schema Markup",
          "Schema Markup -> Page Speed -> Robots.txt -> Canonical Tags -> Backlinks",
          "Backlinks -> On-Page Content -> Indexability -> Server Status -> Robots.txt",
          "Core Web Vitals -> Meta Robots -> Schema Markup -> Server Status -> Robots.txt"], 0,
         "Technical SEO must follow a hierarchical pyramid: search bots must first be able to crawl pages, then index them, then follow clean architecture, before on-page speed and content optimization can have any ranking impact."),

        (8, "technical-presentation", "Presenting Core Web Vitals to an Engineering & Executive Team",
         "Presenting the business impact of Google's Core Web Vitals (LCP, INP, CLS) to a joint meeting of the CMO and the VP of Engineering.",
         "Translate technical performance metrics (Largest Contentful Paint, Interaction to Next Paint, Cumulative Layout Shift) into user experience, bounce rates, and organic ranking gains.",
         ["Core Web Vitals (CWV)", "Largest Contentful Paint (LCP < 2.5s)", "Cumulative Layout Shift (CLS < 0.1)"],
         "Bridging Marketing & Engineering (Align marketing conversion goals with engineering technical performance)",
         "Engineers need to make the website faster because Google's Core Web Vitals update will penalize our SEO rankings.",
         "Antagonistic to engineering and fails to articulate specific metrics, benchmarks, or customer conversion upside.",
         "Core Web Vitals represent Google's official user experience benchmarks that directly influence both organic search rankings and checkout conversions. There are three core metrics: Largest Contentful Paint (LCP), which measures loading speed—our main image takes 4.2 seconds, and Google expects under 2.5 seconds; Cumulative Layout Shift (CLS), which measures visual stability—our jumping banners score 0.28 versus the 0.1 target; and Interaction to Next Paint (INP), measuring responsiveness. For our business, every 1-second delay in mobile LCP correlates with a 7% drop in checkout conversion. By optimizing hero image compression and reserving layout dimensions, engineering helps us capture an estimated $180,000 in recovered mobile sales while securing top Google rankings.",
         "Exceptional cross-functional presentation: defines the exact technical metrics, cites the official benchmarks, and quantifies the financial upside for both teams.",
         "When presenting Core Web Vitals to engineers: speak their language (LCP, INP, CLS) and connect performance optimizations to recovered revenue.",
         "Percentages & Growth", "Email Marketing Click-to-Open Rate (CTOR) Calculation",
         "A promotional email newsletter is delivered to 50,000 subscribers. 10,000 recipients open the email. Of those who opened the email, 1,200 recipients click on a promotional product link. What is the Click-to-Open Rate (CTOR) of this newsletter?",
         ["12.0%", "10.0%", "2.4%", "15.0%"], 0,
         "Calculation: CTOR measures clicks divided by unique opens (not total delivered). CTOR = (1,200 / 10,000) * 100% = 0.12 * 100% = 12.0%.",
         "CTOR (%) = (Clicks / Opens) * 100",
         "Process Flow", "Cart Abandonment Email Lifecycle Automation Flow",
         "What is the most effective behavioral timing sequence for an automated 3-part e-commerce cart abandonment email flow?",
         ["Email 1: Helpful reminder & customer support check-in (1 hour post-abandonment) -> Email 2: Social proof & product reviews (24 hours) -> Email 3: Time-sensitive discount or free shipping incentive (48-72 hours)",
          "Email 1: 50% discount coupon immediately after 5 minutes -> Email 2: Final cancellation threat -> Email 3: Apology letter",
          "Email 1: Send 1 week later -> Email 2: Send 2 weeks later -> Email 3: Send 1 month later",
          "Email 1: Send newsletter -> Email 2: Send product catalog -> Email 3: Unsubscribe notification"], 0,
         "Best-practice cart abandonment starts with a low-friction customer service reminder at 1 hour, adds social proof at 24 hours, and preserves margin by offering financial discounts only as a last resort at 48-72 hours."),

        (9, "manager-conversation", "Negotiating Growth Target Expectations with an Ambitious CEO",
         "A CEO demands that the marketing team increase monthly revenue by 300% in 90 days while simultaneously slashing customer acquisition costs by 50%.",
         "Diplomatically manage executive expectations, explain the economic laws of paid media scaling and diminishing marginal returns, and present a realistic high-growth roadmap.",
         ["Diminishing Marginal Returns in Paid Media", "Auction Saturation / CPM Inflation", "Sustainable Scaling Roadmap"],
         "Executive Realism & Strategic Diplomacy (Ground growth ambitions in auction marketplace mechanics while offering an aggressive plan)",
         "That's completely impossible. You can't triple revenue and cut CAC in half at the same time, nobody can do that.",
         "Confrontational and career-limiting. Rejects executive vision without explaining the underlying economic constraints.",
         "I share your aggressive ambition to dramatically scale our market leadership! However, in digital ad auctions, scaling spend rapidly inherently encounters diminishing marginal returns: as we expand beyond our core high-intent audience into broader demographics, auction CPMs rise and conversion propensity softens, which naturally increases CAC initially rather than decreasing it. Attempting a 300% surge while halving CAC violates paid media marketplace mechanics. Instead, I propose a high-velocity 3-pillar growth strategy: we can realistically achieve 80% to 100% revenue growth in 90 days by scaling top-performing Meta Lookalikes, launching Google Performance Max, and deploying a referral advocacy program that lowers blended CAC organically over time.",
         "Diplomatic, highly strategic, educates the CEO on auction marketplace dynamics, and provides a compelling high-growth alternative.",
         "Never just say 'that is impossible'. Explain the economic law of diminishing marginal returns in ad auctions and propose an aggressive, achievable target.",
         "Financial & Business Math", "Paid Search Impression Share Loss Due to Budget",
         "A company's top-performing Google Ads campaign captures 60% Search Impression Share. Google Ads reports that 30% of potential impression share is lost due to budget constraints, while only 10% is lost due to Ad Rank. If the campaign currently generates $12,000/month at a 4.0x ROAS, how much incremental monthly revenue can realistically be unlocked by expanding budget to capture that lost share?",
         ["$6,000 / month", "$4,000 / month", "$8,000 / month", "$3,500 / month"], 0,
         "Calculation: Current captured share = 60%. Lost share due to budget = 30% (which represents half of the current captured volume: 30% / 60% = 50% additional traffic). Incremental revenue = $12,000 * (30% / 60%) = $12,000 * 0.50 = $6,000 per month.",
         "Incremental Revenue = Current Revenue * (Lost Budget Share / Captured Share)",
         "Debugging Logic", "Resolving Google Tag Manager (GTM) Conversion Tag Misconfigurations",
         "A GA4 purchase event tag configured in Google Tag Manager fires twice whenever a user completes an order, artificially inflating recorded revenue by 100%. What is the technical root cause?",
         ["The GTM trigger is firing on both the custom dataLayer 'purchase' event AND on the generic pageview of the thank-you URL.",
          "Google Analytics 4 is incompatible with Google Tag Manager.",
          "The user's credit card was billed twice by Stripe.",
          "The website hosting provider has an outdated SSL certificate."], 0,
         "Double-counting conversions in GTM typically occurs when both a custom dataLayer push trigger and a URL destination pageview trigger fire on the identical confirmation page load."),

        (10, "email-response", "Writing a Professional Client Pitch for TikTok & YouTube Shorts Diversification",
         "Draft an email to a traditional B2C client explaining why diversifying 20% of their paid media budget from Meta into short-form vertical video (TikTok and YouTube Shorts) is critical for brand longevity.",
         "Articulate shifting consumer attention, lower CPM auctions on emerging platforms, and creative testing synergies across vertical formats.",
         ["Vertical Short-Form Video", "Cross-Platform Creative Repurposing", "Auction CPM Arbitrage"],
         "Persuasive Client Education (Build an attractive business case around audience diversification and lower acquisition costs)",
         "Hey client, Facebook is getting old and expensive. You need to start doing TikTok and YouTube Shorts ads now.",
         "Informal, denigrates the client's existing profitable channel, and lacks concrete media metrics.",
         "Subject: Strategic Media Proposal: Unlocking Growth via Vertical Video Diversification\n\nDear Sarah,\n\nOver the past two quarters, our Meta ad campaigns have delivered stellar results, maintaining a steady 3.4x ROAS. However, as customer attention continues shifting toward short-form vertical video, relying 100% on a single platform creates single-source vulnerability and exposes our margins to seasonal Meta CPM surges.\n\nWe recommend allocating an initial 20% test budget ($6,000/month) toward TikTok Ads and YouTube Shorts. The strategic advantages are clear:\n1. CPM Arbitrage: TikTok auction CPMs are currently 35% lower than Meta, allowing us to acquire top-of-funnel reach at a fraction of the cost.\n2. Creative Synergies: High-performing UGC video concepts developed for Instagram Reels can be repurposed directly onto TikTok and Shorts with zero incremental production overhead.\n3. Incremental Reach: Our cross-platform analysis reveals that 42% of active TikTok users are not active on Instagram daily.\n\nWe have outlined a 60-day test framework with clear CPA benchmarks. Let's discuss this on our Thursday strategy call.\n\nBest regards,\nPerformance Marketing Team",
         "Professional, compelling, cites exact media advantages (lower CPM, creative repurposing, unduplicated reach), and establishes clear test benchmarks.",
         "When pitching channel diversification, highlight: platform risk mitigation, lower auction CPMs, and creative repurposing synergies.",
         "Percentages & Growth", "CPM (Cost Per Mille / Thousand Impressions) Calculation",
         "A programmatic display brand campaign costs $4,800.00 and serves 800,000 total ad impressions across premium news publisher websites. What is the Cost Per Mille (CPM) of this campaign?",
         ["$6.00", "$5.50", "$6.50", "$7.00"], 0,
         "Calculation: CPM = (Total Ad Spend / Total Impressions) * 1,000 = ($4,800.00 / 800,000) * 1,000 = $0.006 * 1,000 = $6.00.",
         "CPM = (Total Spend / Total Impressions) * 1,000",
         "Workflow Ordering", "A/B Creative Testing Workflow for Paid Social Ads",
         "What is the correct sequential methodology for running an A/B creative test in Meta Ads Manager?",
         ["Isolate One Variable (e.g., Hook / First 3 Seconds) -> Keep Copy & Headline Identical -> Run Against Broad Audience with Sufficient Budget -> Measure 3-Second Hook Rate & Hold Rate -> Scale Winning Hook into Broad Production Campaigns",
          "Change Hook, Copy, Headline, and Destination URL all at once -> Run for 2 hours -> Pick the cheapest ad",
          "Scale winning ad to $10,000/day before testing -> Review metrics next month",
          "Test creatives inside a retargeting audience with 200 people"], 0,
         "Rigorous creative testing requires isolating a single variable (such as the first 3-second hook) while holding all other elements constant, evaluating hook and hold retention rates before scaling to production."),

        (11, "conflict-resolution", "Resolving Strategy Disagreements Between Brand and Performance Teams",
         "The Brand Marketing Director and the Performance Marketing Director clash: Brand wants to allocate $50,000 to an unmeasurable influencer lifestyle video, while Performance wants to put all $50,000 into Google Search Ads.",
         "Mediate the dispute with an objective 70-20-10 innovation budget framework that funds measurable brand discovery while protecting immediate revenue targets.",
         ["70-20-10 Marketing Framework", "Brand Equity vs Performance Harvest", "Trackable Influencer Whitelisting"],
         "Strategic Reconciliation (Bridge the brand-performance divide through measurable creator licensing and balanced allocation)",
         "We should give all the money to performance search ads because brand marketing is just a waste of money that can't be tracked in Google Analytics.",
         "Short-sighted and ignores the fundamental role of brand storytelling in fueling future search demand.",
         "Both perspectives represent vital halves of a complete growth engine: Performance Marketing is correct that search ads capture immediate, high-intent cash flow, while Brand Marketing is correct that without fresh cultural awareness and brand resonance, our search pool will shrink and customer acquisition costs will climb. I propose applying the 70-20-10 framework: we allocate 70% ($35,000) directly to our validated high-ROAS Google and Meta performance campaigns. We allocate the remaining 30% ($15,000) to the influencer campaign, but with a performance hybrid structure: the creator creates the lifestyle asset, and we run it via 'Creator Whitelisting / Spark Ads' with trackable UTMs and dedicated landing page discounts. This delivers emotional brand storytelling while giving performance the click-level conversion data we need.",
         "Masterful executive mediation: validates both leaders, introduces creator whitelisting as a bridge, and preserves financial accountability.",
         "Bridge brand and performance through Creator Whitelisting / Meta Partnership Ads: brand gets authentic storytelling, and performance gets trackable ad units.",
         "Financial & Business Math", "Influencer Campaign Cost Per Engagement (CPE) Calculation",
         "A beauty brand pays an influencer $2,500.00 for a sponsored Instagram Reel. The Reel achieves 125,000 video views, 8,000 likes, 1,500 saves, and 500 comments (10,000 total engagements). What is the Cost Per Engagement (CPE) for this collaboration?",
         ["$0.25", "$0.20", "$0.30", "$0.15"], 0,
         "Calculation: Total engagements = 8,000 + 1,500 + 500 = 10,000 engagements. CPE = Spend / Engagements = $2,500.00 / 10,000 = $0.25 per engagement.",
         "Cost Per Engagement = Total Fee / Total Social Engagements",
         "Deductive Analysis", "Identifying Brand Search Bidding Cannibalization",
         "A company ranks #1 organically on Google for its unique, trademarked brand name. When the paid search team launches a branded search campaign bidding $1.50/click, total organic clicks drop by 60%, while paid clicks rise by 65%, resulting in a net 5% traffic gain at a $12,000 monthly cost. How should this be evaluated?",
         ["Brand Cannibalization: Paid ads are capturing traffic that would have visited organically for free. The team should test reducing bids or pausing brand search to evaluate incremental net revenue.",
          "Brilliant Success: The team achieved total domination of the search page and should double the budget.",
          "SEO Failure: The organic ranking dropped because of Google penalties.",
          "Competitor Attack: Competitors are clicking the paid ads repeatedly."], 0,
         "Bidding aggressively on uncontested brand terms often cannibalizes organic traffic that was already guaranteed for free. Incremental lift testing determines whether brand bidding provides true incremental conversions."),

        (12, "hr-question", "Answering: 'How Do You Manage Client Attribution When iOS Tracking Fails?'",
         "An agency interviewer asks: 'Clients constantly panic when their ad platform dashboards disagree with Google Analytics. How do you explain discrepancies and instill confidence in marketing data?'",
         "Articulate the difference between ad platform self-attributing networks (SANs), view-through attribution windows, browser cookie depreciation, and holistic Blended MER reporting.",
         ["Self-Attributing Networks (SANs)", "View-Through vs Click-Through Attribution", "Holistic Blended MER"],
         "Methodological Authority (Educate the interviewer on data discrepancy realities and executive reporting standards)",
         "I tell the client that Facebook always lies and inflates its numbers, so they should only trust Google Analytics.",
         "Inaccurate and unhelpful. Fails to understand view-through conversions or post-iOS 14 modeled reporting.",
         "Data discrepancies between ad platforms and Google Analytics are not bugs—they are inherent architectural differences. Ad platforms like Meta use self-attributing models that include both 7-day click and 1-day view-through conversions, whereas Google Analytics 4 defaults to a last-click or data-driven attribution window that cannot track cross-app view-through impressions. If a customer views an Instagram ad, doesn't click, but searches the brand on desktop 3 hours later and buys, Meta claims 1 conversion while GA4 credits organic search. In client reporting, I educate stakeholders on these mechanics upfront and anchor our source of truth in business-level unit economics: Blended Marketing Efficiency Ratio (MER = Total Revenue / Total Spend) and new customer acquisition velocity.",
         "Flawless industry answer: clearly distinguishes view-through from click-through attribution and elevates reporting to executive Blended MER.",
         "Explain attribution discrepancies: Meta tracks view-through and cross-device journeys; GA4 tracks website sessions. Use Blended MER as the ultimate truth.",
         "Combinatorics & Permutations", "Omnichannel Multi-Variant Creative Ad Assembly",
         "A paid media manager designs a dynamic creative ad test with 4 unique video hooks, 3 different body copy variations, and 2 call-to-action buttons. How many total ad creative permutations are tested across the audience?",
         ["24 variations", "18 variations", "32 variations", "12 variations"], 0,
         "Calculation: Permutations = 4 hooks * 3 copy variants * 2 CTAs = 24 unique creative variations.",
         "Total Combinations = Hooks * Copy * CTAs",
         "Constraint Solving", "Google Ads Target CPA Bid Ceiling Constraints",
         "A lead generation campaign using Target CPA bidding is set to a target of $50.00. However, the market clearing cost to win an enterprise click in this auction requires a bid of $65.00. What will happen to campaign delivery?",
         ["The Google bidding algorithm will suppress impression volume and enter fewer auctions, causing daily ad spend and lead volume to plummet.",
          "Google will automatically increase the daily budget by 500% to win the auction.",
          "The campaign will achieve a 100% conversion rate automatically.",
          "Google will ban the advertiser account for bidding below market clearing price."], 0,
         "When Target CPA is set unrealistically below the market clearing auction cost, automated bidding restricts bids to protect the CPA goal, resulting in severe traffic throttling and missed delivery."),

        (13, "interview-question", "Explaining SEO E-E-A-T and Helpful Content System to an Interviewer",
         "The interviewer asks: 'What does Google's E-E-A-T framework stand for, and how do you optimize a website to survive Google's Helpful Content System updates?'",
         "Explain Experience, Expertise, Authoritativeness, and Trustworthiness (E-E-A-T), first-person authentic demonstrations, author schemas, and removing unhelpful mass-generated AI content.",
         ["E-E-A-T Guidelines", "First-Hand Experience", "Helpful Content System / Information Gain"],
         "Holistic Content Authority (Prioritize genuine human value, original testing, and domain authority over keyword stuffing)",
         "E-E-A-T is just adding author bios to blog posts and making sure articles are over 2,000 words long with keywords.",
         "Shallow and outdated. Fails to understand Google's emphasis on genuine first-hand testing and information gain.",
         "E-E-A-T stands for Experience, Expertise, Authoritativeness, and Trustworthiness—with Trust at the core. Under Google's Helpful Content System and Quality Rater Guidelines, search algorithms prioritize 'Information Gain'—content that provides unique value beyond what is already regurgitated across the web. We optimize for this by: first, demonstrating genuine first-hand Experience through original product teardowns, proprietary customer survey data, and authentic photography rather than stock photos; second, substantiating Expertise with verified author schema markup and credentials; and third, pruning low-quality, programmatic content that was written purely for search engines rather than human readers.",
         "Inspiring, cutting-edge SEO authority: emphasizes 'Information Gain', original proprietary data, and pruning low-value content.",
         "For modern SEO: focus on 'Information Gain' and genuine first-hand experience (original testing, real photos, proprietary data) to satisfy E-E-A-T.",
         "Averages & Distributions", "Average Order Value (AOV) Metric Calculation",
         "Over a 30-day e-commerce campaign, an online fashion store generates $180,000 in gross revenue across 2,400 completed orders. What is the store's Average Order Value (AOV)?",
         ["$75.00", "$70.00", "$80.00", "$85.00"], 0,
         "Calculation: AOV = Total Gross Revenue / Total Completed Orders = $180,000 / 2,400 = $75.00.",
         "AOV = Gross Revenue / Total Orders",
         "Debugging Logic", "Diagnosing Disapproved Google Merchant Center Product Feeds",
         "An e-commerce store's entire Google Shopping feed is disapproved due to 'Mismatched price and availability'. What is the root cause?",
         ["The prices or stock availability in the automated Google Merchant Center XML feed do not match the real-time prices displayed on the landing page schema markup.",
          "The store is selling products that are illegal in international jurisdictions.",
          "The Google Merchant Center account has exceeded its daily click quota.",
          "The product photos do not have white backgrounds."], 0,
         "Googlebot constantly crawls product landing pages and compares the structured data microdata (schema.org) with the submitted feed; any discrepancy triggers automated feed suspension for price/stock mismatch."),

        (14, "workplace-scenario", "Managing Google Analytics 4 (GA4) Custom Event Architecture",
         "A product manager wants to track 120 custom interaction buttons by creating 120 unique event names in GA4 (e.g., `clicked_red_button_homepage`, `clicked_blue_button_cart`).",
         "Explain GA4 event parameter architecture, the recommended event naming conventions, and how event parameters prevent hitting GA4 custom event limits.",
         ["GA4 Event Parameter Model", "Event Naming Best Practices", "Custom Dimension Limits"],
         "Architectural Discipline (Standardize event taxonomies to preserve analytical reporting cleanliness)",
         "Sure, we can create 120 event names if you want, but GA4 might get a bit messy.",
         "Lacks governance. Will cause the property to hit GA4's strict limit of 50 custom event parameters and clutter reports.",
         "In GA4's event-driven data model, creating 120 unique event names is an anti-pattern that will quickly exhaust our property limits and make cross-funnel reporting impossible. Instead, GA4 is architected around structured *event parameters*. We should standardize on a single, reusable action event—such as `cta_click`—and pass contextual details as parameters: `button_name`, `button_location`, and `destination_url`. This consolidates 120 bloated event names into 1 clean event, stays well within GA4 limits, and allows us to build powerful funnel exploration reports comparing all button clicks in a single dashboard.",
         "Authoritative analytics leadership: explains the modern parameter data model and saves the company from hitting irreversible property limits.",
         "GA4 best practice: Use standardized event names (e.g., `cta_click`) and pass specific attributes via event parameters.",
         "Percentages & Growth", "Paid Social Customer Acquisition Cost (CAC) Reduction",
         "In Q1, a Direct-to-Consumer brand spent $60,000 to acquire 1,000 customers ($60.00 CAC). In Q2, after optimizing ad creatives and expanding to lookalikes, they spent $60,000 and acquired 1,250 customers. What is the percentage reduction in CAC?",
         ["20.0% reduction", "25.0% reduction", "15.0% reduction", "18.0% reduction"], 0,
         "Calculation: Q1 CAC = $60.00. Q2 CAC = $60,000 / 1,250 = $48.00. Reduction = (($60.00 - $48.00) / $60.00) * 100% = ($12.00 / $60.00) * 100% = 0.20 * 100% = 20.0% reduction.",
         "CAC Reduction (%) = ((Old CAC - New CAC) / Old CAC) * 100",
         "Workflow Ordering", "Search Engine Optimization (SEO) Keyword Research Pipeline",
         "What is the correct sequential workflow for conducting keyword research for a new commercial product category?",
         ["Seed Keyword Brainstorming -> Search Volume & Keyword Difficulty (KD) Analysis -> Search Intent Categorization (Informational, Commercial, Transactional) -> Competitor SERP Analysis -> Content Mapping & URL Strategy",
          "Publish Articles First -> Check Search Volume Afterwards -> Pick Seed Keywords",
          "Keyword Difficulty Analysis -> Publish -> Brainstorm Seeds -> Categorize Intent",
          "Competitor SERP Analysis -> Publish Identical Content -> Check Search Volume"], 0,
         "Effective keyword research begins with discovering broad seed terms, filtering by volume and competition difficulty, classifying user intent, analyzing existing ranking SERPs, and mapping primary/secondary terms to dedicated target URLs."),

        (15, "technical-explanation", "Explaining Lookalike Audiences and Seed Quality to a Client",
         "A client asks why their 1% Lookalike Audience generated from 10,000 general newsletter subscribers performed terribly, while a Lookalike generated from 500 VIP repeat buyers delivered a 4.5x ROAS.",
         "Explain machine learning Lookalike modeling: how algorithm pattern recognition is entirely dependent on the purity and high intent of the seed audience ('garbage in, garbage out').",
         ["Lookalike Audience Modeling", "Seed Audience Purity", "Value-Based Lookalikes"],
         "Algorithmic Understanding (Explain how seed quality dictates machine learning predictive accuracy)",
         "The 500 buyer lookalike worked better because buyers are better than email subscribers.",
         "Oversimplified and textbook-level. Fails to explain the machine learning feature extraction process.",
         "Lookalike algorithms operate like high-dimensional pattern detectors: Meta analyzes thousands of behavioral signals across your seed list—such as browsing habits, purchase history, and demographics—to find the 1% of users who most closely match that profile. When we feed it 10,000 general newsletter subscribers, the list is diluted with discount hunters and inactive users; the algorithm extracts weak, generic patterns and finds more casual browsers. But when we seed it with 500 VIP repeat buyers, every single profile has high purchasing power and deep brand affinity. The algorithm identifies ultra-pure commercial traits, delivering high-intent shoppers who convert at a 4.5x ROAS.",
         "Superb demonstration of algorithmic intuition: contrasts diluted seeds with high-intent customer value seeds.",
         "Remember: Lookalike performance is 100% determined by seed purity. Always build Lookalikes from top 20% LTV customers rather than generic subscribers.",
         "Financial & Business Math", "Break-Even Return on Ad Spend (ROAS) Calculation",
         "An online retail store sells products with an average gross profit margin of 25.0% (meaning cost of goods, shipping, and merchant fees total 75% of sales price). What is the exact Break-Even ROAS required for this store's paid advertising?",
         ["400% (or 4.0x)", "300% (or 3.0x)", "250% (or 2.5x)", "500% (or 5.0x)"], 0,
         "Calculation: Break-Even ROAS = 1 / Gross Profit Margin % = 1 / 0.25 = 4.0 or 400%.",
         "Break-Even ROAS = 1 / Gross Margin Percentage",
         "Debugging Logic", "Diagnosing Meta Ad Learning Limited Status",
         "A Meta Ads ad set enters 'Learning Limited' status after 7 days. What is the primary cause, and how should it be remediated?",
         ["The ad set failed to generate the required 50 optimization events within a 7-day window; consolidate fragmented ad sets or optimize for an upper-funnel event (e.g., Add to Cart).",
          "The daily budget is exceeding the maximum allowable credit line.",
          "The ad creative contains more than 20% text.",
          "The company Meta Business Page has fewer than 1,000 followers."], 0,
         "Meta's machine learning model requires approximately 50 conversion events per week to exit the learning phase. Under-budgeted or hyper-fragmented ad sets get stuck in 'Learning Limited', cured by budget scaling or ad set consolidation."),
    ]

    for s in foundations:
        days.append({
            "day": s[0],
            "commType": s[1],
            "commTitle": s[2],
            "commScenario": s[3],
            "commPrompt": s[4],
            "commVocab": s[5],
            "commRule": s[6],
            "commWeakResponse": s[7],
            "commWeakCritique": s[8],
            "commStrongResponse": s[9],
            "commStrongCritique": s[10],
            "commCoachTip": s[11],
            "aptTopic": s[12],
            "aptTitle": s[13],
            "aptQuestion": s[14],
            "aptOptions": s[15],
            "aptAnswer": s[16],
            "aptExplanation": s[17],
            "aptFormula": s[18],
            "logicType": s[19],
            "logicTitle": s[20],
            "logicQuestion": s[21],
            "logicOptions": s[22],
            "logicAnswer": s[23],
            "logicExplanation": s[24],
        })

    # Systematic phase topics for Days 16 to 89
    phase_definitions = [
        # Phase 2: Days 16-30 (Search Engine Optimization Mastery)
        (16, 30, "SEO Mastery", [
            ("Search Intent Classification: Informational vs Transactional", "SEO Fundamentals", "Aligning content format and CTA with exact Google user search intent.", ["Search Intent", "SERP Feature Mapping"]),
            ("On-Page Optimization: Title Tag, H1, Meta Description Hierarchy", "On-Page SEO", "Writing click-worthy title tags with keyword prominence and emotional hooks.", ["Title Tag Prominence", "Click-Through Optimization"]),
            ("URL Structure and Semantic Hierarchy Best Practices", "Information Architecture", "Creating clean, short, static URLs that convey categorical hierarchy.", ["Semantic URL Structure", "Breadcrumb Trail"]),
            ("Internal Linking Architecture and Link Equity Distribution", "Site Architecture", "Distributing PageRank from high-authority hub pages to deep commercial pages.", ["PageRank Flow", "Anchor Text Optimization"]),
            ("Robots.txt Directives and Disallow / Crawl-Delay Management", "Technical SEO", "Guiding search bot crawl budgets away from staging environments and search filters.", ["Robots.txt Rules", "Crawl Budget Optimization"]),
            ("XML Sitemaps and Index Coverage in Google Search Console", "Search Console", "Validating submitted sitemaps and troubleshooting 'Crawled - Currently Not Indexed'.", ["Index Coverage Status", "Canonical Consistency"]),
            ("Schema Markup (JSON-LD) for Rich Snippets (Product, Review, FAQ)", "Structured Data", "Implementing structured data to trigger rich star ratings and FAQ dropdowns.", ["JSON-LD Structured Data", "Rich Snippets"]),
            ("Core Web Vitals: Largest Contentful Paint (LCP) Optimization", "Speed Performance", "Compressing WebP images and eliminating render-blocking CSS/JS.", ["LCP Latency", "Render-Blocking Resources"]),
            ("Core Web Vitals: Cumulative Layout Shift (CLS) Prevention", "Visual Stability", "Specifying explicit width and height dimensions on images and dynamic ads.", ["CLS Benchmark < 0.1", "Reserved Layout Boxes"]),
            ("Core Web Vitals: Interaction to Next Paint (INP) Responsiveness", "User Experience", "Minimizing JavaScript main-thread execution time for snappy button clicks.", ["INP Benchmark < 200ms", "Main-Thread Bottlenecks"]),
            ("White-Hat Link Building: Digital PR and Unlinked Brand Mentions", "Off-Page SEO", "Earning high-authority editorial backlinks through proprietary data studies.", ["Digital PR Link Earning", "Editorial Backlinks"]),
            ("Competitor Backlink Gap Analysis with Ahrefs / Semrush", "Competitive Analysis", "Identifying recurring referring domains that link to top ranking competitors.", ["Domain Rating / Authority", "Link Intersect Tool"]),
            ("Handling 301 Permanent Redirects and Avoiding Redirect Chains", "Technical Remediation", "Preserving link equity during website migrations and eliminating redirect hops.", ["301 Redirect Equity", "Redirect Loop Elimination"]),
            ("International SEO: Hreflang Tags and Geo-Targeting", "Global SEO", "Serving regional language variations without duplicate content penalties.", ["Hreflang Annotations", "Country-Code TLDs vs Subfolders"]),
            ("Phase 2 Placement Milestone: Enterprise Technical SEO Audit Defense", "Client Defense", "Presenting a 100-page enterprise technical SEO roadmap to executive leadership.", ["Technical SEO Roadmap", "Organic Revenue Forecasting"]),
        ]),

        # Phase 3: Days 31-45 (SEM & Google Ads Mastery)
        (31, 45, "Google Ads Mastery", [
            ("Google Ads Keyword Match Types: Broad, Phrase, and Exact", "Search Architecture", "Balancing broad match exploration with negative keyword governance.", ["Match Type Evolution", "Query Expansion"]),
            ("Negative Keyword Strategy and Search Terms Report Scrubbing", "Budget Protection", "Filtering out irrelevant search queries to prevent wasted ad expenditure.", ["Negative Match Lists", "Search Query Mining"]),
            ("Responsive Search Ads (RSA): Headline and Description Pinning", "Creative Optimization", "Testing multiple headlines while pinning required brand compliance copy.", ["Responsive Search Ads", "Ad Strength Rating"]),
            ("Google Ads Quality Score Diagnostic Components", "Auction Efficiency", "Improving landing page speed and ad copy relevance to slash CPCs.", ["Quality Score Matrix", "Expected CTR Enhancement"]),
            ("Target CPA vs Target ROAS Smart Bidding Mechanics", "Automated Bidding", "Configuring target bidding thresholds based on profit margin economics.", ["Target CPA Algorithm", "Target ROAS Optimization"]),
            ("Performance Max (PMax) Campaigns: Asset Groups and Signals", "PMax Architecture", "Providing rich first-party audience signals to steer Google's AI bidding.", ["Asset Group Diversity", "First-Party Audience Signals"]),
            ("Google Shopping Campaigns: Feed Optimization and Custom Labels", "E-Commerce SEM", "Using custom labels to segment high-margin vs low-margin inventory in feeds.", ["Merchant Center Feed", "Custom Margin Labels"]),
            ("Google Display Network (GDN) and Placement Exclusions", "Display Advertising", "Excluding low-quality mobile gaming apps and click-fraud websites.", ["GDN Placement Audit", "Click-Fraud Mitigation"]),
            ("YouTube In-Stream Video Ads: Bumper Ads vs TrueView", "Video Advertising", "Designing 6-second bumper ads for reach and skippable ads for action.", ["TrueView for Action", "6-Second Bumper Sequencing"]),
            ("Google Ads Conversion Tracking with Enhanced Conversions", "Conversion Fidelity", "Hashing first-party customer data to recover lost conversion signals.", ["Enhanced Conversions", "Hashed First-Party Data"]),
            ("Auction Insights Analysis: Outranking Competitor Domains", "Competitive Intelligence", "Tracking competitor overlap rate, outranking share, and position above rate.", ["Auction Insights Report", "Overlap & Outranking Share"]),
            ("Google Ads Scripts for Automated Budget Pacing and Anomaly Alerting", "Automation", "Deploying JavaScript scripts to pause underperforming campaigns automatically.", ["Google Ads Scripts", "Automated Pacing Guards"]),
            ("Local Services Ads (LSA) and Google Business Profile Optimization", "Local Search", "Capturing top-of-funnel local Google Guaranteed leads with high intent.", ["Google Guaranteed", "Local Services Ads"]),
            ("Remarketing Lists for Search Ads (RLSA) Dynamic Bidding", "Search Retargeting", "Bidding aggressively on broad search terms when typed by past buyers.", ["RLSA Strategy", "Tiered Bid Adjustments"]),
            ("Phase 3 Placement Milestone: Paid Search Account Restructure Review", "Account Defense", "Presenting full account restructure and Smart Bidding transition to CMO.", ["Account Hierarchy", "Smart Bidding Transition"]),
        ]),

        # Phase 4: Days 46-60 (Paid Social Advertising Mastery)
        (46, 60, "Paid Social Mastery", [
            ("Meta Ads Manager Hierarchy: Campaigns, Ad Sets, and Ads", "Paid Social Architecture", "Aligning objective selection with campaign budget optimization (Advantage+).", ["Campaign Budget Optimization", "Ad Set Segmentation"]),
            ("Advantage+ Shopping Campaigns (ASC) vs Manual Setup", "Meta AI Advertising", "Balancing automated machine learning scaling with manual audience controls.", ["Advantage+ Shopping", "Existing Customer Budget Cap"]),
            ("Creative Diversity: Video Hooks, Statics, Carousels, and UGC", "Creative Strategy", "Structuring creative libraries to conquer ad fatigue and appeal to different buyer motives.", ["User-Generated Content (UGC)", "Creative Diversity"]),
            ("Developing High-Converting 3-Second Video Hooks", "Video Creative", "Stopping user scrolling with visual pattern interrupts and high-contrast text.", ["Thumb-Stop Ratio", "3-Second Hook Rate"]),
            ("Custom Audiences: Customer List Uploads and Website Retargeting", "First-Party Audiences", "Hashing high-LTV customer lists to train Meta's algorithmic targeting.", ["Customer List Match Rate", "Dynamic Retargeting"]),
            ("Value-Based Lookalike Audiences from Purchase Value Seeds", "Algorithmic Prospecting", "Generating lookalikes weighted by customer spending volume rather than count.", ["Value-Based Lookalikes", "High-LTV Seed Lists"]),
            ("TikTok Ads Manager: Spark Ads and Trend Jacking", "TikTok Advertising", "Boosting organic creator content into commercial ads with native UX.", ["TikTok Spark Ads", "Sound-On Creative Strategy"]),
            ("LinkedIn Campaign Manager: B2B Lead Gen Forms and Job Title Targeting", "B2B Social", "Capturing verified professional business leads inside auto-filled native forms.", ["LinkedIn Lead Gen Forms", "Matched Audiences"]),
            ("Pinterest Ads: Visual Search and Intent-Driven Pin Promos", "Visual Discovery", "Reaching high-income female shoppers during the planning and inspiration phase.", ["Promoted Pins", "Visual Search Intent"]),
            ("Meta Conversions API (CAPI) and Event Deduplication", "Tracking Resilience", "Synchronizing browser pixel events with server-side CAPI event IDs.", ["Event ID Deduplication", "Event Quality Score > 8.0"]),
            ("A/B Creative Split Testing vs Dynamic Creative Optimization (DCO)", "Testing Protocols", "Measuring true lift across isolated variables without machine learning bias.", ["Isolated Split Testing", "Dynamic Creative Optimization"]),
            ("Managing Ad Frequency and Creative Fatigue in Small Audiences", "Frequency Control", "Rotating ad copy and refreshing creative assets when frequency surpasses 3.5.", ["Ad Frequency Cap", "Creative Rotation Cadence"]),
            ("Influencer Whitelisting / Meta Partnership Ads", "Creator Ads", "Running paid ads directly through creator social handles for higher credibility.", ["Partnership Ads", "Creator Handle Licensing"]),
            ("Omnichannel Retargeting: Coordinating Meta, Google, and Email", "Funnel Orchestration", "Guiding abandoners through timed, synchronized cross-platform touches.", ["Omnichannel Retargeting", "Coordinated Touchpoints"]),
            ("Phase 4 Placement Milestone: Paid Social Scaling & Creative Defense", "Campaign Review", "Defending creative production pipeline and $100K/month scaling to client.", ["Creative Production Velocity", "Scaling Blueprint"]),
        ]),

        # Phase 5: Days 61-75 (Web Analytics, GA4, Email & Lifecycle CRM)
        (61, 75, "Analytics & Lifecycle", [
            ("Google Analytics 4 (GA4) Data Model: Events and Parameters", "Analytics Architecture", "Transitioning from Universal Analytics session hits to GA4 event architecture.", ["GA4 Event Architecture", "Custom Parameter Mapping"]),
            ("GA4 Funnel Exploration Reports: Identifying Drop-Off Steps", "Funnel Analysis", "Visualizing step-by-step checkout abandonment across user device segments.", ["Funnel Exploration", "Abandonment Step Analysis"]),
            ("GA4 Path Exploration and Reverse Goal Flow Tracking", "User Behavior", "Discovering unexpected customer navigation paths leading to purchase.", ["Path Exploration", "Looping Navigation Discovery"]),
            ("UTM Parameter Governance and Campaign Tracking Hygiene", "Tracking Standards", "Standardizing utm_source, utm_medium, utm_campaign, and utm_content taxonomies.", ["UTM Parameter Hygiene", "Tracking Governance"]),
            ("Google BigQuery Export for GA4 Raw Event Analysis", "Advanced Analytics", "Querying raw unsampled event logs with SQL for custom cohort analyses.", ["BigQuery Raw Export", "Unsampled SQL Queries"]),
            ("Email Deliverability: SPF, DKIM, DMARC, and Domain Warm-Up", "Email Infrastructure", "Authenticating sending domains to prevent emails from landing in spam folders.", ["SPF / DKIM / DMARC", "Sender Reputation Warm-Up"]),
            ("Email Segmentation: RFM (Recency, Frequency, Monetary) Modeling", "CRM Segmentation", "Segmenting subscribers into Champions, Loyalists, and At-Risk categories.", ["RFM Segmentation", "Targeted Lifecycle Messaging"]),
            ("Automated Welcome Email Series: Brand Story and First-Order Incentive", "Lifecycle Automation", "Converting new subscribers into buyers during peak initial engagement.", ["Welcome Series", "First-Purchase Conversion"]),
            ("Customer Win-Back and Sunset Flows for Inactive Subscribers", "List Hygiene", "Re-engaging lapsed buyers and purging unengaged contacts to boost inbox rates.", ["Win-Back Discount Flow", "Subscriber Sunset Protocol"]),
            ("SMS Marketing Strategy: Compliance (TCPA/CTIA) and High-Urgency Flashes", "Mobile Messaging", "Executing legal, high-ROI SMS flash sales without subscriber fatigue.", ["TCPA Compliance", "SMS Flash Campaigns"]),
            ("Customer Lifetime Value (LTV) Cohort Analysis in CRM", "Retention Economics", "Calculating cumulative gross margin generated by customer cohorts over 12 months.", ["12-Month LTV Curves", "Cohort Payback Period"]),
            ("Churn Prevention and Net Promoter Score (NPS) Feedback Loops", "Customer Retention", "Triggering proactive customer success interventions when NPS scores drop.", ["NPS Feedback Loop", "Proactive Churn Defense"]),
            ("Conversion Rate Optimization (CRO): Heatmaps and Session Recordings", "UX Optimization", "Using Hotjar / Microsoft Clarity to identify user rage clicks and dead ends.", ["Rage Clicks", "Session Replay Analysis"]),
            ("Designing Clean A/B Landing Page Experiments with Statistical Rigor", "CRO Experimentation", "Formulating testable hypotheses and running tests to 95% confidence intervals.", ["A/B Testing Hypothesis", "95% Statistical Confidence"]),
            ("Phase 5 Placement Milestone: Full-Funnel Analytics Presentation", "Executive Analytics", "Presenting full-funnel GA4 drop-off and email lifecycle revenue to leadership.", ["Full-Funnel Observability", "Lifecycle Revenue Contribution"]),
        ]),

        # Phase 6: Days 76-89 (Performance Strategy, Attribution & Executive Defense)
        (76, 89, "Growth Strategy", [
            ("Marketing Mix Modeling (MMM) vs Multi-Touch Attribution (MTA)", "Advanced Attribution", "Combining top-down econometric MMM regression with bottom-up click tracking.", ["Econometric MMM", "MTA vs MMM Synergy"]),
            ("Incrementality Testing and Geo-Lift Experiments", "Causal Measurement", "Measuring true causal ad lift by blacking out marketing spend in matched cities.", ["Geo-Lift Experiment", "Causal Incrementality"]),
            ("Media Budget Allocation Across Paid Channels (70-20-10 Rule)", "Budget Strategy", "Balancing core scalable channels with high-potential emerging tests.", ["70-20-10 Portfolio", "Risk-Adjusted Media Budget"]),
            ("Calculating Blended MER and True Contribution Margin", "Unit Economics", "Measuring profitability by subtracting COGS, shipping, and ad spend from revenue.", ["Contribution Margin", "Blended Media Efficiency"]),
            ("Managing Ad Network Policy Violations and Account Suspensions", "Crisis Management", "Structuring professional compliance appeals for disapproved ads or disabled accounts.", ["Policy Violation Appeal", "Compliance Resolution"]),
            ("Black Friday / Cyber Monday (BFCM) Media Planning and Bidding Surges", "Seasonal Strategy", "Scaling ad spend 5x during peak Q4 shopping weeks while managing surging CPMs.", ["BFCM Surge Planning", "Pre-Holiday List Building"]),
            ("International Market Expansion for Direct-to-Consumer Brands", "Global Growth", "Adapting currency, localized landing pages, and international payment methods.", ["Cross-Border Commerce", "Localized Ad Creatives"]),
            ("B2B Account-Based Marketing (ABM) Paid Media Orchestration", "B2B Growth", "Targeting high-value corporate accounts with coordinated LinkedIn and display ads.", ["Account-Based Marketing", "Buying Committee Penetration"]),
            ("Affiliate & Influencer Commission Structures and Fraud Prevention", "Partnership Growth", "Setting tiered CPA commissions and blocking fraudulent coupon toolbar hijackers.", ["Affiliate Fraud Prevention", "Tiered Commission Structure"]),
            ("Building an In-House Creative Strategy & Media Buying Growth Engine", "Team Building", "Structuring agile sprint cadences between copywriters, video editors, and media buyers.", ["Growth Sprint Cadence", "Creative Feedback Loop"]),
            ("Presenting Marketing Performance Decks to Venture Capitalists and CEOs", "Executive Presence", "Translating media metrics into customer acquisition economics and enterprise value.", ["VC Growth Deck", "Enterprise Valuation Impact"]),
            ("Managing Client Churn and Scope Creep in a Digital Agency", "Agency Management", "Setting transparent SLA boundaries and retaining high-value client accounts.", ["Client Retention Strategy", "Scope Governance"]),
            ("Continuous Learning: Staying Ahead of AI Creative and Bidding Automation", "Future-Proofing", "Leveraging generative AI for rapid copy ideation and automated asset rendering.", ["AI Creative Automation", "Predictive Bidding Trends"]),
            ("Senior Growth Marketer Placement Interview: Live Whiteboard Strategy", "Interview Mastery", "Architecting a complete $1M/month omnichannel growth strategy in real-time.", ["Whiteboard Growth Architecture", "Omnichannel Mastery"]),
        ]),
    ]

    for p_start, p_end, p_phase, p_topics in phase_definitions:
        for idx, t in enumerate(p_topics):
            d_num = p_start + idx
            t_title, t_cat, t_desc, t_vocab = t
            rate_base = 1500 + (d_num * 75)
            delta_pct = 15 + (d_num % 20)
            result_val = int(rate_base * (1 + delta_pct / 100))

            days.append({
                "day": d_num,
                "commType": COMM_TYPES[d_num % len(COMM_TYPES)],
                "commTitle": t_title,
                "commScenario": f"During a digital campaign performance review for {t_title}, stakeholders request clarification on {t_desc}.",
                "commPrompt": f"Explain the critical marketing principles, optimization strategies, and business ROI trade-offs of {t_title} with clarity.",
                "commVocab": [t_vocab[0], t_vocab[1]],
                "commRule": "Executive Marketing Presence & ROI-Driven Precision",
                "commWeakResponse": f"We just setup {t_title} using default settings and hope that Facebook or Google optimizes it for us.",
                "commWeakCritique": "Passive, amateurish, and reveals a lack of analytical rigor and commercial accountability.",
                "commStrongResponse": f"In our performance marketing strategy, {t_title} is managed using {t_vocab[0]} and {t_vocab[1]} to guarantee efficient capital allocation, lower acquisition costs, and maximize contribution margin.",
                "commStrongCritique": "Structured, authoritative, and strictly connects tactical campaign knobs to executive financial results.",
                "commCoachTip": f"Always anchor your explanation in commercial ROI: explain how {t_vocab[0]} prevents wasted ad spend.",
                "aptTopic": APT_TOPICS[d_num % len(APT_TOPICS)],
                "aptTitle": f"{t_title} Performance Math",
                "aptQuestion": f"A paid advertising campaign generates {rate_base:,} conversion events per month. After implementing optimization protocols for {t_title}, conversion volume increases by {delta_pct}%. What is the new monthly conversion volume?",
                "aptOptions": [f"{result_val:,} conversions/mo", f"{result_val - 45:,} conversions/mo", f"{result_val + 60:,} conversions/mo", f"{result_val - 75:,} conversions/mo"],
                "aptAnswer": 0,
                "aptExplanation": f"Calculation: Increase = {rate_base} * {delta_pct/100:.2f} = {result_val - rate_base}. New volume = {rate_base} + {result_val - rate_base} = {result_val:,} conversions per month.",
                "aptFormula": "New Volume = Base Volume * (1 + Growth Rate)",
                "logicType": LOGIC_TYPES[d_num % len(LOGIC_TYPES)],
                "logicTitle": f"{t_title} Marketing Logic",
                "logicQuestion": f"When configuring {t_title}, which strategic optimization constraint must be enforced to ensure profitable scaling?",
                "logicOptions": [
                    f"Ensure {t_vocab[0]} is verified and aligned with target unit economics before scaling budget.",
                    f"Bypass {t_vocab[1]} completely and maximize daily spend regardless of acquisition costs.",
                    "Optimize exclusively for top-line vanity impressions while ignoring checkout conversions.",
                    "Pause all brand search campaigns without testing incremental lift."
                ],
                "logicAnswer": 0,
                "logicExplanation": f"Correct! In {t_title}, establishing that {t_vocab[0]} aligns with unit economics guarantees sustainable profitability and prevents capital burn during scaling.",
            })

    # Day 90: Final Placement Challenge
    days.append({
        "day": 90,
        "commType": "interview-question",
        "commTitle": "FINAL PLACEMENT CHALLENGE: Chief Growth Officer & Performance Lead Placement Defense",
        "commScenario": "You are presenting before the Executive Investment Board and Chief Executive Officer for a Head of Digital Marketing & Growth Lead position.",
        "commPrompt": "Deliver an end-to-end full-funnel digital growth architecture for a $20M omnichannel brand scaling to $50M: detailing paid media portfolio allocation (Google, Meta, TikTok), server-side tracking resilience (CAPI & GA4 BigQuery), creative testing velocity, and econometric Marketing Mix Modeling (MMM) that maximizes net contribution margin.",
        "commVocab": ["Full-Funnel Omnichannel Architecture", "Marketing Mix Modeling (MMM)", "Net Contribution Margin Scaling"],
        "commRule": "Boardroom Gravitas, Financial Unit Economics & Growth Leadership",
        "commWeakResponse": "We will run Google Search, Meta Ads, and TikTok ads, make lots of video creatives, track everything in GA4, and scale spend when ROAS looks good.",
        "commWeakCritique": "Lacks financial unit economics, fails to explain incrementality testing, and shows no understanding of capital efficiency.",
        "commStrongResponse": "Our growth scaling architecture treats marketing not as a cost center, but as a disciplined capital allocation portfolio. We allocate capital across a 70-20-10 framework: 70% in validated demand-capture engines (Google Search & Advantage+ Shopping), 20% in vertical video prospecting (TikTok & Meta Partnership Ads), and 10% in high-upside experimental channels. Tracking resilience is anchored in server-side CAPI and raw GA4 event streaming into BigQuery, insulating our signals from cookie decay. Crucially, we graduate beyond flawed platform-reported ROAS by deploying open-source Marketing Mix Modeling (Meta Robyn) combined with quarterly geo-lift incrementality experiments. This guarantees every incremental ad dollar directly drives net contribution margin and sustainable enterprise value.",
        "commStrongCritique": "An absolute masterclass in growth leadership: bridges board-level capital allocation, technical data engineering, creative agility, and econometric incrementality.",
        "commCoachTip": "In the final placement challenge, demonstrate complete command over unit economics, econometric incrementality, and full-funnel media orchestration.",
        "aptTopic": "Data Interpretation & Metrics",
        "aptTitle": "Final Assessment: Enterprise Omnichannel Media Budget Financial Sizing",
        "aptQuestion": "An e-commerce brand operates with an annual paid media budget of $2,400,000. Under a performance scaling model, the brand targets an overall Blended ROAS of 350% (3.5x). If product gross profit margin is 40.0%, what is the net contribution profit generated after deducting both product costs and total advertising spend?",
        "aptOptions": ["$960,000 net profit", "$840,000 net profit", "$1,080,000 net profit", "$720,000 net profit"],
        "aptAnswer": 0,
        "aptExplanation": "Calculation: Total generated revenue = Budget ($2,400,000) * ROAS (3.5) = $8,400,000. Gross profit before ad spend = $8,400,000 * 0.40 (gross margin) = $3,360,000. Net contribution profit after ad spend = Gross Profit ($3,360,000) - Ad Spend ($2,400,000) = $960,000 net profit.",
        "aptFormula": "Contribution Profit = (Total Revenue * Gross Margin %) - Total Ad Spend",
        "logicType": "Decision Architecture",
        "logicTitle": "Final Assessment: End-to-End Growth System Incrementality Logic",
        "logicQuestion": "A high-growth direct-to-consumer brand spends $300,000/month on Meta ads. Meta reports a 3.8x in-platform ROAS, but an executive geo-lift blackout experiment across 5 test markets reveals that turning off Meta ads resulted in ZERO drop in actual total company revenue over 4 weeks. What does this prove, and what is the mandatory immediate strategic action?",
        "logicOptions": [
            "Meta ads were generating zero incremental lift (capturing organic baseline demand without causation); immediately halt or reallocate budget to truly incremental channels and restructure creative targeting.",
            "Increase Meta budget by 200% because the platform reports a 3.8x ROAS.",
            "Fire the analytics team and delete the geo-lift test data.",
            "Switch the attribution window from 7-day click to 28-day view-through."
        ],
        "logicAnswer": 0,
        "logicExplanation": "Correct! When a rigorous geo-lift test shows zero revenue decline when ads are switched off, the ad spend is 100% non-incremental (claiming organic buyers who would have converted anyway). True growth requires reallocating capital to incremental demand-generating channels.",
    })

    return days

print("marketing_data module ready.")
