# scripts/generators/medical_data.py
"""
90 Days of Course-Specific Placement Accelerator Content for Medical Coding (track: medical)
Phases:
1. Days 1-15: Medical Terminology, Anatomy & Physiology, HIPAA & Compliance, Overview of ICD-10-CM, CPT & HCPCS
2. Days 16-30: ICD-10-CM Coding Conventions, Chapter-Specific Guidelines (Infections, Neoplasms, Endocrine, Cardiology)
3. Days 31-45: CPT Coding Fundamentals, Evaluation & Management (E/M) MDM Guidelines, Surgery, Radiology & Lab
4. Days 46-60: HCPCS Level II, Modifiers (-25, -59, -50), NCCI Edits, Bundling & Fraud/Abuse Prevention
5. Days 61-75: Revenue Cycle Management (RCM), CMS-1500 & UB-04 Claims, Clearinghouse Edits, Denials & Appeals
6. Days 76-89: Clinical Documentation Improvement (CDI), Physician Queries, Risk Adjustment (HCC Coding) & Audits
Day 90: Final Placement Challenge
"""

COMM_TYPES = [
    "interview-question", "technical-explanation", "client-conversation",
    "team-communication", "workplace-scenario", "problem-explanation",
    "project-explanation", "technical-presentation", "email-response",
    "manager-conversation", "hr-question", "conflict-resolution",
    "requirement-clarification", "technical-to-nontechnical",
]

APT_TOPICS = [
    "Percentages & Growth", "Ratios & Proportions", "Averages & Distributions",
    "Profit, Margin & ROI", "Time, Work & Capacity", "Speed, Latency & Distance",
    "Probability & Reliability", "Combinatorics & Permutations", "Number Systems & Units",
    "Data Interpretation & Metrics", "Statistics & Dispersion", "Financial & Business Math",
]

LOGIC_TYPES = [
    "Sequence Reasoning", "Workflow Ordering", "Deductive Analysis",
    "Constraint Solving", "Debugging Logic", "Process Flow",
    "Cause & Effect", "Decision Architecture",
]

def get_medical_days():
    days = []

    # 15 Detailed Foundations Days
    foundations = [
        (1, "technical-to-nontechnical", "Explaining ICD-10 vs CPT to a Healthcare Administrator",
         "A new clinic administrator asks why a patient encounter requires both an ICD-10-CM code and a CPT code on the billing claim.",
         "Explain the fundamental difference between diagnosis coding (medical necessity/why) and procedure coding (services rendered/what) with business clarity.",
         ["ICD-10-CM (Medical Necessity)", "CPT (Current Procedural Terminology)", "CMS-1500 Reimbursement"],
         "The Medical Necessity Principle (Connect clinical justification to procedural reimbursement)",
         "ICD-10 is the diagnosis and CPT is the procedure. Insurance needs both or they reject the claim.",
         "Too brief and lacks administrative value. Fails to explain the concept of medical necessity and audit vulnerability.",
         "Think of a healthcare claim as a clinical narrative: ICD-10-CM codes describe *why* the patient sought care (the diagnosis or medical condition), while CPT codes describe *what* services, exams, or surgical procedures the provider performed. Payers require both because reimbursement hinges on Medical Necessity: the CPT procedure must be clinically justified by an approved ICD-10 diagnosis. Submitting a CPT code without a matching, compliant ICD-10 code triggers immediate clearinghouse rejection and delays provider cash flow.",
         "Clear, professional, and frames medical necessity as the financial and clinical bridge for payer reimbursement.",
         "Always explain: ICD-10 is the 'why' (medical necessity) and CPT is the 'what' (service performed).",
         "Percentages & Growth", "Clinical Coding Accuracy Rate Calculation",
         "An internal medical coding quality audit evaluates 250 outpatient encounter charts coded by a team. The auditor finds that 235 charts were coded completely accurately with zero modifier or sequencing errors. What is the team's coding accuracy rate percentage?",
         ["94.0%", "92.5%", "95.0%", "96.0%"], 0,
         "Calculation: Accuracy Rate = (235 / 250) * 100% = 0.94 * 100% = 94.0%.",
         "Accuracy (%) = (Accurate Records / Total Audited) * 100",
         "Workflow Ordering", "Standard Healthcare Revenue Cycle Coding Sequence",
         "Which sequence accurately represents the correct chronological workflow of a patient encounter in the medical coding and billing lifecycle?",
         ["Patient Registration & Insurance Verification -> Clinical Encounter & Documentation -> Charge Capture & Medical Coding -> Claim Scrubbing & Submission -> Payer Adjudication & Payment Posting",
          "Claim Scrubbing -> Clinical Encounter -> Patient Registration -> Payer Adjudication -> Charge Capture",
          "Charge Capture -> Payer Adjudication -> Patient Registration -> Medical Coding -> Claim Submission",
          "Clinical Encounter -> Claim Submission -> Patient Registration -> Medical Coding -> Payer Adjudication"], 0,
         "The revenue cycle workflow begins with demographic/insurance registration, followed by clinical care/documentation, code assignment by certified coders, clearinghouse claim scrubbing, and final payer adjudication."),

        (2, "interview-question", "Explaining HIPAA Compliance and Minimum Necessary Standard",
         "An interviewer for a hospital coding specialist role asks: 'How do you apply the HIPAA Minimum Necessary rule when communicating documentation questions to external billing vendors?'",
         "Articulate HIPAA Privacy Rule protections, the Minimum Necessary standard, and protocols for transmitting Protected Health Information (PHI).",
         ["HIPAA Privacy Rule", "Protected Health Information (PHI)", "Minimum Necessary Standard"],
         "Compliance Integrity (Protect patient confidentiality while maintaining operational coordination)",
         "I just follow HIPAA and don't share patient records with anyone who doesn't work in the hospital.",
         "Overly broad and vague. Fails to define the Minimum Necessary standard or explain business associate protocols.",
         "Under HIPAA Privacy regulations, certified coders must strictly uphold the 'Minimum Necessary' standard. When querying external billing vendors or clearinghouses, we only disclose the specific data elements required to resolve the claim inquiry—such as encounter dates and relevant diagnosis codes—while withholding non-pertinent patient identifiers like Social Security numbers or full medical histories. Furthermore, all electronic transmissions must occur over encrypted, secure Business Associate Agreement (BAA)-compliant channels with strict audit logging.",
         "Demonstrates rigorous compliance knowledge, references BAAs, and highlights exact privacy safeguards.",
         "Whenever HIPAA is discussed, highlight the 'Minimum Necessary' standard and encrypted transmission protocols.",
         "Ratios & Proportions", "Coder Chart Review Productivity Ratio",
         "A medical coding supervisor establishes that an experienced outpatient coder should process charts at a ratio of 5 outpatient clinic charts per hour. How many completed charts are expected from a coder during an 8-hour shift with a 1-hour dedicated meeting/break allowance (7 productive hours)?",
         ["35 charts", "40 charts", "30 charts", "45 charts"], 0,
         "Calculation: Productive hours = 8 - 1 = 7 hours. Total charts = 7 hours * 5 charts/hour = 35 charts.",
         "Total Charts = Productive Hours * Productivity Rate",
         "Deductive Analysis", "Identifying Coding Fraud vs Unintentional Abuse",
         "A provider repeatedly bills CPT 99215 (Level 5 highest-complexity outpatient visit) for brief 10-minute follow-ups for common colds, despite documented warnings from the compliance officer. Under Federal healthcare guidelines, how is this categorized?",
         ["Fraud: Knowingly submitting false claims for higher reimbursement (upcoding) with deliberate disregard or reckless ignorance.",
          "Unintentional Error: Standard clerical coding variance common in high-volume practices.",
          "Appropriate Practice: Providers have total subjective discretion over visit level coding regardless of documentation.",
          "Payer Glitch: An automated software error caused by clearinghouse translation."], 0,
         "Upcoding knowingly or with reckless disregard after compliance warnings violates the False Claims Act and constitutes healthcare fraud, distinguishing it from accidental clerical errors."),

        (3, "team-communication", "Issuing a Compliant Physician Query Regarding Incomplete Documentation",
         "A physician documents 'patient has elevated troponin and chest pain, treated with aspirin and nitrates,' but does not document a definitive diagnosis of myocardial infarction or angina.",
         "Draft a non-leading, compliant physician query adhering to AHIMA/ACDIS guidelines to clarify the clinical diagnosis without leading the provider.",
         ["AHIMA/ACDIS Query Standards", "Non-Leading Physician Query", "Clinical Documentation Improvement (CDI)"],
         "Non-Leading Query Ethics (Present documented clinical indicators and offer multiple diagnostic choices including 'other' and 'unable to determine')",
         "Doctor, you wrote elevated troponin and nitrates. Can you please add Acute Myocardial Infarction so we can code it properly?",
         "Severe compliance violation: this is a leading query that coaches the physician to document a specific high-reimbursement code.",
         "Dear Dr. Smith, regarding patient encounter #48291: Clinical documentation indicates an elevated troponin of 1.4 ng/mL, ischemic ECG changes, and patient administration of sublingual nitroglycerin and aspirin. Based on these documented clinical indicators, please clarify the definitive diagnosis if clinically feasible: [ ] Acute Myocardial Infarction (specify STEMI or NSTEMI), [ ] Unstable Angina, [ ] Demand Ischemia secondary to tachycardia, [ ] Other condition (please specify), [ ] Unable to determine clinically. Thank you for your collaboration.",
         "Compliant AHIMA-certified query format: provides clinical indicators, offers multiple balanced options, and avoids leading language.",
         "Never tell a doctor what to document. Present clinical evidence and provide multiple options including 'other' and 'unable to determine'.",
         "Time, Work & Capacity", "Medical Coding Department Backlog Clearance",
         "A hospital coding department has a backlog of 720 unbilled surgical inpatient charts. A team of 4 full-time inpatient coders can each review and code 6 inpatient charts per day. How many business days will it take the team to completely clear the backlog?",
         ["30 days", "25 days", "35 days", "40 days"], 0,
         "Calculation: Daily team capacity = 4 coders * 6 charts/day = 24 charts/day. Days required = 720 / 24 = 30 business days.",
         "Days to Clear = Backlog Volume / (Coders * Daily Rate)",
         "Debugging Logic", "Resolving Unspecified Diagnosis Code Denials",
         "A claim for outpatient physical therapy is denied by Medicare with remark code 'Diagnosis code lacks specificity'. The claim was submitted with ICD-10 code M54.5 (Low back pain, unspecified). What is the appropriate resolution?",
         ["Review the clinical documentation for anatomical detail (e.g., lumbar strain, lumbago with sciatica, site laterality) and update to a specific ICD-10 code supported by the medical record.",
          "Resubmit the exact same claim with a modifier -59 added to the therapy code.",
          "Arbitrarily change the diagnosis code to fracture without reviewing the clinical chart.",
          "Write off the balance immediately as uncollectible bad debt."], 0,
         "Medicare and commercial payers increasingly deny unspecified codes when specific codes exist. The coder must review the chart for documented clinical specificity (laterality, etiology) and bill the substantiated specific code."),

        (4, "client-conversation", "Explaining an Out-of-Pocket Insurance Denial to a Patient",
         "A patient calls billing upset because their insurer denied coverage for a diagnostic routine screening colonoscopy, leaving them with an unexpected $1,800 bill.",
         "Explain how screening codes (Z12.11) differ from diagnostic/therapeutic codes when a polyp is removed, and navigate patient advocacy resources with empathy.",
         ["Screening vs Diagnostic Colonoscopy", "Preventive Care Mandate (ACA)", "PT Modifier / Cost-Sharing"],
         "Compassionate Advocacy (De-escalate emotional distress while investigating clinical coding remedies)",
         "Your insurance didn't pay because the doctor found a polyp, so it's not preventive anymore. You have to pay the $1,800.",
         "Cold, unsympathetic, and overlooks crucial billing regulations like Modifier PT or 33 which protect preventive screening status.",
         "I completely understand how stressful an unexpected bill is, especially when you scheduled this as a routine preventive screening. Under the Affordable Care Act, screening colonoscopies are covered at 100%. However, when the gastroenterologist identified and removed a polyp during the procedure, the claim transitioned from purely screening to diagnostic. In these situations, Medicare and many commercial payers require Modifier PT or 33 to signal that the procedure originated as a preventive screening, which waives or reduces your deductible. I will place a temporary hold on your account while our coding team reviews the chart to ensure the preventive modifier was properly applied.",
         "Empathetic, highly knowledgeable regarding healthcare payer mandates (Modifier PT/33), and offers immediate operational relief.",
         "When patients receive surprise bills for screening procedures, always check whether preventive modifiers (Modifier PT or 33) were omitted.",
         "Financial & Business Math", "Provider Clean Claim Reimbursement Calculation",
         "A medical clinic bills $8,400 in gross charges for 60 patient office visits. The contractual commercial payer fee schedule allows an average reimbursement of $95.00 per visit, with a patient copay responsibility of $20.00 per visit. How much will the insurance payer directly reimburse the clinic across these 60 visits?",
         ["$4,500.00", "$5,700.00", "$4,800.00", "$3,900.00"], 0,
         "Calculation: Allowed amount per visit = $95.00. Payer responsibility = Allowed ($95) - Copay ($20) = $75.00 per visit. Total payer reimbursement = 60 visits * $75.00 = $4,500.00.",
         "Payer Payment = Visits * (Contractual Allowed Amount - Patient Copay)",
         "Cause & Effect", "Impact of Missing Seventh Character in ICD-10-CM Injury Coding",
         "An orthopedic claim lists an initial encounter fracture code as S52.501 (Fracture of lower end of right radius), omitting the 7th character extension 'A'. What will occur during clearinghouse adjudication?",
         ["The clearinghouse or payer will immediately reject the claim as an invalid code, because ICD-10 requires all applicable characters up to 7 characters for traumatic injury categories.",
          "The payer will automatically append the letter 'A' and process the claim without delay.",
          "The claim will convert into a CPT code automatically.",
          "The claim will pay at a 50% penalty rate."], 0,
         "In ICD-10-CM, categories that require a 7th character (such as fractures indicating encounter type: A=initial, D=subsequent, S=sequela) are invalid without that extension, causing automated clearinghouse rejection."),

        (5, "problem-explanation", "Explaining Evaluation and Management (E/M) Guidelines 2021/2023 Update",
         "A medical group director asks why their clinical providers are no longer required to document comprehensive 10-system Review of Systems (ROS) for outpatient office visit codes.",
         "Explain the AMA/CMS 2021/2023 E/M landmark changes: eliminating history/exam as code-level determinants and focusing strictly on Medical Decision Making (MDM) or Total Time.",
         ["E/M 2021/2023 Guidelines", "Medical Decision Making (MDM)", "Reduction of Documentation Burden"],
         "Regulatory Evolution (Explain how regulatory updates streamline clinical workflow while maintaining audit rigor)",
         "The rules changed so doctors don't have to write long notes anymore. They can just pick whatever code they want based on time.",
         "Inaccurate and risky. Fails to explain the structured 3-element MDM framework that replaces the old 1995/1997 guidelines.",
         "Under the AMA and CMS 2021 outpatient and 2023 inpatient E/M revisions, the documentation burden was significantly modernized to combat physician burnout. Historically under the 1995/1997 rules, codes were driven by counting bullet points in History and Physical Exam. Today, history and exam are performed as clinically appropriate, but code selection is determined strictly by either Medical Decision Making (MDM) or Total Time on the date of encounter. MDM evaluates three elements: the number/complexity of problems addressed, the amount/complexity of data reviewed, and the risk of complications or morbidity.",
         "Superb explanation: explains historical context, cites the exact three MDM elements, and clarifies compliance boundaries.",
         "Remember the E/M 2021/2023 transformation: code selection is driven strictly by Medical Decision Making (MDM) or Total Time.",
         "Percentages & Growth", "Denial Rate Reduction Impact on Cash Flow",
         "A specialty clinic submits $400,000 in monthly claims. Initially, their claim denial rate is 8.0%. After implementing automated front-end scrubbing and coder chart audits, the denial rate drops to 3.5%. How much monthly claim value was prevented from initial denial?",
         ["$18,000 / month", "$14,000 / month", "$20,000 / month", "$16,000 / month"], 0,
         "Calculation: Denial rate reduction = 8.0% - 3.5% = 4.5%. Preserved clean claim volume = $400,000 * 0.045 = $18,000 per month.",
         "Saved Claim Dollars = Total Billed * (Initial Denial Rate - New Denial Rate)",
         "Decision Architecture", "E/M Medical Decision Making (MDM) Level Selection",
         "A physician sees an established patient with 2 stable chronic illnesses (hypertension and well-controlled type 2 diabetes), reviews lab results from an external lab, and renews prescription medications. According to AMA MDM guidelines, what is the appropriate E/M level?",
         ["CPT 99214 (Level 4 - Moderate Medical Decision Making)",
          "CPT 99212 (Level 2 - Straightforward Decision Making)",
          "CPT 99215 (Level 5 - High Complexity Decision Making)",
          "CPT 99211 (Level 1 - Minimal Clinical Service)"], 0,
         "Two stable chronic conditions = Moderate problems; prescription drug management = Moderate risk. Meeting 2 of 3 MDM categories at Moderate complexity satisfies CPT 99214."),

        (6, "interview-question", "Demonstrating Proper Use of Modifier -25 in an Audit Interview",
         "The interviewer asks: 'When is it legally and clinically appropriate to append Modifier -25 to an Evaluation and Management (E/M) service?'",
         "Explain Modifier -25 guidelines: significant, separately identifiable E/M service by the same physician on the same day as a minor surgical procedure.",
         ["Modifier -25", "Significant, Separately Identifiable E/M", "Minor Procedure (0- or 10-day global)"],
         "Audit Defense Precision (Articulate documentation independence so the E/M stands alone under audit)",
         "You put Modifier -25 on an office visit whenever the doctor also does a procedure like a wart removal or joint injection on the same day.",
         "Incorrectly assumes Modifier -25 is automatic. Billing it without an independent, medically necessary workup constitutes fraud.",
         "Modifier -25 may only be appended to an E/M service code when clinical documentation proves a 'significant, separately identifiable' evaluation beyond the typical pre- and post-procedural care of the minor procedure performed on the same day. For example, if a patient presents for chronic COPD management and during the visit the provider notices and excises a suspicious lesion, Modifier -25 is appropriate on the E/M because the COPD evaluation is clinically distinct. Under payer audit, if the E/M documentation is excised from the chart, the procedure note must stand completely on its own, and vice-versa.",
         "Authoritative audit defense: explains the 'stand-alone' clinical documentation test and prevents improper unbundling.",
         "Modifier -25 rule: The E/M service must be significant and separately identifiable. Always verify the chart passes the stand-alone test.",
         "Data Interpretation & Metrics", "Medicare Relative Value Unit (RVU) Payment Calculation",
         "A cardiologist performs a diagnostic procedure with a Total Relative Value Unit (RVU) of 4.50. The current Medicare Conversion Factor is $32.75 per RVU. Geographic Practice Cost Index (GPCI) is normalized to 1.0. What is the allowable Medicare reimbursement for this service?",
         ["$147.38", "$135.50", "$152.20", "$142.10"], 0,
         "Calculation: Allowed Reimbursement = Total RVU * Conversion Factor = 4.50 * $32.75 = $147.375, which rounds to $147.38.",
         "Reimbursement = RVU * Conversion Factor",
         "Constraint Solving", "NCCI Edits and Modifier -59 Unbundling Rules",
         "A surgeon performs two distinct surgical procedures during the same operating session. The National Correct Coding Initiative (NCCI) lists Procedure B as bundled into Procedure A with an edit modifier indicator of '0'. Can the coder append Modifier -59 to unbundle Procedure B?",
         ["No: An NCCI modifier indicator of '0' signifies that no modifier is allowed under any circumstance, and the codes may never be billed together.",
          "Yes: Modifier -59 can always be used to override any NCCI bundling edit.",
          "Yes: As long as the surgeon submits a written appeal letter to Medicare.",
          "No: But the coder can bill Procedure B under an unlisted code instead."], 0,
         "In NCCI PTP edits: Indicator '0' means no modifier allowed (never unbundle); Indicator '1' allows appropriate modifiers (-59, -X{EPSU}) if clinically distinct; Indicator '9' means deleted/exempt."),

        (7, "workplace-scenario", "Resolving an Unbundling Disagreement with a Billing Specialist",
         "A billing specialist wants to unbundle a comprehensive metabolic panel (CPT 80053) into 14 individual electrolyte and liver enzyme tests to increase total billed charges.",
         "Explain CPT bundling rules, NCCI guidelines, and the severe False Claims Act liabilities associated with unbundling fragmentation.",
         ["Unbundling / Fragmentation", "Organ or Disease-Oriented Panels", "False Claims Act Liability"],
         "Ethical Compliance Courage (Stand firm on coding ethics to shield the organization from federal sanctions)",
         "We can't do that because my supervisor said panel tests shouldn't be split up.",
         "Weak and deferential. Fails to cite official CPT coding conventions and federal regulatory statutes.",
         "I understand the motivation to optimize revenue, but unbundling an organ-disease panel like CPT 80053 into individual component tests is explicitly prohibited under CPT guidelines and NCCI rules. When all tests in a defined panel are performed from the same blood draw, billing them separately constitutes 'fragmentation'—an illegal practice under the federal False Claims Act. If audited by CMS or the OIG, the clinic would face mandatory recoupment, treble damages ($11,000+ per false claim), and potential exclusion from federal healthcare programs. We must bill the bundled panel 80053.",
         "Flawless demonstration of coding compliance: explains the clinical panel definition and cites federal OIG legal consequences.",
         "Never unbundle panel codes: when all components of a panel are performed, billing individual tests is illegal fragmentation.",
         "Averages & Distributions", "Average Days in Accounts Receivable (A/R) Metric",
         "A healthcare organization has a total current Accounts Receivable balance of $1,800,000 and calculates its average daily gross revenue at $45,000 per day. What is the organization's Days in A/R?",
         ["40 days", "35 days", "45 days", "50 days"], 0,
         "Calculation: Days in A/R = Total Current A/R / Average Daily Revenue = $1,800,000 / $45,000 = 40 days.",
         "Days in A/R = Accounts Receivable Balance / Average Daily Revenue",
         "Workflow Ordering", "Appealing a Denied Medical Necessity Claim Sequence",
         "What is the correct sequential procedure for appealing an outpatient insurance claim denied for 'lack of medical necessity'?",
         ["Review Remittance Advice & Denial Reason -> Examine Medical Record for Supporting Documentation -> Obtain Attending Physician Letter of Medical Necessity -> Submit First-Level Appeal with Chart Records -> Track Appeal Status",
          "Submit Appeal without Records -> Review Denial -> Contact Patient for Payment -> Write Off Balance",
          "Write Off Balance -> Contact Physician -> Resubmit Identical Claim -> Check Denial Code",
          "File Lawsuit with Insurance Commissioner -> Submit Claim Records -> Review Denial"], 0,
         "A successful medical necessity appeal requires reviewing the remittance advice reason code, extracting documented clinical rationale, securing provider clinical justification, and submitting formal records within timely filing limits."),

        (8, "technical-presentation", "Presenting Hierarchical Condition Categories (HCC) to Medical Staff",
         "Presenting the importance of accurate chronic disease documentation to primary care physicians in a Medicare Advantage value-based contract.",
         "Explain how chronic condition documentation directly affects patient Risk Adjustment Factor (RAF) scores, healthcare resource allocation, and annual funding.",
         ["Risk Adjustment Factor (RAF)", "HCC Coding", "MEAT Criteria (Monitor, Evaluate, Assess, Treat)"],
         "Value-Based Transformation (Show clinicians how documentation accuracy impacts patient care funding)",
         "Doctors need to write down every diagnosis every year so the clinic gets more risk adjustment money from Medicare.",
         "Focuses crudely on revenue rather than accurate patient disease burden and value-based care management.",
         "In Medicare Advantage value-based care, funding is determined by patient Risk Adjustment Factor (RAF) scores calculated from Hierarchical Condition Categories (HCCs). If an elderly patient with diabetic nephropathy is simply documented as 'diabetes on insulin', their true disease burden is severely under-represented, leaving our care teams without the budgeted resources required for intensive disease management. Under CMS rules, chronic conditions reset every calendar year and must be documented using the MEAT criteria: Monitor, Evaluate, Assess, or Treat. Accurate, specific coding ensures our patient illness severity is faithfully reflected.",
         "Inspiring, clinically respectful presentation: highlights patient care funding and teaches the memorable MEAT documentation rule.",
         "For HCC risk adjustment, emphasize the annual reset and the MEAT criteria: Monitor, Evaluate, Assess, or Treat.",
         "Percentages & Growth", "HCC Risk Adjustment Score Weight Calculation",
         "A Medicare Advantage patient has a baseline demographic risk score of 0.350. During the annual wellness exam, the coder captures documentation satisfying HCC 19 (Diabetes with Chronic Complications, weight 0.368) and HCC 85 (Congestive Heart Failure, weight 0.323). What is the patient's new total Risk Adjustment Factor (RAF) score?",
         ["1.041", "0.985", "1.120", "1.015"], 0,
         "Calculation: Total RAF Score = Demographic (0.350) + HCC 19 (0.368) + HCC 85 (0.323) = 1.041.",
         "Total RAF = Demographic Factor + Sum of Documented HCC Weights",
         "Process Flow", "MEAT Documentation Requirement Validation",
         "A physician lists 'Stage 3 Chronic Kidney Disease' in the patient's past medical history problem list, but makes no mention of eGFR monitoring, nephrology evaluation, dietary assessment, or medication adjustment anywhere in the encounter progress note. Can this condition be coded for HCC risk adjustment?",
         ["No: Merely listing a condition in the past history without documented Monitoring, Evaluation, Assessment, or Treatment (MEAT) fails CMS validation standards.",
          "Yes: Any condition listed anywhere in the electronic medical record problem list may be coded annually.",
          "Yes: Past medical history is considered active care by all Medicare payers.",
          "No: Chronic kidney disease is never eligible for risk adjustment."], 0,
         "Under CMS Risk Adjustment Data Validation (RADV) rules, conditions listed solely in historical problem lists without documented current MEAT are disallowed during audits."),

        (9, "manager-conversation", "Addressing High Coding Backlog Due to Complex EHR Migration",
         "Meeting with the Chief Financial Officer (CFO) to report that hospital Discharged Not Final Billed (DNFB) dollars increased by 40% following a switch to a new EHR system.",
         "Communicate the root cause of the billing slowdown, articulate coder learning curve factors, and present a structured recovery roadmap.",
         ["Discharged Not Final Billed (DNFB)", "EHR Transition Learning Curve", "Interim Contract Coding Support"],
         "Executive Problem-Solving (Acknowledge financial risk, explain technical bottlenecks, and present a budgeted mitigation plan)",
         "The new EHR software is terrible and slow. Coders can't find templates, so don't blame the coding department for unbilled revenue.",
         "Defensive, unprofessional, and fails to offer the CFO a concrete strategy to recover billing cash flow.",
         "I want to transparently address the 40% increase in our DNFB balance following our EHR migration. The surge is driven by three temporary bottlenecks: new charge router interface errors, unfamiliar clinical documentation layout for our coders, and missing automated CPT crosswalks. To accelerate recovery, our department has instituted daily 30-minute EHR super-user huddles and standardized template hotkeys. Furthermore, I propose bringing on two certified interim remote contract coders for 3 weeks to clear the surgical backlog. This will stabilize our DNFB down to our target 3.2 days and normalize cash flow within 30 days.",
         "Exemplary managerial communication: breaks down root causes, outlines immediate internal remediation, and proposes an actionable interim staffing solution.",
         "When reporting operational backlogs to executive leadership, pair problem diagnosis with an immediate, budgeted remediation timeline.",
         "Financial & Business Math", "Discharged Not Final Billed (DNFB) Financial Sizing",
         "A hospital averages $1,200,000 in gross daily discharges. Following an electronic health record upgrade, the Discharged Not Final Billed (DNFB) window extends from an average of 4.0 days to 7.5 days. What is the total dollar volume of revenue temporarily held in unbilled DNFB status under this new delay?",
         ["$9,000,000", "$8,400,000", "$9,600,000", "$7,800,000"], 0,
         "Calculation: Total DNFB Dollar Volume = Average Daily Gross Revenue * Average DNFB Days = $1,200,000 * 7.5 days = $9,000,000.",
         "Total DNFB = Daily Discharge Revenue * DNFB Days",
         "Debugging Logic", "Resolving Claim Scrubber Edits for Mutually Exclusive Code Pairs",
         "A claim scrubber rejects a claim because CPT 49505 (Inguinal hernia repair) and CPT 49520 (Recurrent inguinal hernia repair) were both billed on the same anatomical site during the same operation. What is the coding logic error?",
         ["Mutually Exclusive: A hernia repair cannot be simultaneously initial and recurrent on the same exact anatomical hernia defect.",
          "Missing Modifier: The coder forgot to append Modifier -50 for bilateral repair.",
          "Diagnosis Mismatch: The diagnosis code was for femoral hernia rather than inguinal hernia.",
          "Payer Restriction: Hernia repairs can only be billed by two different operating surgeons."], 0,
         "An initial hernia repair and a recurrent hernia repair at the exact same anatomical site are clinically mutually exclusive; a defect is either an initial presentation or a recurrence, but cannot be both."),

        (10, "email-response", "Responding to a Provider Inquiry on Denied Surgical Modifiers",
         "An orthopedic surgeon emails demanding to know why their bill for a left knee arthroscopy was denied when they performed both a meniscectomy and an extensive chondroplasty in the same knee compartment.",
         "Draft an email explaining CMS NCCI bundling guidelines regarding knee arthroscopy compartment rules, maintaining professional collegiality.",
         ["Knee Arthroscopy Compartments", "NCCI Column 1 / Column 2 Edits", "Surgeon Education"],
         "Professional Clinical Education (Ground explanations in published medical society and CMS standards)",
         "Doctor, Medicare doesn't let us bill chondroplasty and meniscectomy together in the same knee. We had to remove the chondroplasty code.",
         "Blunt and lacks clinical detail regarding anatomical compartments, making the surgeon feel their work is being arbitrarily dismissed.",
         "Dear Dr. Harrison,\n\nThank you for reaching out regarding the billing for encounter #93821 (Left knee arthroscopy). Under CMS National Correct Coding Initiative (NCCI) policy and AAOS guidelines, chondroplasty (CPT 29877) is bundled into a meniscectomy (CPT 29881) when performed in the same anatomical compartment (the medial compartment). Payers consider debridement in the operative field as inherent to the primary procedure.\n\nHowever, if significant chondroplasty was performed in a *separate, distinct* compartment of the knee (such as the patellofemoral or lateral compartment), CPT guidelines permit reporting HCPCS code G0289 for the separate compartment service. If your operative findings substantiate work in a separate compartment, please update the operative report to specify the distinct anatomical location, and we will gladly resubmit the claim with appropriate documentation.\n\nSincerely,\nHospital Surgical Coding Team",
         "Outstanding tone: respects the surgeon's clinical skill, cites official CMS/AAOS rules, and provides a clear, compliant pathway forward (separate compartment G-code).",
         "When explaining surgical bundling to doctors, cite anatomical compartments and specific medical society (AAOS/AMA) guidelines.",
         "Profit, Margin & ROI", "Clean Claim Rate Impact on Billing Administrative Costs",
         "A medical billing department processes 5,000 claims per month. The administrative cost to rework, appeal, and resubmit a denied claim averages $25.00. By boosting the Clean Claim Rate from 88% to 96%, how much administrative rework cost is saved each month?",
         ["$10,000 / month", "$8,500 / month", "$12,000 / month", "$7,500 / month"], 0,
         "Calculation: Claims denied initially at 88% clean rate = 5,000 * 0.12 = 600 claims. Denied at 96% clean rate = 5,000 * 0.04 = 200 claims. Denied claims prevented = 600 - 200 = 400 claims. Cost saved = 400 * $25.00 = $10,000 per month.",
         "Monthly Savings = Prevented Rework Claims * Cost per Rework",
         "Workflow Ordering", "Surgical Coding Operative Report Review Sequence",
         "What is the recommended analytical sequence for abstracting codes from a complex operative report?",
         ["Review Postoperative Diagnosis -> Read Operative Technique Narrative -> Identify Main Procedures & Anatomical Sites -> Check NCCI Bundling & Modifiers -> Verify Pathology Report Confirmation",
          "Read Header Only -> Pick First CPT in Alphabetical Index -> Submit Claim -> Read Narrative if Denied",
          "Review Pathology Report -> Submit Claim -> Read Postoperative Diagnosis -> Check Modifiers",
          "Check Modifiers -> Pick CPT Code -> Read Narrative -> Ignore Postoperative Diagnosis"], 0,
         "Accurate surgical coding requires reviewing the operative narrative in full (not just the header title), verifying anatomical approaches and findings, verifying NCCI bundling edits, and cross-referencing final pathology tissue confirmations."),

        (11, "conflict-resolution", "Mediation Between Clinical Documentation Specialist and Floor Coder",
         "A CDI specialist and a senior inpatient coder dispute whether a patient's acute respiratory failure can be sequenced as the principal diagnosis over pneumonia.",
         "Resolve the coding discrepancy using official ICD-10-CM Official Guidelines for Coding and Reporting (Section II Selection of Principal Diagnosis).",
         ["ICD-10-CM Section II (Principal Diagnosis)", "Two or More Comparative Conditions", "Acute Respiratory Failure Sequencing"],
         "Authoritative Adjudication (Base decisions strictly on published Official Coding Guidelines)",
         "Let's just code acute respiratory failure because it pays a higher DRG and nobody will notice.",
         "Serious compliance violation: sequencing solely to maximize reimbursement (DRG creep) violates federal coding ethics.",
         "Let's consult ICD-10-CM Official Guidelines for Coding and Reporting, Section II.C: 'Two or more comparative or contrasting conditions'. When a patient presents with both acute respiratory failure and severe pneumonia, and both conditions equally meet the definition of principal diagnosis—namely, the condition established after study to be chiefly responsible for occasioning the admission—either condition may be sequenced first, unless the alphabetic index or tabular list directs otherwise. Because the clinical documentation confirms that intensive ICU ventilatory support was initiated immediately for respiratory arrest, acute respiratory failure is clinically substantiated as chiefly responsible for admission and may be compliant sequenced as principal.",
         "Diplomatic and grounded in official ICD-10-CM Section II guidelines, balancing clinical acuity with ethical compliance.",
         "Always resolve sequencing disputes using the Official Guidelines for Coding and Reporting (Section II: Principal Diagnosis).",
         "Percentages & Growth", "Diagnosis Related Group (DRG) Relative Weight Case-Mix Impact",
         "A hospital discharges 120 inpatients in a month. 40 patients fall into DRG A (Relative Weight 1.25), 50 patients fall into DRG B (Relative Weight 1.80), and 30 patients fall into DRG C (Relative Weight 2.40). What is the hospital's Case Mix Index (CMI) for this discharge cohort?",
         ["1.767", "1.650", "1.820", "1.710"], 0,
         "Calculation: Total Relative Weight = (40 * 1.25) + (50 * 1.80) + (30 * 2.40) = 50 + 90 + 72 = 212. Total discharges = 120. Case Mix Index (CMI) = 212 / 120 = 1.7666... which rounds to 1.767.",
         "Case Mix Index = Total Accumulated Relative Weight / Total Discharges",
         "Deductive Analysis", "Determining Principal Diagnosis for Inpatient Poisoning vs Adverse Effect",
         "A patient accidentally takes a double dose of their prescribed blood pressure medication and develops acute hypotension. According to ICD-10-CM guidelines, how should this be sequenced?",
         ["Code first the Poisoning code (T-code indicating accidental overdose), followed by the manifestation code (hypotension).",
          "Code first the hypotension, followed by the adverse effect T-code.",
          "Code only the hypertension condition.",
          "Code the underdosing code followed by cardiac arrest."], 0,
         "Under ICD-10-CM guidelines: when an overdose occurs (even if accidental), it is classified as a poisoning. The poisoning code is sequenced first, followed by codes for the clinical manifestations."),

        (12, "hr-question", "Answering: 'How Do You Stay Current with Annual Coding Regulatory Changes?'",
         "An executive interviewer asks: 'ICD-10, CPT, and CMS rules change continuously every October and January. What is your system for ensuring our practice never falls out of compliance?'",
         "Articulate continuous professional education habits, AAPC/AHIMA CEUs, Federal Register reviews, and internal knowledge dissemination.",
         ["AAPC / AHIMA Continuing Education", "CMS Transmittals & Federal Register", "Quarterly Team In-Services"],
         "Proactive Professional Excellence (Demonstrate systematic, structured continuous learning)",
         "I wait for the annual coding book updates to arrive and read the summary section in the beginning.",
         "Passive and reactive. Fails to account for quarterly NCCI updates, transmittals, and mid-year CMS policy changes.",
         "I maintain an active, multi-tiered regulatory update workflow. Annually, I attend the AAPC/AHIMA national update webinars ahead of the October 1st ICD-10-CM and January 1st CPT releases to map additions, deletions, and guideline revisions into our billing software crosswalks. Quarterly, I monitor CMS Transmittals and Medicare MLN Matters bulletins to track NCCI PTP and MUE edit updates. Crucially, I translate these regulatory changes into practical one-page clinical cheat-sheets and 15-minute lunch-and-learn sessions for our providers, preventing clearinghouse denials before changes go live.",
         "Impressive, proactive, and demonstrates the candidate is not just a passive coder, but an active clinical educator and compliance leader.",
         "Showcase proactive regulatory monitoring: mention CMS Transmittals, quarterly NCCI edits, and provider education.",
         "Combinatorics & Permutations", "Outpatient CPT Coding Multi-Specialty Modifier Combinations",
         "A surgical coder evaluates an encounter with 3 distinct procedural codes. The payer allows 2 possible procedural modifiers (-59 or -XU) and 2 possible anatomical modifiers (RT or LT). How many unique modifier permutations are theoretically possible across a single line item?",
         ["4 combinations", "6 combinations", "8 combinations", "2 combinations"], 0,
         "Calculation: Permutations = 2 procedural modifiers * 2 anatomical modifiers = 4 unique combinations.",
         "Total Combinations = Modifiers Type 1 * Modifiers Type 2",
         "Constraint Solving", "Medically Unlikely Edits (MUE) Units of Service Validation",
         "A provider bills 3 units of CPT 45378 (Diagnostic colonoscopy) on the same date of service for the same patient. The CMS Medically Unlikely Edit (MUE) table specifies a maximum unit value of '1' with an MUE adjudication indicator of '2' (date of service edit). What must the coder do?",
         ["Correct the claim to bill exactly 1 unit because a patient can clinically undergo only one complete diagnostic colonoscopy per calendar day.",
          "Add Modifier -59 to bill all 3 units separately.",
          "Appeal to the state insurance board for triple reimbursement.",
          "Change the code to an unlisted endoscopy code."], 0,
         "MUEs establish the maximum units of service a provider can report under typical circumstances. An MUE of 1 with date of service edit cannot be overridden when anatomical duplication is clinically impossible."),

        (13, "interview-question", "Explaining the Difference Between ICD-10-CM Excludes1 and Excludes2 Notes",
         "The interviewer asks: 'What is the critical compliance difference between an Excludes1 note and an Excludes2 note in the ICD-10-CM tabular list?'",
         "Explain the categorical rule: Excludes1 means 'NOT CODED HERE' (mutually exclusive conditions), whereas Excludes2 means 'NOT INCLUDED HERE' (patient may have both conditions concurrently).",
         ["Excludes1 ('Not Coded Here')", "Excludes2 ('Not Included Here')", "Tabular List Conventions"],
         "Convention Precision (Know the fundamental rules that govern clean diagnostic claim submission)",
         "Excludes1 means you can never bill the two codes together. Excludes2 means you can bill them together if you have documentation.",
         "Partially correct but incomplete. Misses the official definition and the important exception for unrelated clinical conditions.",
         "In ICD-10-CM, an 'Excludes1' note represents a pure exclusion meaning 'NOT CODED HERE'. It indicates that the code being excluded and the code under which the note appears are clinically mutually exclusive and should never be used together—such as a congenital form versus an acquired form of the same condition (with a rare exception when the two conditions are completely unrelated). Conversely, an 'Excludes2' note means 'NOT INCLUDED HERE'. It indicates that although the excluded condition is not part of the condition represented by the code, a patient may suffer from both conditions concurrently. When documented, both codes may be reported together compliantly.",
         "Flawless technical answer: provides exact convention phrasing ('Not Coded Here' vs 'Not Included Here') and clinical context.",
         "Memorize: Excludes1 = 'NOT CODED HERE' (mutually exclusive); Excludes2 = 'NOT INCLUDED HERE' (both may be coded together if documented).",
         "Averages & Distributions", "Medical Audit Error Rate Benchmark",
         "Across 4 consecutive quarterly chart audits, a hospital coding unit records individual audit error rates of 6.2%, 4.8%, 3.5%, and 5.5%. What is the annual average audit error rate across these four quarters?",
         ["5.0%", "4.8%", "5.2%", "5.5%"], 0,
         "Calculation: Sum of error rates = 6.2 + 4.8 + 3.5 + 5.5 = 20.0%. Average = 20.0% / 4 = 5.0%.",
         "Mean Error Rate = Sum of Quarterly Rates / 4",
         "Debugging Logic", "Resolving Combination Codes in Diabetic Manifestations",
         "A coder submits two separate codes for a diabetic patient: E11.9 (Type 2 diabetes without complications) and N18.3 (Stage 3 chronic kidney disease). What is the coding convention error?",
         ["Under ICD-10-CM guideline I.C.4.a, diabetes and chronic kidney disease have a presumed causal relationship ('with'); the coder must assign combination code E11.22 (Type 2 diabetes with diabetic chronic kidney disease) plus N18.3.",
          "The coder should only code the kidney disease and omit the diabetes completely.",
          "Diabetes and kidney disease can never be coded on the same patient.",
          "The coder must wait for a kidney biopsy before coding any renal condition in diabetes."], 0,
         "ICD-10-CM assumes a causal link between diabetes and conditions listed under 'with' (such as CKD). The guidelines mandate reporting the diabetic combination code (E11.22) followed by the stage of CKD."),

        (14, "workplace-scenario", "Conducting a Compliant Telehealth Billing Review",
         "A clinical practice expanded video telehealth visits during the winter and submits CPT 99214 with standard office place of service (POS 11) and no telehealth modifiers.",
         "Explain CMS telehealth guidelines, Place of Service codes (POS 02 vs POS 10), and mandatory modifiers (-95) to ensure audit compliance.",
         ["Place of Service 02 / 10", "Modifier -95 (Synchronous Telehealth)", "CMS Telehealth Originating Site Rules"],
         "Telehealth Regulatory Compliance (Ensure virtual encounters match payer place-of-service and modifier rules)",
         "We should just bill POS 11 like normal visits because the doctor did the work from their office.",
         "Violates CMS billing guidelines and triggers audit recoupment for misrepresenting the place of service.",
         "Billing telehealth visits under Place of Service 11 (Office) without telehealth modifiers misrepresents the encounter location and exposes the practice to audit recoupment. CMS mandates distinct POS codes: POS 02 for telehealth provided outside the patient's home, and POS 10 for telehealth provided in the patient's home. Furthermore, CPT codes must be appended with Modifier -95 to verify synchronous real-time audio and video interaction. Aligning our claim scrubber with these POS and modifier rules guarantees clean claim payment and protects our revenue from post-payment audits.",
         "Clear, actionable compliance instruction that protects the clinic from major telehealth audit recoupments.",
         "Telehealth billing essentials: use POS 10 (patient home) or POS 02 (other facility) and append Modifier -95 for real-time audio/video.",
         "Percentages & Growth", "Telehealth Volume Growth and Copay Collection",
         "A medical group transitions 800 patient visits to telehealth in January. By April, telehealth visits grow by 45%. If each visit collects an average patient copay of $15.00, what is the total patient copay revenue collected in April?",
         ["$17,400.00", "$16,200.00", "$18,500.00", "$15,800.00"], 0,
         "Calculation: April visits = 800 * (1 + 0.45) = 800 * 1.45 = 1,160 visits. Copay revenue = 1,160 * $15.00 = $17,400.00.",
         "Total Copay = (Base Visits * (1 + Growth Rate)) * Copay Amount",
         "Workflow Ordering", "CMS-1500 Paper Claim vs Electronic 837P Mapping",
         "Which mapping correctly correlates the standard professional claim field on a CMS-1500 paper claim to its electronic HIPAA 837P equivalent?",
         ["Box 21 (Diagnosis Codes) and Box 24D (Procedures / Modifiers) map directly to Loop 2300 / Loop 2400 in the electronic 837P EDI transaction.",
          "Box 1 (Insurance Type) maps to Loop 9999 and Box 24D maps to the patient social security index.",
          "Paper claims cannot be translated into electronic EDI transactions under HIPAA rules.",
          "Box 24D maps to the billing provider bank account number."], 0,
         "The CMS-1500 paper claim corresponds directly to the HIPAA 837P professional electronic transaction, where Box 21 diagnoses map to Loop 2300 and Box 24 service lines map to Loop 2400."),

        (15, "technical-explanation", "Explaining Global Surgical Package Periods (0, 10, vs 90 Days)",
         "A junior surgical coder is confused about why an office visit 2 weeks after an appendectomy cannot be billed as a regular established patient visit.",
         "Explain the concept of the CMS Global Surgical Package (pre-operative, intra-operative, and post-operative care) and global period timeframes.",
         ["Global Surgical Package", "90-Day Major Surgery Global Period", "Post-Operative Follow-Up (CPT 99024)"],
         "Concept Demystification (Show how comprehensive package fees cover typical postoperative care)",
         "You can't bill it because the surgery has a 90-day global period, so you have to bill 99024 which pays zero.",
         "Tells them what to code without explaining the underlying economic rationale of the global surgical bundle.",
         "The reason we don't bill an office visit 2 weeks after an appendectomy is due to the Global Surgical Package. When Medicare or commercial payers reimburse a major surgical procedure (assigned a 90-day global period), that single surgical payment is an all-inclusive bundle covering: the preoperative work 1 day prior, the operation itself, and all routine postoperative follow-up care for 90 days. An uncomplicated post-op incision check is already paid for inside the original surgery fee. We report CPT 99024 as a tracking code with a $0 charge to track clinical workload and care continuity without double-billing the payer.",
         "Exceptional pedagogical clarity: explains the economic bundling logic and the exact role of zero-dollar tracking code 99024.",
         "Always explain global periods: 0-day (minor/endoscopy), 10-day (minor procedure), and 90-day (major surgery, covers routine follow-up).",
         "Financial & Business Math", "Global Period Postoperative Exception Billing",
         "During a 90-day postoperative global period for hip replacement, a patient experiences a surgical site infection requiring an unscheduled return to the operating room for debridement. The procedure fee is $850. Under Modifier -78 rules, the payer reimburses the intraoperative surgical portion at 70% of the allowed fee. How much is reimbursed for this return to the OR?",
         ["$595.00", "$550.00", "$620.00", "$510.00"], 0,
         "Calculation: Allowed reimbursement = $850 * 0.70 = $595.00.",
         "Reimbursement = Allowed Surgical Fee * Intraoperative Factor (70%)",
         "Debugging Logic", "Selecting Modifiers for Staged vs Unplanned Returns to the OR",
         "A patient undergoes a staged breast reconstruction procedure 30 days after initial mastectomy within the 90-day global period, which was planned and documented in the initial operative note. Which modifier must be appended?",
         ["Modifier -58 (Staged or related procedure by the same physician during the global period)",
          "Modifier -78 (Unplanned return to the operating room for a related procedure)",
          "Modifier -79 (Unrelated procedure by the same physician during the global period)",
          "Modifier -24 (Unrelated E/M service during a postoperative period)"], 0,
         "Modifier -58 applies to planned, staged procedures during a global period; Modifier -78 applies to unplanned complications returning to the OR; Modifier -79 applies to unrelated procedures."),
    ]

    for s in foundations:
        days.append({
            "day": s[0],
            "commType": s[1],
            "commTitle": s[2],
            "commScenario": s[3],
            "commPrompt": s[4],
            "commVocab": s[5],
            "commRule": s[6],
            "commWeakResponse": s[7],
            "commWeakCritique": s[8],
            "commStrongResponse": s[9],
            "commStrongCritique": s[10],
            "commCoachTip": s[11],
            "aptTopic": s[12],
            "aptTitle": s[13],
            "aptQuestion": s[14],
            "aptOptions": s[15],
            "aptAnswer": s[16],
            "aptExplanation": s[17],
            "aptFormula": s[18],
            "logicType": s[19],
            "logicTitle": s[20],
            "logicQuestion": s[21],
            "logicOptions": s[22],
            "logicAnswer": s[23],
            "logicExplanation": s[24],
        })

    # Systematic phase topics for Days 16 to 89
    phase_definitions = [
        # Phase 2: Days 16-30 (ICD-10-CM Chapter-Specific Guidelines)
        (16, 30, "ICD-10-CM Guidelines", [
            ("Infectious Diseases: Sepsis, Severe Sepsis and Septic Shock", "Inpatient Guidelines", "Sequencing systemic infection, severe sepsis (R65.20), and organ dysfunction.", ["Systemic Inflammatory Response", "Severe Sepsis Sequencing"]),
            ("HIV / AIDS Coding Guidelines (Code 042 vs Z21)", "Diagnostic Specificity", "Distinguishing confirmed symptomatic HIV disease (B20) from asymptomatic status (Z21).", ["Confirmed HIV (B20)", "Asymptomatic HIV (Z21)"]),
            ("Neoplasm Coding: Primary vs Secondary Malignancies", "Oncology Guidelines", "Determining principal diagnosis when treatment is directed toward metastasis.", ["Primary Site", "Metastatic Secondary Site"]),
            ("Coding Neoplasms with Encounter for Chemotherapy (Z51.11)", "Oncology Sequencing", "Sequencing antineoplastic chemotherapy encounters ahead of the malignancy code.", ["Z51.11 Chemotherapy", "Secondary Diagnosis Sequencing"]),
            ("Type 2 Diabetes Mellitus with Hyperglycemia and Ketoacidosis", "Endocrine Coding", "Differentiating diabetes with ketoacidosis without coma vs with coma.", ["Diabetic Ketoacidosis (DKA)", "Hyperosmolarity"]),
            ("Hypertension with Heart Disease and Chronic Kidney Disease", "Cardiorenal Coding", "Assigning triple combination codes for Hypertensive Heart and CKD (I13).", ["Hypertensive Heart Disease", "Cardiorenal Presumed Causality"]),
            ("Acute Myocardial Infarction: STEMI vs NSTEMI Coding", "Cardiology Guidelines", "Sequencing STEMI site codes vs non-ST segment elevation myocardial infarction (I21.4).", ["STEMI Categorization", "NSTEMI Default Rules"]),
            ("Subsequent Acute Myocardial Infarction (Category I22)", "Cardiology Sequencing", "Reporting second AMI occurring within 4 weeks of the initial infarction.", ["Category I22 (Subsequent AMI)", "4-Week Global Window"]),
            ("Cerebral Infarction (Stroke) with Residual Sequelae / Late Effects", "Neurology Guidelines", "Distinguishing acute stroke care from Category I69 cognitive and neurological deficits.", ["Acute Stroke (I63)", "Late Effects / Sequelae (I69)"]),
            ("Chronic Obstructive Pulmonary Disease (COPD) with Acute Exacerbation", "Pulmonology Guidelines", "Coding acute exacerbation vs acute lower respiratory infection in COPD.", ["COPD Exacerbation", "Infectious Exacerbation"]),
            ("Chronic Kidney Disease (CKD) Stages and End Stage Renal Disease", "Nephrology Guidelines", "Assigning CKD stage based on eGFR and sequencing ESRD with dialysis status.", ["CKD Staging (N18.1-N18.6)", "Dialysis Status (Z99.2)"]),
            ("Pregnancy Trimester Coding and Incidental Pregnancy (Z33.1)", "Obstetrics Guidelines", "Determining when pregnancy is primary vs incidental to an unrelated medical condition.", ["Trimester Extensions", "Supervision of High-Risk (O09)"]),
            ("Pathological Fractures vs Traumatic Fractures", "Orthopedic Guidelines", "Differentiating fractures occurring under normal physiological stress due to osteoporosis.", ["Pathological Fracture (M84)", "Traumatic Fracture (S-category)"]),
            ("Adverse Effect vs Poisoning vs Underdosing Guidelines", "Toxicology Coding", "Selecting correct 7th characters and secondary manifestation codes for medication events.", ["Adverse Effect (T-code)", "Underdosing Intent"]),
            ("Phase 2 Placement Milestone: Diagnostic Guideline Defense", "Coding Interview", "Defending ICD-10-CM chapter guidelines and official sequencing rules in an interview.", ["Coding Conventions", "Official Guidelines"]),
        ]),

        # Phase 3: Days 31-45 (CPT Fundamentals, E/M, Surgery, Radiology & Lab)
        (31, 45, "CPT Procedural Coding", [
            ("New Patient vs Established Patient E/M Decision Rules", "E/M Criteria", "Applying the 3-year professional face-to-face rule across group practice specialties.", ["3-Year Rule", "Same Specialty / Subspecialty"]),
            ("Hospital Inpatient Initial and Subsequent Care (99221-99233)", "Inpatient E/M", "Selecting inpatient service levels based on Medical Decision Making or Total Time.", ["Inpatient MDM", "Total Time Documentation"]),
            ("Emergency Department Services Coding (CPT 99281-99285)", "Emergency E/M", "Coding emergency care where time is not a descriptive component of the code.", ["Emergency MDM", "No Time Component"]),
            ("Critical Care Services (CPT 99291 and 99292) Time Rules", "Critical Care", "Documenting direct personal delivery of critical care in 30-minute increments.", ["First 30-74 Minutes", "Subsequent 30-Minute Blocks"]),
            ("Integumentary Excision: Benign vs Malignant Lesions", "Surgery Guidelines", "Measuring excised diameter plus narrowest margin calculation for lesion sizing.", ["Excised Diameter + Margins", "Benign vs Malignant CPT"]),
            ("Wound Repair: Simple, Intermediate, and Complex Layering", "Surgical Closure", "Summing lengths of repairs within the same anatomical classification and complexity.", ["Summation of Lengths", "Layered Closure Requirements"]),
            ("Musculoskeletal Fracture Care: Closed vs Open Reduction", "Orthopedic Surgery", "Distinguishing restorative manipulation from application of cast without reduction.", ["Manipulation / Reduction", "Surgical Approach"]),
            ("Cardiovascular Diagnostic Cardiac Catheterization Bundling", "Cardiology CPT", "Understanding bundled coronary angiography, ventriculography, and access.", ["Coronary Angiography", "Vascular Catheter Placement"]),
            ("Endoscopy Coding: Diagnostic Colonoscopy with Biopsy vs Snare", "Gastroenterology CPT", "Reporting biopsy (45380) vs snare removal (45385) in separate anatomical lesions.", ["Multiple Endoscopy Rule", "Biopsy vs Snare"]),
            ("Radiology Component Coding: Professional vs Technical Split", "Radiology Billing", "Applying Modifier -26 (Professional) and Modifier -TC (Technical Component).", ["Modifier -26", "Modifier -TC"]),
            ("Diagnostic Ultrasound: Complete vs Limited Exam Documentation", "Radiology Criteria", "Verifying all required organ structures are imaged to support a 'complete' code.", ["Complete vs Limited", "Organ Structure Criteria"]),
            ("Pathology Gross and Microscopic Examination Levels (88300-88309)", "Pathology CPT", "Assigning surgical pathology level based on tissue specimen complexity.", ["Specimen Levels", "Surgical Pathology"]),
            ("Automated Clinical Laboratory Panels and Reflex Testing", "Laboratory Billing", "Coding individual tests vs automated multi-analyte panels compliantly.", ["Reflex Testing Protocol", "Panel Requirements"]),
            ("Physical Therapy Modalities: Supervised vs Constant Attendance", "Physical Medicine", "Documenting 15-minute timed therapy codes using the 8-minute Medicare rule.", ["8-Minute Rule", "Timed Therapy Intervals"]),
            ("Phase 3 Placement Milestone: Procedural CPT Defense Review", "Technical Presentation", "Presenting CPT surgical abstraction and modifier defense to hospital leadership.", ["Operative Abstraction", "CPT Hierarchy"]),
        ]),

        # Phase 4: Days 46-60 (HCPCS Level II, Modifiers & NCCI Edits)
        (46, 60, "HCPCS & Compliance", [
            ("HCPCS Level II National Codes for Injectable Drugs (J-Codes)", "HCPCS Coding", "Calculating billing units from dosage administered versus package vial size.", ["J-Code Billing Units", "Administered vs Wasted"]),
            ("Billing Drug Wastage with Modifier -JW and -JZ", "Compliance Mandate", "Reporting discarded drug volume from single-dose vials on separate claim lines.", ["Modifier -JW (Wasted)", "Modifier -JZ (Zero Wastage)"]),
            ("Durable Medical Equipment, Prosthetics, Orthotics (DMEPOS)", "DMEPOS Billing", "Documenting Certificate of Medical Necessity (CMN) and face-to-face physician orders.", ["Certificate of Medical Necessity", "DMEPOS Coverage"]),
            ("Modifier -50 (Bilateral Procedure) vs Modifiers RT and LT", "Surgical Modifiers", "Applying payer-specific rules for reporting 1-line 150% vs 2-line bilateral billing.", ["Modifier -50 Bilateral", "Anatomical Laterality"]),
            ("Modifier -51 (Multiple Procedures) and Fee Reductions", "Reimbursement Rules", "Understanding payer multi-procedure discounting (100% / 50% / 50%).", ["Multiple Procedure Discount", "Standard Fee Reduction"]),
            ("Modifier -52 (Reduced Services) vs Modifier -53 (Discontinued)", "Surgical Complications", "Distinguishing elective physician reductions from anesthesia safety termination.", ["Modifier -52 Reduced", "Modifier -53 Discontinued"]),
            ("Anatomical HCPCS Modifiers -E1 to -E4, -FA to -F9, -TA to -T9", "Precision Modifiers", "Identifying exact digit, eyelid, or toe location on specialty procedures.", ["Digit Anatomical Modifiers", "Claim Line Scrubbing"]),
            ("HCPCS Modifiers -XE, -XS, -XP, -XU (The Medicare X-Modifiers)", "NCCI Modifiers", "Using specific subset modifiers instead of generic -59 for Medicare claims.", ["Medicare X{EPSU} Modifiers", "Distinct Service Subsets"]),
            ("NCCI Medically Unlikely Edits (MUE) Adjudication Indicators", "Claim Scrubbing", "Differentiating line-item edits from date-of-service cumulative unit ceilings.", ["MUE Adjudication Indicator", "Units of Service Cap"]),
            ("Comprehensive vs Component PTP Edits in Outpatient Hospitals", "Hospital OPPS", "Preventing improper separate billing under CMS Outpatient Code Editor (OCE).", ["Outpatient Code Editor (OCE)", "PTP Column Edits"]),
            ("Office of Inspector General (OIG) Work Plan and Target Audits", "Compliance Monitoring", "Aligning internal audits with active OIG high-risk billing enforcement priorities.", ["OIG Work Plan", "High-Risk Target Areas"]),
            ("Federal Anti-Kickback Statute and Stark Law in Coding / Billing", "Healthcare Law", "Recognizing illegal remuneration and physician self-referral violations.", ["Anti-Kickback Statute", "Stark Law Compliance"]),
            ("Health Care Fraud and Abuse Control (HCFAC) Recovery Metrics", "Enforcement Overview", "Understanding federal civil monetary penalties for persistent False Claims.", ["Civil Monetary Penalties", "Treble Damages"]),
            ("Corporate Integrity Agreements (CIA) and Compliance Programs", "Corporate Governance", "Structuring seven core compliance program elements under OIG guidelines.", ["Seven Compliance Elements", "Independent Review Org"]),
            ("Phase 4 Placement Milestone: NCCI & Compliance Audit Defense", "Audit Presentation", "Defending modifier compliance and NCCI unbundling rules to audit committees.", ["Compliance Safeguards", "Modifier Legality"]),
        ]),

        # Phase 5: Days 61-75 (Revenue Cycle, Claims, Denials & Appeals)
        (61, 75, "RCM & Denials", [
            ("CMS-1500 Professional Claim vs UB-04 Institutional Claim", "Claim Types", "Differentiating physician fee billing from facility room, board, and nursing fees.", ["CMS-1500 (837P)", "UB-04 / CMS-1450 (837I)"]),
            ("Revenue Codes and HCPCS Crosswalks on Institutional UB-04", "Facility Billing", "Mapping 4-digit revenue codes (e.g., 0360 Operating Room) to line items.", ["Revenue Codes", "Type of Bill (TOB)"]),
            ("Electronic Data Interchange (EDI) Claim Clearinghouse Cycles", "EDI Transactions", "Understanding ANSI ASC X12 837 claim transmission and 999 acknowledgments.", ["ANSI 837 Protocol", "999 / 277CA Acceptance"]),
            ("Electronic Remittance Advice (ERA 835) and Claim Adjustment Codes", "Payment Posting", "Interpreting CARC (Claim Adjustment Reason) and RARC remark codes.", ["835 Payment Advice", "CARC / RARC Reason Codes"]),
            ("Analyzing Front-End Clearinghouse Rejections vs Back-End Denials", "RCM Operations", "Distinguishing demographic format rejections from clinical coverage denials.", ["Clearinghouse Rejections", "Payer Clinical Denials"]),
            ("CO-45 (Contractual Obligation / Maximum Fee Schedule Write-Off)", "Financial Adjustments", "Posting contractual adjustments correctly without unallowable patient billing.", ["Contractual Adjustment", "Prohibited Balance Billing"]),
            ("PR-1, PR-2, PR-3 (Patient Responsibility Deductible, Coinsurance)", "Patient Accounting", "Accurately billing patient balances supported by compliant adjudication.", ["Patient Deductible (PR-1)", "Coinsurance (PR-2)"]),
            ("Appealing Timely Filing Limit Denials (Proof of Timely Submission)", "Payer Appeals", "Providing clearinghouse batch acceptance logs to overturn timely filing denials.", ["Timely Filing Window", "Clearinghouse Proof of Filing"]),
            ("Appealing 'Experimental / Investigational' Service Denials", "Clinical Appeals", "Compiling peer-reviewed clinical trial literature and FDA approval indications.", ["Peer-Reviewed Literature", "Investigational Rebuttal"]),
            ("Coordinating Prior Authorizations and Retro-Authorizations", "Utilization Management", "Preventing denials by linking valid authorization numbers on claim line Loop 2300.", ["Prior Authorization", "Retro-Authorization"]),
            ("Coordination of Benefits (COB) and Birthday Rule Logic", "Secondary Billing", "Determining primary payer between parents using calendar birthday guidelines.", ["Birthday Rule", "Primary vs Secondary"]),
            ("Credit Balance Resolution and Mandatory Overpayment Refunds", "Financial Compliance", "Meeting the federal 60-day deadline for refunding Medicare overpayments.", ["60-Day Overpayment Rule", "Reverse False Claims"]),
            ("Lockbox Banking and Automated Payment Posting Reconciliation", "Treasury & RCM", "Matching bank deposits against posted ERA 835 transaction batches.", ["Payment Reconciliation", "Unapplied Cash Resolution"]),
            ("Value-Based Alternative Payment Models (Bundled Payments / BPCI)", "Healthcare Economics", "Managing single episode-of-care payments across acute and post-acute providers.", ["Bundled Payment Episode", "Target Price Reconciliation"]),
            ("Phase 5 Placement Milestone: Revenue Cycle Management Review", "Management Defense", "Presenting denial reduction metrics and Days in A/R performance to CFO.", ["Cash Flow Velocity", "Denial Resolution Rate"]),
        ]),

        # Phase 6: Days 76-89 (CDI, Physician Queries, HCCs & Audits)
        (76, 89, "CDI & Quality Audits", [
            ("Clinical Documentation Improvement (CDI) Specialist Daily Workflow", "CDI Operations", "Reviewing concurrent inpatient charts to bridge clinical acuity and code specificity.", ["Concurrent Chart Review", "Query Opportunities"]),
            ("Constructing Verbal vs Written Physician Queries Under AHIMA Rules", "Provider Engagement", "Documenting verbal queries contemporaneously in compliance with query standards.", ["Verbal Query Protocol", "Contemporaneous Record"]),
            ("Clarifying Malnutrition Severity (Mild, Moderate, Severe Marasmus)", "Inpatient Acuity", "Querying provider when clinical dietitian nutritional assessments meet criteria.", ["Severe Malnutrition", "CC / MCC Capture"]),
            ("Documenting Encephalopathy (Toxic, Metabolic, Anoxic) vs Confusion", "Neurology CDI", "Capturing acute metabolic encephalopathy as an MCC during acute hospitalizations.", ["Metabolic Encephalopathy", "MCC Diagnostic Capture"]),
            ("Acute Blood Loss Anemia vs Chronic Anemia in Surgical Patients", "Post-Op Complications", "Distinguishing expected intraoperative drop from acute blood loss anemia.", ["Acute Blood Loss Anemia", "Complication vs Expected"]),
            ("CMS Hierarchical Condition Categories (HCC) Version 28 Transition", "Risk Adjustment", "Navigating changes in coefficient weights and dropped categories in V28.", ["HCC V28 Transition", "Dropped Category Impacts"]),
            ("Prescription Drug HCCs (RxHCC) for Part D Risk Adjustment", "Medicare Part D", "Tracking chronic medication therapies tied to Part D risk scores.", ["RxHCC Modeling", "Part D Disease Burden"]),
            ("Risk Adjustment Data Validation (RADV) Audit Preparation", "CMS Audits", "Sampling patient charts to verify documentation withstands federal RADV scrutiny.", ["RADV Audit Standards", "Extrapolation Risk"]),
            ("Internal Coding Quality Audit Methodology: Random vs Targeted Sampling", "Quality Assurance", "Structuring 95% confidence internal audits targeting high-risk DRGs.", ["Targeted DRG Audits", "Random Quality Sample"]),
            ("Merit-based Incentive Payment System (MIPS) Quality Performance", "Quality Reporting", "Reporting quality measure codes to maximize Medicare provider fee bonuses.", ["MIPS Quality Measures", "Fee Schedule Modifier"]),
            ("Healthcare Common Procedure Coding System (HCPCS) Quality Category II", "Performance Measures", "Utilizing tracking codes (e.g., 3008F for BP < 140/90) for clinical measures.", ["Category II CPT Codes", "Quality Metric Tracking"]),
            ("Root Cause Analysis (RCA) on Recurrent Hospital Claim Denials", "Quality Improvement", "Applying Lean Six Sigma / Ishikawa diagrams to solve recurring billing flaws.", ["Ishikawa Fishbone Diagram", "Process Remediation"]),
            ("Defending Medical Coding Audits Against Third-Party Recovery Audit Contractors", "RAC Audits", "Structuring multi-level administrative law judge (ALJ) appeals against RAC denials.", ["RAC Recoupment Defense", "ALJ Hearing Strategy"]),
            ("Senior Medical Coder Career Pathway: CPC to CPMA and CRC Mastery", "Career Development", "Preparing for medical auditor certification and clinical leadership roles.", ["CPMA Certified Auditor", "CRC Risk Specialist"]),
        ]),
    ]

    for p_start, p_end, p_phase, p_topics in phase_definitions:
        for idx, t in enumerate(p_topics):
            d_num = p_start + idx
            t_title, t_cat, t_desc, t_vocab = t
            rate_base = 240 + (d_num * 10)
            delta_pct = 12 + (d_num % 18)
            result_val = int(rate_base * (1 + delta_pct / 100))

            days.append({
                "day": d_num,
                "commType": COMM_TYPES[d_num % len(COMM_TYPES)],
                "commTitle": t_title,
                "commScenario": f"During a clinical coding workflow review for {t_title}, stakeholders request clarification on {t_desc}.",
                "commPrompt": f"Explain the critical coding guidelines, documentation requirements, and compliance implications of {t_title} with precision.",
                "commVocab": [t_vocab[0], t_vocab[1]],
                "commRule": "Healthcare Documentation Accuracy & Regulatory Compliance",
                "commWeakResponse": f"We just code {t_title} according to whatever the doctor wrote quickly without checking official guidelines.",
                "commWeakCritique": "Vague, passive, and demonstrates a severe lack of compliance rigor and guideline familiarity.",
                "commStrongResponse": f"In our medical coding operations, {t_title} is abstracted using {t_vocab[0]} and {t_vocab[1]} to guarantee complete documentation compliance, eliminate unbundling risks, and protect reimbursement integrity.",
                "commStrongCritique": "Structured, authoritative, and strictly connects clinical documentation to official regulatory standards.",
                "commCoachTip": f"Always anchor your explanation in official guidelines: explain how {t_vocab[0]} prevents clearinghouse rejections.",
                "aptTopic": APT_TOPICS[d_num % len(APT_TOPICS)],
                "aptTitle": f"{t_title} Productivity & Billing Math",
                "aptQuestion": f"A healthcare billing unit processes {rate_base:,} encounter claims per day. After implementing workflow improvements for {t_title}, claim throughput increases by {delta_pct}%. What is the new daily claim volume processed?",
                "aptOptions": [f"{result_val:,} claims/day", f"{result_val - 25:,} claims/day", f"{result_val + 30:,} claims/day", f"{result_val - 40:,} claims/day"],
                "aptAnswer": 0,
                "aptExplanation": f"Calculation: Increase = {rate_base} * {delta_pct/100:.2f} = {result_val - rate_base}. New claim volume = {rate_base} + {result_val - rate_base} = {result_val:,} claims/day.",
                "aptFormula": "New Volume = Base Claims * (1 + Increase Rate)",
                "logicType": LOGIC_TYPES[d_num % len(LOGIC_TYPES)],
                "logicTitle": f"{t_title} Compliance Logic",
                "logicQuestion": f"When evaluating a clinical chart for {t_title}, which regulatory or coding constraint must be verified before submitting the claim?",
                "logicOptions": [
                    f"Verify that {t_vocab[0]} is explicitly substantiated in the clinical progress notes before assigning billable codes.",
                    f"Bypass {t_vocab[1]} completely to expedite claim submission without provider documentation.",
                    "Assign high-level surgical codes without reviewing the operative report narrative.",
                    "Unbundle composite panel codes into separate individual laboratory line items."
                ],
                "logicAnswer": 0,
                "logicExplanation": f"Correct! In {t_title}, ensuring that {t_vocab[0]} is clearly documented in the medical record protects the organization from False Claims audits and guarantees medical necessity.",
            })

    # Day 90: Final Placement Challenge
    days.append({
        "day": 90,
        "commType": "interview-question",
        "commTitle": "FINAL PLACEMENT CHALLENGE: Lead Medical Coder & Compliance Auditor Placement Defense",
        "commScenario": "You are presenting before the Hospital Compliance Committee and the Chief Medical Officer for a Lead Medical Coder and Auditor position.",
        "commPrompt": "Deliver an end-to-end strategic compliance walkthrough of an acute hospital revenue cycle coding program: detailing NCCI edit scrubbing, non-leading CDI physician query governance, annual HCC risk adjustment capture across 25,000 Medicare Advantage patients, and defense protocols against OIG and RAC audits.",
        "commVocab": ["Hospital Revenue Integrity", "RADV Audit Defense", "Non-Leading Query Governance"],
        "commRule": "Executive Healthcare Presence, Regulatory Authority & Compliance Mastery",
        "commWeakResponse": "We check all claims against coding books, ask doctors to fix notes when claims are denied, and make sure we code as much as possible so the hospital gets paid.",
        "commWeakCritique": "Lacks regulatory terminology, fails to explain non-leading query ethics, and ignores federal False Claims Act exposure.",
        "commStrongResponse": "Our enterprise revenue integrity framework enforces a zero-tolerance compliance architecture aligned with AHIMA, AAPC, and CMS mandates. Front-end claims pass through dual-layer NCCI and MUE scrubbers to eliminate improper unbundling and modifier abuse. Inpatient documentation is reviewed concurrently by our CDI team using strictly non-leading, evidence-based physician queries that substantiate clinical acuity (such as sepsis and severe malnutrition) without coaching. For our 25,000 Medicare Advantage lives, we conduct 100% pre-bill validation on chronic condition MEAT criteria to insulate the health system from CMS RADV audit extrapolation penalties. In the event of a third-party RAC audit, our multi-tiered documentation tracking guarantees complete audit-trail defensibility and maximum legitimate reimbursement.",
        "commStrongCritique": "Flawless executive defense: perfectly balances regulatory ethics, physician collaboration, payer scrubbing, and risk adjustment integrity.",
        "commCoachTip": "In the final placement challenge, demonstrate complete command over coding guidelines, physician query ethics, and legal audit protection.",
        "aptTopic": "Data Interpretation & Metrics",
        "aptTitle": "Final Assessment: Hospital Inpatient Medicare DRG Reimbursement Math",
        "aptQuestion": "A hospital discharges 40 inpatients with Septicemia without ventilator support (MS-DRG 872, Relative Weight 1.450). The hospital's base Medicare operating payment rate is $6,200.00 per unit of weight. What is the total Medicare reimbursement generated for this discharge cohort?",
        "aptOptions": ["$359,600.00", "$345,000.00", "$372,000.00", "$325,000.00"],
        "aptAnswer": 0,
        "aptExplanation": "Calculation: Reimbursement per patient = Relative Weight (1.450) * Base Rate ($6,200.00) = $8,990.00. Total cohort reimbursement = 40 patients * $8,990.00 = $359,600.00.",
        "aptFormula": "Cohort Reimbursement = Patients * (Relative Weight * Base Operating Rate)",
        "logicType": "Decision Architecture",
        "logicTitle": "Final Assessment: End-to-End Clinical Documentation & Legal Compliance Logic",
        "logicQuestion": "A hospital internal audit reveals that a high-volume orthopedic surgeon is consistently documenting 'extensive debridement' in operative titles, but the surgical narrative only describes normal wound irrigation. Billing staff have been appending Modifier -22 to claim extra 25% reimbursement. According to federal compliance rules, what is the mandatory immediate action?",
        "logicOptions": [
            "Halt all Modifier -22 submissions for this surgeon immediately, refund any improper historical overpayments to payers within 60 days, conduct provider re-education on operative documentation, and implement mandatory pre-bill coding audits.",
            "Continue billing Modifier -22 because the surgeon has executive seniority in the hospital.",
            "Instruct the floor coders to alter the surgeon's operative report narrative after the fact to match the title.",
            "Ignore the discrepancy unless an external RAC auditor sends a formal demand letter."
        ],
        "logicAnswer": 0,
        "logicExplanation": "Correct! When an internal audit discovers unsubstantiated claims, the provider must immediately halt billing, self-disclose and refund overpayments within the 60-day federal mandate, and institute corrective provider education to eliminate False Claims Act liability.",
    })

    return days

print("medical_data module ready.")
