# scripts/generators/sap_data.py
"""
90 Days of Course-Specific Placement Accelerator Content for SAP FICO (track: sap)
Phases:
1. Days 1-15: Enterprise Structure, SAP Fiori / GUI, Company Code, Chart of Accounts & Posting Periods
2. Days 16-30: General Ledger (FI-GL), Document Types, Posting Keys, Field Status & Document Splitting
3. Days 31-45: Accounts Payable (FI-AP), Accounts Receivable (FI-AR), Payment Terms, F110 & Dunning
4. Days 46-60: Asset Accounting (FI-AA), Depreciation Keys, Asset Classes & Capital Work in Progress (CWIP)
5. Days 61-75: Controlling (CO), Cost Centers (CO-CCA), Internal Orders & Profit Center Accounting (CO-PCA)
6. Days 76-89: Period-End Closing, MM-FI & SD-FI Integration, GST/VAT & S/4HANA Universal Journal (ACDOCA)
Day 90: Final Placement Challenge
"""

COMM_TYPES = [
    "interview-question", "technical-explanation", "client-conversation",
    "team-communication", "workplace-scenario", "problem-explanation",
    "project-explanation", "technical-presentation", "email-response",
    "manager-conversation", "hr-question", "conflict-resolution",
    "requirement-clarification", "technical-to-nontechnical",
]

APT_TOPICS = [
    "Percentages & Growth", "Ratios & Proportions", "Averages & Distributions",
    "Profit, Margin & ROI", "Time, Work & Capacity", "Speed, Latency & Distance",
    "Probability & Reliability", "Combinatorics & Permutations", "Number Systems & Units",
    "Data Interpretation & Metrics", "Statistics & Dispersion", "Financial & Business Math",
]

LOGIC_TYPES = [
    "Sequence Reasoning", "Workflow Ordering", "Deductive Analysis",
    "Constraint Solving", "Debugging Logic", "Process Flow",
    "Cause & Effect", "Decision Architecture",
]

def get_sap_days():
    days = []

    # 15 Detailed Foundations Days
    foundations = [
        (1, "technical-to-nontechnical", "Explaining Company Code vs Business Area to a CFO",
         "A non-technical CFO of a newly acquired conglomerate asks why their three regional business divisions cannot simply be set up as three separate Company Codes in SAP.",
         "Explain the legal, fiscal, and statutory boundary of a Company Code (independent balance sheet/P&L) versus internal managerial reporting via Business Areas / Profit Centers.",
         ["Company Code (Legal Entity)", "Profit Center / Business Area", "Statutory vs Managerial Reporting"],
         "The Statutory Separation Principle (Company codes represent independent legal accounting entities)",
         "Company codes are for legal taxes and business areas are just for internal reports, so you shouldn't make too many company codes.",
         "Too simplistic. Fails to explain the administrative overhead of intercompany transactions and consolidated reporting.",
         "In SAP enterprise architecture, a Company Code represents an independent legal entity with its own commercial registration, statutory tax filings, and mandatory standalone Balance Sheet and P&L. If we create separate Company Codes for your regional divisions, every single inventory transfer between them legally becomes an 'Intercompany Sale', requiring cross-company billing, transfer pricing, and complex year-end financial consolidations. Instead, we configure your parent entity as a single Company Code, and model your three regional divisions as Profit Centers. This provides complete divisional P&L visibility for management while avoiding millions in intercompany accounting overhead.",
         "Exemplary executive consulting: prevents costly ERP misconfiguration, explains intercompany friction, and delivers clean managerial reporting.",
         "Always articulate the core rule: Company Code = Legal/Statutory entity (External); Profit Center = Operational segment (Internal).",
         "Financial & Business Math", "Goods and Services Tax (GST) Calculation on Vendor Invoice",
         "An enterprise records an accounts payable vendor invoice for raw materials valued at ₹250,000. Under applicable tax regulations, an 18.0% Goods and Services Tax (GST) applies (split equally between CGST and SGST). What is the total invoice amount payable to the vendor?",
         ["₹295,000", "₹280,000", "₹300,000", "₹275,000"], 0,
         "Calculation: Tax amount = ₹250,000 * 0.18 = ₹45,000. Total gross payable = ₹250,000 + ₹45,000 = ₹295,000 (CGST ₹22,500 + SGST ₹22,500).",
         "Gross Amount = Net Base Amount * (1 + Tax Rate)",
         "Workflow Ordering", "Standard SAP P2P (Procure-to-Pay) MM-FI Integration Sequence",
         "Which sequence accurately represents the financial and logistical integration flow of the Procure-to-Pay (P2P) cycle in SAP?",
         ["Purchase Requisition (ME51N) -> Purchase Order (ME21N) -> Goods Receipt (MIGO: Dr Inventory / Cr GR/IR) -> Invoice Verification (MIRO: Dr GR/IR / Cr Vendor) -> Payment Program (F110: Dr Vendor / Cr Bank)",
          "Invoice Verification -> Goods Receipt -> Purchase Order -> Payment Program -> Purchase Requisition",
          "Goods Receipt -> Purchase Requisition -> Payment Program -> Invoice Verification -> Purchase Order",
          "Payment Program -> Goods Receipt -> Invoice Verification -> Purchase Order -> Requisition"], 0,
         "In the standard SAP P2P lifecycle, purchasing issues the PO, warehouse receipt triggers inventory and GR/IR clearing entries via MIGO, finance verifies the invoice via MIRO clearing GR/IR against the vendor, and treasury executes payment via F110."),

        (2, "interview-question", "Explaining S/4HANA Universal Journal (ACDOCA) to a Technical Interviewer",
         "An enterprise interviewer asks: 'How does SAP S/4HANA Universal Journal (table ACDOCA) fundamentally revolutionize financial accounting compared to legacy ECC 6.0?'",
         "Articulate the unification of FI (Financial Accounting) and CO (Controlling), the elimination of reconciliation ledgers, single source of truth, and multi-dimensional reporting.",
         ["Universal Journal (Table ACDOCA)", "FI-CO Reconciliation Elimination", "Single Source of Truth"],
         "Architectural Evolution (Highlight how in-memory columnar storage unifies general ledger with management controlling)",
         "In ECC we had lots of tables like BKPF, BSEG, and COEP. In S/4HANA everything goes into table ACDOCA so it is much faster.",
         "Accurate in name but shallow. Fails to explain the elimination of FI-CO reconciliation or multi-GAAP parallel accounting.",
         "In legacy ECC 6.0, Financial Accounting (FI) and Controlling (CO) existed as separate data silos stored in disparate tables (BSIS, BSAK, COEP), requiring cumbersome month-end FI-CO reconciliation postings. SAP S/4HANA shatters this divide by introducing the Universal Journal in table ACDOCA—a single, unified line-item table that combines GL accounts, cost centers, profit centers, internal orders, and asset transactions in real time. Every accounting document automatically carries both statutory financial data and managerial controlling dimensions in a single line. This eliminates FI-CO reconciliation entirely, provides instantaneous profitability analysis, and allows multi-GAAP parallel accounting within one single source of truth.",
         "Flawless technical command: contrasts legacy tabular silos with ACDOCA and cites exact business benefits (zero FI-CO reconciliation, instant P&L).",
         "Always highlight ACDOCA's defining achievement: complete real-time unification of FI (Financial Accounting) and CO (Controlling).",
         "Percentages & Growth", "Early Payment Cash Discount Math (Payment Terms 2/10 Net 30)",
         "A vendor issues an invoice of $80,000 with SAP payment terms '2/10, Net 30' (2% cash discount if paid within 10 days, otherwise net full amount due in 30 days). The finance team executes an early payment via transaction F110 on Day 8. How much cash discount does the enterprise capture?",
         ["$1,600", "$1,200", "$2,000", "$800"], 0,
         "Calculation: Discount Amount = Invoice Value * Discount Rate = $80,000 * 0.02 = $1,600. The net amount disbursed to the vendor is $78,400.",
         "Cash Discount = Gross Invoice Amount * Discount Percentage",
         "Deductive Analysis", "Diagnosing GR/IR Clearing Account Variances in MIRO",
         "During invoice verification (transaction MIRO), the invoice price for 100 units of raw materials is $105/unit, whereas the purchase order and goods receipt (MIGO) were recorded at $100/unit. How does SAP automatically handle the $500 price variance under standard costing?",
         ["Under standard price control (S), SAP posts the $500 price difference to a designated Price Difference (PRD) GL account, leaving the inventory valuation at standard cost.",
          "The system aborts the transaction and deletes the purchase order automatically.",
          "The vendor account is credited for only $100/unit and the vendor is short-paid without notification.",
          "The variance is booked directly to customer bad debt expense."], 0,
         "When material price control is set to Standard (S), inventory is valued at fixed standard cost; any variance between PO/GR and the verified invoice in MIRO is routed to Price Difference (PRD) accounts."),

        (3, "team-communication", "Mentoring a Junior Consultant on SAP Document Splitting in New GL",
         "A junior functional consultant encounters an error during vendor invoice posting: 'Balancing field Profit Center in line item 001 not filled' and doesn't understand why.",
         "Explain the concept of Document Splitting in SAP New GL / S/4HANA: splitting balancing balance sheet accounts by segment and profit center for compliant financial statements.",
         ["Document Splitting", "Segment Reporting (IFRS / US GAAP)", "Passive vs Active Splitting"],
         "Functional Guidance (Break down how document splitting creates segment-balanced balance sheets)",
         "You got that error because document splitting is turned on. Just enter a profit center manually in every line.",
         "Uninstructive and misleading. Vendor and tax lines cannot always have manual profit centers entered directly by users.",
         "Great troubleshooting scenario! In SAP New GL and S/4HANA, Document Splitting is active to support Segment Reporting under IFRS and US GAAP. When you post a vendor invoice containing expenses for two different profit centers, the vendor liability line (line item 001) doesn't naturally know which profit center it belongs to. Document Splitting automatically splits the vendor payable and tax lines in the general ledger view proportionally based on the expense lines, ensuring that each profit center's Balance Sheet balances to zero. The error indicates that the underlying Document Type is not properly configured with an assigned Business Transaction Variant in customizing. Let's inspect the document splitting characteristics together.",
         "Superb coaching: explains the 'why' (IFRS segment reporting) and guides the junior consultant to the correct customizing table.",
         "Explain Document Splitting: it splits balance sheet lines (vendor/tax) proportionally across expense profit centers to create balanced segment balance sheets.",
         "Financial & Business Math", "Straight-Line Depreciation Calculation in Asset Accounting (FI-AA)",
         "A manufacturing company capitalizes production machinery with an acquisition value of $120,000 and an estimated useful life of 5 years (zero salvage value). Under the straight-line depreciation method (depreciation key LINR), what is the monthly depreciation posted to the General Ledger via transaction AFAB?",
         ["$2,000 / month", "$2,400 / month", "$1,800 / month", "$2,500 / month"], 0,
         "Calculation: Annual depreciation = $120,000 / 5 years = $24,000 per year. Monthly depreciation = $24,000 / 12 months = $2,000 per month.",
         "Monthly Depreciation = (Acquisition Cost - Salvage Value) / (Useful Years * 12)",
         "Debugging Logic", "Resolving Posting Period Closed Error in SAP (Transaction OB52)",
         "An accountant attempting to post a month-end adjustment entry on October 2nd receives error message 'Posting period 009 2026 is not open for variant 1000'. What is the correct functional procedure to resolve this?",
         ["The authorized finance lead must open posting period 9 for account type '+' or relevant sub-ledger in transaction OB52 (Open and Close Posting Periods).",
          "The user must change their computer's local operating system date back to September 30th.",
          "The database administrator must restart the SAP HANA database instance.",
          "The document must be permanently deleted and re-keyed next quarter."], 0,
         "Posting periods are governed by period control tables maintained in transaction OB52; authorized finance personnel must open period 9 for the target posting period variant to allow late adjustments."),

        (4, "client-conversation", "Explaining Year-End Retained Earnings Carryforward to a Client",
         "A client finance controller worries that their Balance Sheet retained earnings account did not automatically balance on the morning of January 1st after changing fiscal years.",
         "Explain the SAP Balance Carryforward program (transaction FAGLGVTR), how P&L accounts are zeroed into Retained Earnings, and how balance sheet accounts carry forward.",
         ["Balance Carryforward (FAGLGVTR)", "Retained Earnings Account (Key X)", "P&L vs Balance Sheet Closing"],
         "Accounting Reassurance (Demystify the automated closing technical run and instill complete audit confidence)",
         "You have to run a transaction in SAP to carry forward the balances, it doesn't happen automatically overnight.",
         "Too curt and lacks accounting detail regarding the difference between balance sheet and nominal P&L accounts.",
         "I completely understand your concern, but please be assured that your financial data is fully intact! In SAP, the fiscal year-end closing follows strict accounting standards: Balance Sheet accounts carry their cumulative closing balances forward into period 0 of the new fiscal year, whereas P&L accounts are nominal accounts that must be cleared to zero. Their net balance—the net profit or loss for the year—is transferred into your configured Retained Earnings account (Account Key X). This process is executed cleanly via the Balance Carryforward program (transaction FAGLGVTR). Running this program reconciles your opening balances and ensures your new year's Balance Sheet balances to the penny.",
         "Authoritative, reassuring, and articulates the exact accounting logic and transaction code required to resolve the inquiry.",
         "Remember: P&L accounts clear to zero into Retained Earnings; Balance Sheet balances roll into Period 0 via transaction FAGLGVTR.",
         "Percentages & Growth", "Withholding Tax (TDS) Deduction on Professional Services",
         "An enterprise in India processes a consulting fee invoice of ₹150,000 from a vendor. Under section 194J of the Income Tax Act, Tax Deducted at Source (TDS) applies at 10.0%. What is the net payment disbursed to the consultant and the TDS liability credited to the tax authority?",
         ["Net Payment: ₹135,000 | TDS Liability: ₹15,000", "Net Payment: ₹140,000 | TDS Liability: ₹10,000", "Net Payment: ₹130,000 | TDS Liability: ₹20,000", "Net Payment: ₹142,500 | TDS Liability: ₹7,500"], 0,
         "Calculation: TDS Deduction = ₹150,000 * 0.10 = ₹15,000. Net amount payable to vendor = ₹150,000 - ₹15,000 = ₹135,000. TDS payable to government = ₹15,000.",
         "Net Disbursed = Gross Invoice - (Gross Invoice * TDS Rate)",
         "Cause & Effect", "Impact of Field Status Variant Suppression in General Ledger Postings",
         "If the Field Status Group assigned to an expense GL account sets 'Cost Center' to 'Suppressed', what happens when a user attempts to post an expense to that account via transaction FB50?",
         ["The Cost Center input field will be completely invisible on the posting screen, preventing the user from entering a cost center and triggering a CO error if a cost object is required.",
          "The system will automatically assign the default cost center of the company code.",
          "The transaction will post successfully and charge the CEO's personal expense account.",
          "The SAP GUI will crash immediately."], 0,
         "Field Status settings (Suppressed, Required, Optional) dictate screen field visibility; suppressing a field hides it entirely, making it impossible to assign cost objects directly on that line."),

        (5, "problem-explanation", "Explaining Real-Time FI-SD Billing Integration to a Sales Manager",
         "A sales operations manager asks why shipping a sales order doesn't immediately generate revenue in the General Ledger, and wants to understand when revenue is officially recognized.",
         "Explain the Order-to-Cash (O2C) cycle: Post Goods Issue (PGI) recognizes Cost of Goods Sold and inventory reduction; Billing (VF01) recognizes Revenue and Customer Receivable.",
         ["Order-to-Cash (O2C)", "Post Goods Issue (PGI: Dr COGS / Cr Inventory)", "Billing Document (VF01: Dr Customer / Cr Revenue)"],
         "Process Clarity (Differentiate logistical goods movement from accounting revenue realization)",
         "Shipping goods doesn't make revenue because shipping is delivery. Revenue only happens when we make the invoice in VF01.",
         "Technically accurate but fails to explain the vital COGS inventory journal entry that occurs upon shipping.",
         "In SAP Order-to-Cash integration, there are two distinct accounting milestones: First, when the warehouse ships the product and performs Post Goods Issue (PGI via transaction VL02N), this represents a logistical transfer of ownership. Accounting recognizes the cost: Debit Cost of Goods Sold (COGS) and Credit Finished Goods Inventory. However, under accounting standards, Revenue is not realized until the Billing Document is created (transaction VF01). At that exact instant, SAP automatically generates the financial accounting document: Debit Customer Accounts Receivable and Credit Sales Revenue. This two-step process maintains strict compliance with the Matching Principle of accounting.",
         "Exceptional pedagogical clarity: cites exact transactions, outlines the journal entries at each milestone, and explains the Matching Principle.",
         "In SD-FI integration: PGI posts Dr COGS / Cr Inventory; Billing Document (VF01) posts Dr Customer AR / Cr Sales Revenue.",
         "Financial & Business Math", "Foreign Exchange Unrealized Gain/Loss Revaluation",
         "An enterprise records an open vendor liability of €100,000 when the exchange rate is $1.05 per Euro ($105,000 book value). At month-end closing, the spot exchange rate shifts to $1.08 per Euro ($108,000 revalued). What is the foreign exchange gain or loss posted to the P&L via foreign currency valuation (FAGL_FCV)?",
         ["$3,000 Unrealized Loss", "$3,000 Unrealized Gain", "$2,500 Unrealized Loss", "$2,000 Unrealized Gain"], 0,
         "Calculation: Original liability = €100,000 * 1.05 = $105,000. Month-end revalued liability = €100,000 * 1.08 = $108,000. Because it is a liability (money owed), an increase in local currency required to settle represents an expense/loss: $108,000 - $105,000 = $3,000 Unrealized FX Loss.",
         "FX Variance = Revalued Amount - Book Amount (Positive on liability = Loss)",
         "Decision Architecture", "Depreciation Method Selection for Tax vs Book Ledgers",
         "An enterprise running SAP S/4HANA maintains dual accounting ledgers: Leading Ledger (0L for local statutory tax using Written Down Value reducing balance) and Non-Leading Ledger (2L for IFRS corporate reporting using Straight Line). How does SAP Asset Accounting accommodate this?",
         ["By configuring separate Depreciation Areas linked to specific Ledger Groups (Area 01 to Ledger 0L with reducing balance key, and Area 30 to Ledger 2L with straight line key).",
          "By creating two completely separate physical machine records in the asset master database.",
          "By manually recalculating depreciation in Excel every month and posting journal vouchers.",
          "SAP cannot support two different depreciation methods simultaneously."], 0,
         "SAP Asset Accounting accommodates multi-GAAP accounting by mapping distinct Depreciation Areas to different Ledger Groups, allowing independent valuation and depreciation rules per accounting standard."),

        (6, "interview-question", "Demonstrating Automatic Payment Program (F110) Configuration Mastery",
         "The interviewer asks: 'Can you walk me through the core customizing parameters of the SAP Automatic Payment Program (transaction FBZP / F110)?'",
         "Articulate the six configuration pillars: All Company Codes, Paying Company Codes, Payment Methods in Country, Payment Methods in Company Code, Bank Determination, and House Banks.",
         ["Automatic Payment Program (F110)", "Customizing Transaction FBZP", "House Bank Determination"],
         "Systemic Customizing Mastery (Structure complex ERP configuration into clean, logical architecture pillars)",
         "You run F110 to pay vendors automatically. You configure it in FBZP with your company code, payment method, and house bank.",
         "Superficial and unstructured. Fails to demonstrate consultant-level configuration knowledge of the FBZP hierarchy.",
         "The Automatic Payment Program is configured through transaction FBZP across six structured pillars: 1. 'All Company Codes' sets intercompany payment relationships and sending/paying entities; 2. 'Paying Company Codes' defines minimum disbursement amounts and cash discount tolerances; 3. 'Payment Methods in Country' configures bank transfer/check formats and currency restrictions; 4. 'Payment Methods in Company Code' sets payment groupings and foreign currency rules; 5. 'Bank Determination' establishes the bank selection ranking order, available cash balances, and value dates; and 6. 'House Banks' links GL clearing accounts to EDI bank interfaces. During an F110 execution, the system runs through proposal, exception logging, and payment posting with automatic check/file generation.",
         "Consultant-grade masterclass: enumerates all six configuration pillars of FBZP in exact architectural order.",
         "Memorize the six pillars of FBZP: All Company Codes, Paying Company Codes, Methods in Country, Methods in Company Code, Bank Determination, House Banks.",
         "Data Interpretation & Metrics", "Accounts Receivable Days Sales Outstanding (DSO) Calculation",
         "A corporation has total outstanding Accounts Receivable of $4,500,000 at the end of Q3. Total credit sales over the 90-day quarter were $13,500,000. What is the company's Days Sales Outstanding (DSO)?",
         ["30 days", "25 days", "35 days", "40 days"], 0,
         "Calculation: Average daily credit sales = $13,500,000 / 90 days = $150,000 per day. DSO = Total AR / Average Daily Sales = $4,500,000 / $150,000 = 30 days.",
         "DSO = (Accounts Receivable / Total Credit Sales) * Period Days",
         "Constraint Solving", "Vendor Payment Block in Automatic Payment Program",
         "An accounts payable invoice is due for payment, but when the F110 payment proposal is executed, the invoice appears in the exception list with error 'Invoice blocked for payment (Block Code R)'. What is the cause and resolution?",
         ["The invoice was blocked automatically during MIRO verification due to a quantity or price variance; the authorized accounting lead must release the block in transaction MRBR.",
          "The vendor's bank account was permanently closed by the government.",
          "The company code has exceeded its credit limit.",
          "The invoice must be cancelled and re-created under a new document number."], 0,
         "Payment block 'R' indicates invoice verification variance blocks; invoices blocked during MIRO cannot be disbursed by F110 until released via transaction MRBR (Release Blocked Invoices)."),

        (7, "workplace-scenario", "Resolving Unreconciled Internal Order Costs During Period Closing",
         "During month-end close, a manufacturing plant controller discovers $140,000 in operational maintenance costs trapped in an Internal Order that failed to settle to the production cost center.",
         "Explain the Internal Order settlement rule configuration (transaction KO02 / KO88), allocation structures, and receiver cost centers.",
         ["Internal Order Settlement (KO88)", "Settlement Rule & Allocation Structure", "Cost Center Debit / Order Credit"],
         "Management Accounting Rigor (Diagnose cost object settlement failures and execute clean period allocations)",
         "The order didn't settle because someone forgot to run the settlement transaction. Just run KO88 and see if it works.",
         "Lacks functional diagnostic depth. Fails to verify whether the settlement rule, settlement profile, or valid receiver exists.",
         "When costs remain trapped in an Internal Order, it is typically caused by one of two issues: either a missing Settlement Rule in the order master data (transaction KO02), or an expired validity date on the receiver Cost Center. An Internal Order is a temporary cost collector; it cannot close the period with an open balance if it is configured for full settlement. I will check transaction KO02 to verify that the Settlement Profile maps the costs to an active receiver Cost Center with 100% distribution. Once verified, executing transaction KO88 will credit the Internal Order and debit the production Cost Center, clearing the variance before financial reporting.",
         "Exceptional management accounting troubleshooting: explains the role of temporary cost collectors, checks settlement profiles, and executes KO88.",
         "Internal Order closing protocol: Verify Settlement Rule in KO02 (receiver cost center and percentage), then execute settlement run in KO88.",
         "Financial & Business Math", "Cost Center Overhead Secondary Allocation Percentage",
         "A corporate IT service cost center incurs $240,000 in total monthly expenses. Under an assessment cycle (transaction KSU5), costs are allocated to three operating divisions based on employee headcounts: Division A (120 employees), Division B (80 employees), and Division C (40 employees). How much IT overhead cost is allocated to Division A?",
         ["$120,000", "$100,000", "$140,000", "$90,000"], 0,
         "Calculation: Total headcount = 120 + 80 + 40 = 240 employees. Division A share = 120 / 240 = 50.0%. Allocated cost = $240,000 * 0.50 = $120,000.",
         "Allocated Cost = Total Pool * (Segment Basis / Total Basis)",
         "Workflow Ordering", "SAP Cost Center Assessment Cycle Execution Flow",
         "Which sequence represents the correct configuration and execution steps for a monthly Controlling (CO) Assessment Cycle in SAP?",
         ["Define Secondary Cost Element (Category 42) -> Create Assessment Cycle (KSU1: Sender/Receiver Rules) -> Post Actual Costs to Sender -> Execute Assessment Run (KSU5) -> Verify Zero Sender Balance in Cost Center Report (S_ALR_87013611)",
          "Execute Assessment Run -> Define Cost Element -> Create Assessment Cycle -> Post Actual Costs",
          "Create Assessment Cycle -> Verify Zero Balance -> Post Actual Costs -> Define Cost Element",
          "Post Actual Costs -> Execute Assessment Run -> Define Secondary Cost Element -> Create Cycle"], 0,
         "Assessment cycles require secondary cost elements (Category 42), defining sender/receiver allocation rules in KSU1, posting primary costs, executing KSU5, and verifying zero net sender balance in standard reports."),

        (8, "technical-presentation", "Presenting SAP Fiori User Experience Transformation to Finance Leadership",
         "Presenting the business case for replacing legacy SAP GUI 't-codes' (FB50, F-02, F110) with SAP Fiori launchpad role-based apps to the corporate Controller.",
         "Contrast cumbersome transactional menus with personalized, role-based, responsive Fiori apps, highlighting embedded real-time analytics and mobile approvals.",
         ["SAP Fiori Launchpad", "Role-Based Apps vs T-Codes", "Embedded Real-Time Analytics"],
         "Digital Transformation Value (Showcase user productivity gains, error reduction, and executive mobile approvals)",
         "Fiori looks much nicer and modern than the old gray SAP GUI screens and runs in Google Chrome.",
         "Shallow cosmetic comparison. Misses the architectural shift from monolithic transactions to role-based analytical apps.",
         "SAP Fiori is not merely a modern visual skin; it represents a fundamental paradigm shift in enterprise productivity. Legacy SAP GUI forced finance users to memorize hundreds of cryptic transaction codes (like F-02 or FAGLL03) and navigate overwhelming screens with 80 unneeded fields. Fiori introduces role-based, contextual applications that surface only what a specific user needs—such as the 'Manage Journal Entries' or 'Verify General Ledger Entries' apps. Crucially, Fiori embeds real-time analytics directly into the workflow: an accounts payable clerk sees dynamic KPI tiles showing overdue invoices without running a single manual report, while executives can approve $500,000 payments securely from mobile tablets.",
         "Inspiring, modern executive presentation: focuses on cognitive load reduction, role-based filtering, and embedded live KPI tiles.",
         "When presenting Fiori: emphasize role-based simplicity, embedded operational analytics, and mobile approval agility over mere cosmetic upgrades.",
         "Percentages & Growth", "Asset Salvage Value and Declining Balance Depreciation",
         "A logistics warehouse purchases delivery trucks for €200,000. Under the double declining balance method at a 20% annual rate, what is the depreciation expense recorded in Year 1, and the remaining net book value at the start of Year 2?",
         ["Year 1 Depreciation: €40,000 | Book Value: €160,000", "Year 1 Depreciation: €50,000 | Book Value: €150,000", "Year 1 Depreciation: €35,000 | Book Value: €165,000", "Year 1 Depreciation: €45,000 | Book Value: €155,000"], 0,
         "Calculation: Year 1 Depreciation = €200,000 * 0.20 = €40,000. Remaining Net Book Value = €200,000 - €40,000 = €160,000.",
         "Depreciation = Book Value * Rate; New Book Value = Book Value - Depreciation",
         "Process Flow", "Asset Capitalization from CWIP (Capital Work in Progress)",
         "When a major factory construction project is completed, what is the mandatory SAP Asset Accounting workflow to transfer costs from CWIP (Asset Class 4000) to the Final Fixed Asset?",
         ["Create Final Asset Master (AS01) -> Execute Asset Transfer / Settlement (ABUMN / AIAB & AIBU: Dr Fixed Asset / Cr CWIP) -> Begin Depreciation Run in Month of In-Service Date",
          "Delete the CWIP asset and re-invoice the contractors under a different company code",
          "Change the asset class directly in table ANLA using database scripts",
          "Begin depreciation immediately on the CWIP asset while construction is ongoing"], 0,
         "Capital Work in Progress cannot be depreciated while under construction; upon commissioning, an asset master is created and settlement is executed via AIAB/AIBU or ABUMN to transfer costs to the depreciable fixed asset."),

        (9, "manager-conversation", "Addressing Month-End Financial Close Delays with the Finance Director",
         "The Finance Director is frustrated that the global financial month-end close currently takes 9 business days, causing leadership reporting deadlines to be missed.",
         "Diagnose the closing bottlenecks (manual spreadsheet reconciliations, delayed intercompany billing, uncoordinated batch jobs) and present a Fast Close optimization plan using SAP Financial Closing Cockpit.",
         ["SAP Financial Closing Cockpit", "Fast Close Strategy", "Intercompany Reconciliation Automation"],
         "Operational Excellence & Leadership (Transform an uncoordinated manual closing schedule into an automated orchestration)",
         "The closing takes 9 days because subsidiaries are slow at entering their journal vouchers and don't care about deadlines.",
         "Blames subsidiaries, lacks strategic insight, and fails to offer technical workflow solutions.",
         "I share your urgency to compress our 9-day close down to our 4-day target. Our diagnostic reveals three primary bottlenecks: 1. Unsynchronized intercompany cut-offs leading to 48 hours of manual reconciliation emails; 2. Manual execution of sequential month-end batch jobs (foreign currency revaluation, asset depreciation, assessment cycles); and 3. Late GR/IR clearing. I propose implementing the SAP Financial Closing Cockpit: it provides an automated, centralized schedule of closing tasks with explicit dependency triggers and automated background execution. By standardizing our intercompany matching cut-offs on Day -1 and automating batch sequences, we can eliminate 4 full days of manual lag within two closing cycles.",
         "High-impact management consulting: identifies specific technical bottlenecks and proposes the SAP Financial Closing Cockpit to achieve a 4-day close.",
         "For financial close acceleration: advocate the SAP Financial Closing Cockpit, automated task dependencies, and standardized intercompany cut-offs.",
         "Financial & Business Math", "Dunning Interest and Late Payment Surcharges Calculation",
         "A customer with an overdue accounts receivable balance of $60,000 is 45 days late. The enterprise executes a level-3 dunning run (transaction F150) that applies an annual overdue penalty interest rate of 12.0% calculated on a 360-day commercial basis. How much penalty interest is billed to the customer?",
         ["$900.00", "$750.00", "$1,050.00", "$800.00"], 0,
         "Calculation: Annual interest = $60,000 * 0.12 = $7,200. Daily interest = $7,200 / 360 days = $20.00/day. Interest for 45 days = $20.00 * 45 = $900.00.",
         "Dunning Interest = Principal * Annual Rate * (Overdue Days / 360)",
         "Debugging Logic", "Resolving Account Assignment Errors in Automatic Account Determination (OBYC)",
         "During goods receipt posting (transaction MIGO), the transaction fails with error 'Account determination for entry 1000 WRX not possible'. What is the root cause?",
         ["Transaction key WRX (GR/IR clearing account) lacks a mapped General Ledger account for valuation grouping code and valuation class in customizing table OBYC.",
          "The warehouse worker entered an invalid storage bin number.",
          "The purchasing vendor has not signed the vendor master agreement.",
          "The company code has run out of sequential document numbers."], 0,
         "In MM-FI integration, transaction OBYC governs automatic account determination; error WRX indicates that the GR/IR clearing account assignment is missing for the specified valuation class."),

        (10, "email-response", "Writing a Professional Response to External Auditors on Journal Voucher Controls",
         "External financial auditors email demanding an explanation of compensating controls regarding manual journal vouchers posted via transaction FB50 without secondary workflow approval.",
         "Draft a formal, audit-compliant response detailing SAP Dual-Control principles (Park and Post via FV50/FBV0), user authorization segregation, and automated change logs.",
         ["Dual-Control Principle (Park & Post)", "Segregation of Duties (SoD)", "SAP Workflow Approval & Change Logs"],
         "Audit Defense Rigor (Demonstrate ironclad internal financial controls and complete audit trail defensibility)",
         "Dear Auditors, our accountants are trustworthy so they post FB50 directly. We check things at the end of the year.",
         "Devastating audit red flag. Concedes a complete failure of internal controls and segregation of duties.",
         "Dear Audit Team,\n\nThank you for your inquiry regarding our General Ledger posting governance. We enforce strict Segregation of Duties (SoD) and automated Dual-Control principles for all manual financial adjustments:\n\n1. Segregation of Authorization: Floor accountants are provisioned with transaction FV50 (Park Document) only, allowing them to draft and park journal entries but legally prohibiting them from posting to the General Ledger.\n2. Automated Workflow Approval: Parked documents automatically route to certified Finance Managers via workflow. Posting authority (transaction FBV0) is restricted exclusively to managers who did not create the entry.\n3. Audit Trail & Logging: Every change, line-item edit, and posting timestamp is permanently recorded in tables BKPF and CDHDR with complete user attribution.\n4. Post-Posting Sampling: Our internal audit unit reviews monthly automated exception reports of all direct entries exceeding $50,000.\n\nWe have attached the SAP authorization role matrices for your review.\n\nSincerely,\nGlobal Financial Systems Controller",
         "Masterful formal audit response: outlines exact transactions (FV50 vs FBV0), proves Segregation of Duties, and cites permanent system logging.",
         "Audit control rule: Always cite the Dual-Control Principle: Preparer parks (FV50), Approver reviews and posts (FBV0).",
         "Profit, Margin & ROI", "Profit Center Return on Investment (ROI) Metric",
         "A strategic business unit (Profit Center 2000) records an operating net profit of $450,000 for the fiscal year. The total capital invested (average operating asset base) allocated to this Profit Center is $3,000,000. What is the Profit Center's Return on Investment (ROI)?",
         ["15.0%", "12.5%", "18.0%", "14.0%"], 0,
         "Calculation: ROI = (Operating Profit / Invested Capital) * 100% = ($450,000 / $3,000,000) * 100% = 0.15 * 100% = 15.0%.",
         "ROI (%) = (Operating Profit / Capital Base) * 100",
         "Workflow Ordering", "SAP New GL Financial Statement Version (FSV) Creation Flow",
         "What is the correct sequential procedure for configuring a customized Financial Statement Version (FSV) in SAP?",
         ["Create FSV Header (OB58: Assign Chart of Accounts & Language) -> Define Balance Sheet & P&L Node Hierarchy -> Assign General Ledger Accounts to Nodes -> Specify Debit/Credit Shift Rules -> Generate Financial Reports (F.01)",
          "Generate Reports -> Assign Accounts -> Define Hierarchy -> Create Header",
          "Assign Accounts -> Generate Reports -> Specify Debit Shift -> Define Hierarchy",
          "Create Header -> Generate Reports -> Assign GL Accounts -> Define Node Hierarchy"], 0,
         "Financial Statement Versions (FSV) require setting up the header in OB58, building the structural node hierarchy (Assets, Liabilities, Revenue, Expenses), assigning accounts, defining debit/credit shifts, and verifying in report F.01."),

        (11, "conflict-resolution", "Mediation Between Materials Management and Finance on Physical Inventory Write-Offs",
         "The Warehouse Logistics Manager and the Plant Controller clash over a $280,000 physical inventory cycle count deficit: Logistics wants to adjust stock without financial write-offs, while Finance insists on booking the loss immediately.",
         "Mediate the dispute using SAP standard physical inventory valuation procedures (transaction MI07), inventory reserve accounts, and joint root-cause investigation.",
         ["Physical Inventory Difference Posting (MI07)", "Dr Inventory Variance / Cr Stock", "Audit Inventory Reserve"],
         "Cross-Functional Governance (Enforce financial statutory integrity while partnering with logistics on root-cause remediation)",
         "Logistics just has to accept the loss and finance should post the write-off immediately without any questions.",
         "Aggressive and uncollaborative. Creates organizational friction without resolving the underlying physical stock leakage.",
         "Both departments have critical, non-negotiable responsibilities: Finance is legally mandated under corporate governance to ensure the Balance Sheet reflects physically verified assets—holding $280,000 in phantom stock on the books constitutes statutory misrepresentation. However, Logistics is right that blindly posting a lump-sum adjustment obscures operational theft or scanning flaws. I propose a structured joint resolution: We execute transaction MI07 to post the inventory difference to our established Inventory Loss Reserve account, maintaining audit compliance. Simultaneously, we launch a joint 5-day deep dive across the top 10 variance SKUs to audit PO receiving scans, bill-of-materials consumption, and scrap logs. This protects financial integrity while giving operations the granular data to eliminate inventory leakage.",
         "Brilliant mediation: protects financial compliance, utilizes reserve accounts, and establishes a constructive operational investigation.",
         "Balance Sheet integrity is non-negotiable: inventory counts must be posted via MI07, but partner with logistics to audit shrinkage root causes.",
         "Financial & Business Math", "Cash Flow Operating Working Capital Variation",
         "Over a financial quarter, an enterprise's Accounts Receivable increases by $500,000, Inventory increases by $300,000, and Accounts Payable increases by $400,000. What is the net impact of these operational changes on the company's operating cash flow?",
         ["-$400,000 (Cash Outflow)", "-$600,000 (Cash Outflow)", "+$200,000 (Cash Inflow)", "+$400,000 (Cash Inflow)"], 0,
         "Calculation: Working capital cash impact = - Change in AR (-$500,000) - Change in Inventory (-$300,000) + Change in AP (+$400,000) = -$800,000 + $400,000 = -$400,000 net cash outflow.",
         "Cash Impact = - Delta AR - Delta Inventory + Delta AP",
         "Deductive Analysis", "Identifying Recurring Journal Entry Reversal Mechanics",
         "A finance team posts an accrual entry of $50,000 for unbilled utility expenses on September 30th using document type SA. What is the mandatory next-period procedure to prevent double-counting expenses when the actual utility invoice arrives in October?",
         ["Post an automated reversing entry on October 1st (transaction F.81 / FBS1 with reversal reason 01) to clear the accrual back to the P&L.",
          "Delete the original September 30th accounting document from the database.",
          "Ignore the accrual and deduct the expense from the vendor's bank account directly.",
          "Wait until the end of the year and adjust retained earnings."], 0,
         "Accrual entries must be reversed at the start of the following period (F.81) so that when the actual vendor invoice is processed, expenses are not duplicated in the General Ledger."),

        (12, "hr-question", "Answering: 'Describe a Challenging S/4HANA Finance Migration You Led'",
         "An enterprise executive interviewer asks: 'Tell me about a complex SAP S/4HANA migration challenge you faced, how you reconciled legacy data, and what you delivered.'",
         "Utilize the STAR framework (Situation, Task, Action, Result) showcasing ECC to S/4HANA data migration, Universal Journal cutover checks, and minimal business disruption.",
         ["STAR Framework", "ECC to S/4HANA Migration", "Pre-Migration Checks & Blackline Reconciliation"],
         "Executive Technical Leadership (Demonstrate mastery of pre-migration integrity, cutover execution, and zero post-go-live accounting errors)",
         "I was on a project where we migrated from ECC to S/4HANA. We ran the migration scripts and it went well with very few errors.",
         "Vague, passive, and reveals no personal ownership, technical depth, or strategic problem-solving.",
         "In my previous implementation, I led the finance workstream migrating a global manufacturing enterprise with 8 Company Codes from ECC 6.0 to S/4HANA 2022. The most critical challenge was reconciling 12 years of historical asset accounting and profit center data that contained unposted depreciation runs and orphaned cost objects. I instituted a rigorous pre-migration data cleansing protocol: executing transaction FIN_CORR_MIG to resolve legacy document inconsistencies before the migration. During cutover weekend, we migrated over 14 million line items into the Universal Journal (ACDOCA) using the SAP S/4HANA Migration Cockpit. We achieved 100% trial balance reconciliation across all 8 entities within our 36-hour downtime window, achieving Day 1 financial go-live with zero operational disruption.",
         "Sensational interview answer: cites specific migration tools (FIN_CORR_MIG, Migration Cockpit), quantifies volume (14M items, 8 codes), and demonstrates executive poise.",
         "In migration interview answers: highlight pre-migration data cleansing, trial balance reconciliation rigor, and zero business interruption.",
         "Combinatorics & Permutations", "SAP Financial Authorization Role Matrix Permutations",
         "A security architect configures authorization roles for 4 distinct Company Codes. Each company code has 3 possible posting authorization levels (Display Only, Park Document, Full Post) and 2 possible sub-ledger scopes (AP or AR). How many unique security authorization profiles are required to cover all combinations?",
         ["24 profiles", "18 profiles", "32 profiles", "12 profiles"], 0,
         "Calculation: Total profiles = 4 Company Codes * 3 Authorization Levels * 2 Sub-ledgers = 24 unique security profiles.",
         "Total Profiles = N1 * N2 * N3",
         "Constraint Solving", "Bank Account Reconciliation Matching Constraints",
         "During electronic bank statement (EBS) processing in transaction FF_5, an incoming customer bank payment of $12,450 cannot be automatically cleared against open customer invoices. What is the primary cause?",
         ["The payment reference or invoice number in the bank statement note to payee does not match the open item assignment number or payment tolerance threshold in SAP.",
          "The customer's bank has been acquired by a competitor.",
          "The electronic bank statement file format must always be entered manually by an accountant.",
          "The company code has disabled all customer collections."], 0,
         "EBS automated clearing algorithms rely on search strings matching the invoice number or assignment field in the bank statement interpretation algorithm; mismatched references route items to post-processing (FEBAN)."),

        (13, "interview-question", "Explaining Parallel Accounting and Ledger Approach in SAP S/4HANA",
         "The interviewer asks: 'How does SAP S/4HANA handle parallel accounting for multinational enterprises requiring both Local GAAP and IFRS reporting?'",
         "Explain the Ledger Approach (Leading Ledger 0L for Group IFRS vs Non-Leading Ledgers like 2L for Local GAAP), parallel currencies, and independent closing postings.",
         ["Leading Ledger (0L)", "Non-Leading Ledger (Parallel GAAP)", "Multi-Currency Architecture"],
         "Global Accounting Architecture (Explain how parallel ledgers eliminate the need for cumbersome parallel accounts)",
         "We create two ledgers, 0L for IFRS and another ledger for local tax, and post entries to both.",
         "Too brief and omits crucial concepts like Leading Ledger universality, parallel currencies, and ledger-specific manual adjustments.",
         "In modern SAP S/4HANA, parallel accounting is elegantly handled via the Ledger Approach rather than the outdated Accounts Approach. We designate Ledger 0L as the Leading Ledger, which is populated across all Company Codes and holds group reporting standards (such as IFRS or US GAAP) and corporate currencies. Concurrently, we create Non-Leading Ledgers (such as 2L) assigned to specific company codes to represent Local Statutory GAAP. Transactions that comply with both standards post simultaneously to all ledgers. However, for standards-divergent valuations—such as different asset depreciation rules or pension provisions—postings are directed specifically to a single Ledger Group. This provides instant, compliant standalone balance sheets for each accounting standard without reconciliation.",
         "Brilliant demonstration of global ERP design: clearly contrasts Leading vs Non-Leading ledgers and explains ledger-specific closing entries.",
         "Always explain: Leading Ledger 0L is universal (IFRS/Group); Non-Leading Ledgers handle Local GAAP divergence via Ledger Groups.",
         "Averages & Distributions", "Average Payment Days and Vendor Performance Score",
         "Over five major vendor disbursements, the Treasury team logs payment turnaround times of 24 days, 28 days, 35 days, 31 days, and 27 days. What is the average payment turnaround duration across these disbursements?",
         ["29.0 days", "28.5 days", "30.0 days", "27.5 days"], 0,
         "Calculation: Total turnaround days = 24 + 28 + 35 + 31 + 27 = 145 days. Average = 145 / 5 = 29.0 days.",
         "Average Days = Sum of Days / Total Disbursements",
         "Debugging Logic", "Resolving Document Splitting Characteristic Inconsistencies",
         "A user posting an intercompany journal entry encounters error 'Document splitting: Characteristic Segment not found'. What is the customizing diagnosis?",
         ["The Segment derivation logic from Profit Center is unpopulated, or the Segment field is mandatory in Document Splitting without an active default derivation rule.",
          "The user must change their SAP user interface language to German.",
          "The company code has been deleted from customizing table T001.",
          "The segment report was blocked by a network firewall."], 0,
         "Document splitting enforces balancing characteristics (Segment, Profit Center); if a segment cannot be derived automatically from the assigned profit center, posting is rejected to preserve segment balance integrity."),

        (14, "workplace-scenario", "Managing Master Data Governance (MDG) for Vendor & Customer Accounts",
         "A procurement team wants to create vendor master records directly in production without centralized tax registration checks, resulting in duplicate vendors and fraudulent banking edits.",
         "Articulate SAP Master Data Governance (MDG), Business Partner (BP) approach in S/4HANA, and mandatory bank change approval workflows.",
         ["SAP Business Partner (Transaction BP)", "Master Data Governance (MDG)", "Dual-Control Bank Detail Changes"],
         "Governance & Fraud Prevention (Shield the enterprise from payment diversion fraud through strict master data controls)",
         "Procurement shouldn't create vendors because they will mess up the accounting keys. Only finance can create vendors.",
         "Territorial and unconstructive. Fails to explain the SAP S/4HANA Business Partner model or modern governance workflows.",
         "Allowing decentralized, unvetted vendor creation in production exposes the enterprise to severe audit failures and payment diversion fraud. In S/4HANA, all vendors and customers are unified under the central Business Partner (BP) model. I propose routing all vendor creation and bank detail modifications through a centralized SAP Master Data Governance (MDG) workflow: 1. Tax identification and corporate registration numbers are validated automatically against government registries to eliminate duplicates; 2. Role-based approvals ensure procurement verifies commercial terms while finance validates payment methods and GL reconciliation accounts; and 3. Any change to vendor banking details requires dual-control verification with mandatory vendor telephone confirmation before payment release.",
         "Authoritative, high-governance solution: leverages S/4HANA BP model, automated tax validation, and fraud-proof dual control.",
         "In S/4HANA, master data is unified under the Business Partner (BP) concept; enforce dual-control verification for all bank detail modifications.",
         "Percentages & Growth", "Foreign Exchange Revaluation Rate Movement Percentage",
         "A company records a Japanese Yen (JPY) payable of ¥10,000,000 when the exchange rate is 150 JPY per 1 USD ($66,667 USD equivalent). At month-end revaluation, the exchange rate strengthens to 140 JPY per 1 USD ($71,429 USD equivalent). By what percentage did the USD value of the liability increase?",
         ["7.14% increase", "6.67% increase", "8.25% increase", "5.50% increase"], 0,
         "Calculation: Old value = 10,000,000 / 150 = $66,666.67. New value = 10,000,000 / 140 = $71,428.57. Value increase = $71,428.57 - $66,666.67 = $4,761.90. Percentage increase = ($4,761.90 / $66,666.67) * 100% = 7.1428... or 7.14%.",
         "Percentage Change (%) = ((New USD - Old USD) / Old USD) * 100",
         "Workflow Ordering", "S/4HANA Central Finance (CFIN) Data Replication Flow",
         "What is the correct sequential architecture for replicating financial postings from legacy non-SAP ERPs into S/4HANA Central Finance?",
         ["Source Transaction Post -> Landscape Transformation (SLT) Trigger Capture -> Application Interface Framework (AIF) Error Handling -> Central Finance (CFIN) Mapping -> Universal Journal (ACDOCA) Document Generation",
          "Universal Journal -> Source Transaction -> SLT -> AIF -> Central Finance",
          "AIF -> Universal Journal -> Source Post -> SLT -> Mapping",
          "Central Finance -> Source Transaction -> Universal Journal -> AIF -> SLT"], 0,
         "Central Finance replication captures source transactions via SAP Landscape Transformation (SLT), maps master data and handles errors via AIF, and posts balanced entries directly into the S/4HANA Universal Journal (ACDOCA)."),

        (15, "technical-explanation", "Explaining Clearing Accounts vs Reconciliation Accounts in SAP",
         "A junior consultant confuses the difference between a sub-ledger Reconciliation Account and a balance sheet Clearing Account.",
         "Explain the distinction: Reconciliation Accounts (e.g., Accounts Payable) are non-directly postable GL accounts that mirror sub-ledgers; Clearing Accounts (e.g., GR/IR, Bank In-transit) are temporary transit accounts that balance to zero.",
         ["Reconciliation Accounts (Sub-ledger Mirror)", "Clearing Accounts (Zero-Balance Transit)", "Direct Posting Prohibitions"],
         "Foundational Clarity (Differentiate permanent sub-ledger summary control from temporary operational transit buckets)",
         "Reconciliation accounts are for vendors and customers. Clearing accounts are for everything else in between.",
         "Too simplistic and technically incomplete. Misses the vital operational rules governing direct postings and clearing status.",
         "This is one of the most essential concepts in SAP finance! A Reconciliation Account acts as a real-time summary mirror of a sub-ledger (such as Accounts Payable or Accounts Receivable). You can never post directly to a reconciliation account in transaction FB50; instead, every time you post to an individual Vendor or Customer master record, SAP automatically updates the underlying Reconciliation Account in the General Ledger simultaneously. Conversely, a Clearing Account (such as the GR/IR account or Bank In-transit account) is a temporary operational holding bucket where two offsetting business events occur at different times. The balance represents timing differences, and when both events complete, the items are cleared against each other to zero.",
         "Exceptional pedagogical clarity: contrasts sub-ledger automation with temporal offset holding buckets.",
         "Remember: Reconciliation accounts mirror sub-ledgers and prohibit direct postings; Clearing accounts hold temporary timing offsets until cleared to zero.",
         "Financial & Business Math", "Intercompany Cross-Border Transfer Pricing Markup",
         "A parent manufacturing Company Code in Germany produces specialized industrial sensors at a standard cost of €800 per unit. Under the corporate Transfer Pricing policy, goods are sold to an Indian sales subsidiary with a mandatory arm's-length cost-plus markup of 25.0%. What is the intercompany billing transfer price per sensor?",
         ["€1,000", "€1,050", "€950", "€1,100"], 0,
         "Calculation: Transfer Price = Base Standard Cost * (1 + Transfer Markup) = €800 * (1 + 0.25) = €800 * 1.25 = €1,000 per unit.",
         "Transfer Price = Standard Cost * (1 + Cost-Plus Markup Rate)",
         "Debugging Logic", "Resolving Unbalanced Cross-Company Code Transaction Errors",
         "When posting an intercompany transaction across Company Code 1000 and Company Code 2000, the posting errors with 'Intercompany clearing accounts not maintained for transaction 1000/2000'. What is the customizing fix?",
         ["Define the intercompany receivable and payable clearing accounts in transaction OBYA for both company code combinations.",
          "Merge Company Code 1000 and 2000 into a single entity in transaction OX02.",
          "Suppress the company code field in field status variant 0001.",
          "Post the transaction in Controlling (CO) instead of Financial Accounting (FI)."], 0,
         "Cross-company code transactions generate automated offset entries to keep each legal entity's balance sheet balanced; transaction OBYA must configure the respective intercompany receivable and payable clearing accounts."),
    ]

    for s in foundations:
        days.append({
            "day": s[0],
            "commType": s[1],
            "commTitle": s[2],
            "commScenario": s[3],
            "commPrompt": s[4],
            "commVocab": s[5],
            "commRule": s[6],
            "commWeakResponse": s[7],
            "commWeakCritique": s[8],
            "commStrongResponse": s[9],
            "commStrongCritique": s[10],
            "commCoachTip": s[11],
            "aptTopic": s[12],
            "aptTitle": s[13],
            "aptQuestion": s[14],
            "aptOptions": s[15],
            "aptAnswer": s[16],
            "aptExplanation": s[17],
            "aptFormula": s[18],
            "logicType": s[19],
            "logicTitle": s[20],
            "logicQuestion": s[21],
            "logicOptions": s[22],
            "logicAnswer": s[23],
            "logicExplanation": s[24],
        })

    # Systematic phase topics for Days 16 to 89
    phase_definitions = [
        # Phase 2: Days 16-30 (General Ledger FI-GL Deep Dive)
        (16, 30, "General Ledger FI-GL", [
            ("Document Types (SA, KR, KZ, DR, DZ) and Number Ranges", "FI-GL Architecture", "Configuring document header validation and yearly sequential number intervals.", ["Document Types", "Number Range Intervals"]),
            ("Posting Keys (01, 15, 40, 50) and Debit/Credit Line Controls", "Posting Mechanics", "Understanding how 2-digit posting keys dictate debit/credit and account type.", ["Posting Keys", "Account Type Classification"]),
            ("Field Status Variants and Groups: Field Suppression & Rules", "Data Entry Governance", "Configuring screen field rules to enforce mandatory business segment entry.", ["Field Status Variant", "Field Status Group"]),
            ("New GL Document Splitting: Zero-Balance Segment Rules", "Segment Accounting", "Enforcing zero-balance clearing accounts for segment and profit center balance sheets.", ["Zero-Balance Clearing", "Segment Splitting Rules"]),
            ("Financial Statement Versions (FSV) and Balance Sheet Grouping", "Financial Reporting", "Mapping GL account ranges to standardized statutory financial statement nodes.", ["Financial Statement Version", "Balance Sheet Structure"]),
            ("Accrual Engine in S/4HANA: Automated Deferrals and Accruals", "Period Accounting", "Automating monthly recurring expense recognition without manual reversal entries.", ["Accrual Engine", "Linear Accrual Schedule"]),
            ("Ledger Approach: Leading Ledger 0L and Non-Leading Ledgers", "Multi-GAAP Accounting", "Managing divergent statutory accounting principles within a unified database.", ["Leading Ledger 0L", "Non-Leading Ledger"]),
            ("Currencies in S/4HANA: Functional, Group, and Hard Currencies", "Multi-Currency Architecture", "Configuring Company Code Currency, Group Currency, and Freely Defined Currencies.", ["Functional Currency", "Group Currency (ACDOCA)"]),
            ("Foreign Currency Valuation (FAGL_FCV) and Delta Postings", "Treasury & FX", "Executing month-end balance sheet revaluation using current spot exchange rates.", ["Foreign Currency Valuation", "Delta Revaluation Method"]),
            ("General Ledger Open Item Management and Manual Clearing (F-03)", "GL Reconciliation", "Clearing offsetting debit and credit items on transit clearing accounts.", ["Open Item Management", "Manual Clearing (F-03)"]),
            ("Automated Clearing Program (F.13) Selection Criteria", "Clearing Automation", "Configuring matching criteria (assignment, reference) for automated clearing.", ["Automated Clearing (F.13)", "Matching Criteria"]),
            ("Parking vs Holding vs Posting Documents in SAP", "Posting Workflow", "Differentiating incomplete held documents from workflow-enabled parked vouchers.", ["Park Document (FV50)", "Hold Document"]),
            ("Validation and Substitution Rules in Financial Accounting (GGB0 / GGB1)", "Data Quality Rules", "Enforcing business constraints and automatic field population at document save.", ["Validation Rule (GGB0)", "Substitution Rule (GGB1)"]),
            ("Chart of Accounts Architecture: Operational, Group, and Country CoA", "CoA Design", "Structuring multi-tier Charts of Accounts for global multinational enterprises.", ["Operational CoA", "Alternative / Country CoA"]),
            ("Phase 2 Placement Milestone: General Ledger Design Review", "Architecture Defense", "Defending S/4HANA General Ledger architecture and Document Splitting to Controller.", ["General Ledger Blueprint", "Segment Balance Defensibility"]),
        ]),

        # Phase 3: Days 31-45 (Accounts Payable & Accounts Receivable FI-AP/AR)
        (31, 45, "FI-AP & FI-AR", [
            ("Business Partner (BP) Customer and Vendor Roles and Groupings", "Master Data Architecture", "Configuring Business Partner groupings, number ranges, and FI roles.", ["Business Partner Roles", "BP Number Groupings"]),
            ("Reconciliation Accounts for Vendors and Customers", "Sub-ledger Integration", "Connecting sub-ledger postings to balance sheet summary control accounts.", ["AP/AR Reconciliation Account", "Direct Posting Lock"]),
            ("Payment Terms (OBB8) and Multi-Tier Cash Discount Calculations", "Working Capital Terms", "Configuring baseline dates, discount percentages, and net due periods.", ["Payment Terms (OBB8)", "Baseline Date Rules"]),
            ("Automatic Payment Program (F110): Proposal and Edit Runs", "Payment Operations", "Executing disbursement proposals, reviewing exception lists, and processing runs.", ["F110 Payment Proposal", "Disbursement Exception Log"]),
            ("House Banks, Bank Accounts, and Bank Sub-Accounts in FI", "Treasury Architecture", "Configuring clearing sub-accounts to reconcile payments against statements.", ["House Bank (FI12)", "Bank Sub-Accounts"]),
            ("Dunning Program (F150): Dunning Levels, Grace Periods, and Letters", "Collections Operations", "Executing multi-level automated dunning notices and calculating penalty interest.", ["Dunning Procedure (F150)", "Dunning Grace Periods"]),
            ("Customer Credit Management (FSCM) and Exposure Limits", "Credit Governance", "Setting automated credit limits, risk categories, and sales order delivery blocks.", ["FSCM Credit Management", "Credit Exposure Monitoring"]),
            ("Down Payment Processing: Down Payment Requests (F-47) and Postings (F-48)", "Special GL Transactions", "Processing vendor advance deposits using Special GL indicators without invoice mismatch.", ["Special GL Indicator (A)", "Down Payment Clearing"]),
            ("Vendor Invoice Verification (MIRO) and Price/Quantity Variances", "MM-FI Invoice Matching", "Reconciling vendor invoices against purchase orders and goods receipts in 3-way match.", ["3-Way Match Verification", "Quantity / Price Variance"]),
            ("Credit Memo Processing and Netting in Accounts Payable", "AP Adjustments", "Applying credit memos against open vendor invoices to reduce disbursement cash.", ["Credit Memo (FB65)", "Vendor Netting"]),
            ("Customer Invoice Processing and Revenue Recognition Links", "SD-FI Integration", "Verifying accounting document creation upon billing document release in VF02.", ["Billing Release to Accounting", "Customer Open Items"]),
            ("Electronic Bank Statement (EBS) MT940 / CAMT.053 Ingestion", "Bank Reconciliation", "Automating bank statement ingestion and automatic customer invoice clearing.", ["MT940 / CAMT Formats", "Interpretation Algorithm"]),
            ("Managing Post-Dated Checks (PDC) and Bill of Exchange", "Special Transactions", "Recording and discounting post-dated customer instruments in emerging markets.", ["Post-Dated Checks", "Bill of Exchange Liability"]),
            ("Year-End 1099 Vendor Tax Reporting in SAP Accounts Payable", "Tax Compliance", "Configuring 1099 withholding tax boxes and generating annual vendor tax returns.", ["1099 Vendor Reporting", "Withholding Tax Codes"]),
            ("Phase 3 Placement Milestone: Sub-Ledger AP/AR Audit Defense", "Audit Defense", "Defending sub-ledger reconciliation, payment controls, and dunning workflows.", ["Sub-Ledger Integrity", "Internal Payment Controls"]),
        ]),

        # Phase 4: Days 46-60 (Asset Accounting FI-AA Deep Dive)
        (46, 60, "Asset Accounting FI-AA", [
            ("Asset Classes and Chart of Depreciation Configuration", "Asset Architecture", "Configuring Asset Classes, Account Determination, and depreciation areas.", ["Chart of Depreciation", "Asset Class Master"]),
            ("Depreciation Keys, Calculation Methods, and Base Methods", "Depreciation Valuation", "Configuring straight-line, declining balance, and units-of-production keys.", ["Depreciation Key", "Base Calculation Method"]),
            ("Capital Work in Progress (CWIP) and Settlement to Fixed Assets", "Capital Projects", "Collecting construction costs and executing settlement runs (AIAB / AIBU).", ["CWIP Asset Class", "Settlement Rule Allocation"]),
            ("Asset Acquisition from Vendor (F-90) vs Logistics PO Ingestion", "Asset Capitalization", "Comparing direct financial capitalization with PO-based goods receipt assets.", ["Asset Acquisition (F-90)", "Logistics Asset Integration"]),
            ("Asset Retirement with Revenue: Customer Sale vs Scrapping", "Asset Disposal", "Recording asset disposal gain/loss under scrapping (ABAVN) vs sale (F-92).", ["Asset Scrapping (ABAVN)", "Retirement Gain/Loss"]),
            ("Intercompany and Intra-Company Asset Transfers (ABUMN / ABT1N)", "Asset Relocation", "Transferring asset cost and accumulated depreciation between plants or entities.", ["Asset Transfer (ABT1N)", "Accumulated Depreciation Transfer"]),
            ("Asset Impairment Accounting (IAS 36 / US GAAP)", "Impairment Valuation", "Posting unplanned depreciation (ABAA) to write down impaired asset carrying value.", ["Unplanned Depreciation", "Impairment Carrying Value"]),
            ("Asset Revaluation and Periodic Inflation Adjustments", "Asset Indexation", "Revaluing fixed assets to current fair market value under revaluation model.", ["Asset Revaluation", "Revaluation Surplus"]),
            ("Depreciation Run (AFAB) and General Ledger Posting Engine", "Periodic Asset Runs", "Executing monthly depreciation runs and resolving posting run termination errors.", ["Depreciation Run (AFAB)", "Restart / Repeat Modes"]),
            ("Asset History Sheet (S_ALR_87011990) and Statutory Disclosures", "Statutory Reporting", "Generating opening balance, additions, disposals, and closing net book value.", ["Asset History Sheet", "Net Book Value Disclosure"]),
            ("Low-Value Assets (LVA) Full Immediate Write-Off Processing", "Tax Depreciation", "Capitalizing and fully depreciating low-cost items in the month of acquisition.", ["Low-Value Assets (LVA)", "Immediate Write-Off Threshold"]),
            ("Physical Inventory Counting for Fixed Assets and Barcode Audits", "Physical Asset Control", "Reconciling physical fixed asset counts against the asset master registry.", ["Asset Barcode Auditing", "Asset Inventory Sheet"]),
            ("Componentization of Fixed Assets (Complex Multi-Part Assets)", "Component Accounting", "Managing major components with different useful lives under separate sub-numbers.", ["Asset Sub-Numbers", "Component Depreciation"]),
            ("Lease Accounting in S/4HANA under IFRS 16 / ASC 842", "Lease Governance", "Capitalizing Right-of-Use (ROU) assets and corresponding lease liabilities.", ["IFRS 16 Lease Accounting", "Right-of-Use (ROU) Asset"]),
            ("Phase 4 Placement Milestone: Asset Accounting Architecture Defense", "Executive Presentation", "Presenting asset lifecycle management and IFRS 16 lease compliance to CFO.", ["Asset Lifecycle Strategy", "IFRS 16 Compliance"]),
        ]),

        # Phase 5: Days 61-75 (Controlling CO: Cost Centers, Orders & Profit Centers)
        (61, 75, "Controlling CO", [
            ("Controlling Area Configuration and Assignment to Company Codes", "Controlling Architecture", "Establishing 1:1 vs 1:N controlling area to company code enterprise structures.", ["Controlling Area (OKKP)", "1:N Enterprise Structure"]),
            ("Primary vs Secondary Cost Elements in S/4HANA", "Cost Element Design", "Understanding how GL account types in S/4HANA incorporate CO cost elements.", ["Primary Cost Elements", "Secondary Cost Elements"]),
            ("Cost Center Accounting (CO-CCA) Hierarchy and Standard Tree", "Cost Center Design", "Structuring cost center hierarchies to mirror operational organizational charts.", ["Cost Center Standard Hierarchy", "Cost Center Master (KS01)"]),
            ("Activity Types and Statistical Key Figures (SKF)", "Allocation Drivers", "Measuring internal labor hours, square footage, and machine run hours.", ["Activity Types (KL01)", "Statistical Key Figures"]),
            ("Cost Center Distribution (KSV5) vs Assessment (KSU5) Cycles", "Cost Allocation Cycles", "Comparing primary cost distribution with secondary cost element assessments.", ["Cost Distribution (KSV5)", "Cost Assessment (KSU5)"]),
            ("Internal Orders: Real Orders vs Statistical Orders", "Internal Project Costing", "Differentiating temporary cost accumulators from pure statistical tracking.", ["Real Internal Order", "Statistical Order"]),
            ("Internal Order Budgeting, Availability Control, and Tolerance Limits", "Budget Governance", "Enforcing strict budget thresholds that block purchase requisitions when exhausted.", ["Availability Control (AKBL)", "Tolerance Limit Warnings"]),
            ("Profit Center Accounting (CO-PCA) Standard Hierarchy", "Managerial P&L", "Structuring profit centers to deliver comprehensive divisional P&L statements.", ["Profit Center Hierarchy", "Divisional P&L Accounting"]),
            ("Transfer Pricing Between Profit Centers in S/4HANA", "Managerial Pricing", "Establishing arm's-length internal transfer prices between business units.", ["Profit Center Transfer Price", "Internal Markups"]),
            ("Product Costing (CO-PC): Cost Object Controlling and Standard Cost", "Manufacturing Costing", "Calculating standard cost estimates using Bill of Materials and routings.", ["Cost Estimate with Quantity", "BOM & Routing Explosion"]),
            ("Costing Run (CK40N): Costing, Marking, and Releasing Standard Prices", "Costing Release", "Executing quarterly standard cost updates across manufacturing plant inventories.", ["Costing Run (CK40N)", "Marking & Releasing Prices"]),
            ("Manufacturing Order Variances: Material, Labor, and Overhead Splits", "Variance Analysis", "Calculating input price, input quantity, and resource usage variances (KKS2).", ["Manufacturing Variance", "Production Order Settlement"]),
            ("Profitability Analysis (CO-PA): Costing-Based vs Account-Based", "Margin Analytics", "Analyzing market segment margins across products, customers, and sales channels.", ["Account-Based CO-PA", "Margin Contribution"]),
            ("CO-PA Derivation Rules and Characteristic Mapping", "Market Segment Modeling", "Deriving strategic market characteristics (industry, territory) from master data.", ["Characteristic Derivation", "Profitability Segment"]),
            ("Phase 5 Placement Milestone: Management Controlling CO Defense", "Executive Review", "Presenting Cost Center allocations and standard product costing to COO.", ["Cost Center Strategy", "Standard Costing Integrity"]),
        ]),

        # Phase 6: Days 76-89 (Period-End Close, Integrations & S/4HANA Universal Journal)
        (76, 89, "Integration & Closing", [
            ("Month-End Financial Close Checklist and Sequential Dependencies", "Financial Closing", "Sequencing period-end tasks from sub-ledger closing to financial statement generation.", ["Closing Checklist", "Sequential Task Dependencies"]),
            ("GR/IR Clearing Account Maintenance and Analysis (MR11)", "MM-FI Reconciliation", "Clearing aged purchase order delivery vs invoice timing imbalances.", ["GR/IR Clearing (MR11)", "Unbilled Receipts Cleanup"]),
            ("MM-FI Automatic Account Determination (OBYC): Keys and Modifiers", "Integration Customizing", "Configuring valuation classes, posting rules, and automatic GL triggers.", ["Transaction OBYC", "Valuation Class Mapping"]),
            ("SD-FI Revenue Account Determination (VKOA): Access Sequences", "Revenue Integration", "Configuring account assignment groups and pricing condition type mappings.", ["Transaction VKOA", "Account Determination Group"]),
            ("Goods and Services Tax (GST) / Value Added Tax (VAT) Reporting", "Tax Filings", "Reconciling input tax credits against output tax liabilities in tax registers.", ["Input Tax Credit (ITC)", "Tax on Sales/Purchases"]),
            ("Intercompany Reconciliations (ICR) and Elimination Postings", "Group Consolidation", "Reconciling intercompany receivables, payables, revenues, and expenses.", ["Intercompany Reconciliation", "Elimination Entry"]),
            ("S/4HANA Universal Journal ACDOCA Architecture Deep Dive", "In-Memory Database", "Analyzing 300+ financial and managerial dimensions in a single data row.", ["Table ACDOCA Structure", "Multi-Dimensional Granularity"]),
            ("Central Finance (CFIN) Replication Engine and Error Handling (AIF)", "Enterprise Scale", "Replicating financial documents from distributed legacy SAP and non-SAP systems.", ["Central Finance (CFIN)", "Application Interface Framework"]),
            ("Financial Closing Cockpit Automation and Background Job Triggers", "Closing Automation", "Automating batch closing runs with dependency logic and real-time Gantt tracking.", ["Closing Cockpit Scheduling", "Automated Background Batch"]),
            ("Audit Information System (AIS) and Internal Financial Controls", "Audit Readiness", "Generating audit trails, user transaction logs, and Segregation of Duties checks.", ["Audit Information System", "Segregation of Duties (SoD)"]),
            ("Data Migration Cockpit (LTMC / Migrate Your Data) for Finance", "Data Migration", "Staging, mapping, and validating opening balances and master data from legacy systems.", ["Migration Cockpit", "Opening Balance Cutover"]),
            ("SAP FICO Cutover Planning and Go-Live Readiness Governance", "Go-Live Architecture", "Orchestrating financial blackline reconciliation, freeze periods, and hypercare.", ["Cutover Strategy", "Financial Blackline Reconcile"]),
            ("Continuous Learning: S/4HANA Cloud (Public vs Private) Finance Trends", "Future-Proofing", "Evaluating monthly cloud updates, Clean Core strategy, and BTP integration.", ["Clean Core Strategy", "S/4HANA Cloud Finance"]),
            ("Senior SAP FICO Consultant Placement Interview: Complex Scenarios", "Placement Defense", "Architecting a multi-national global S/4HANA financial blueprint in live interview.", ["Global Blueprint Defense", "Consulting Leadership"]),
        ]),
    ]

    for p_start, p_end, p_phase, p_topics in phase_definitions:
        for idx, t in enumerate(p_topics):
            d_num = p_start + idx
            t_title, t_cat, t_desc, t_vocab = t
            rate_base = 3200 + (d_num * 140)
            delta_pct = 12 + (d_num % 22)
            result_val = int(rate_base * (1 + delta_pct / 100))

            days.append({
                "day": d_num,
                "commType": COMM_TYPES[d_num % len(COMM_TYPES)],
                "commTitle": t_title,
                "commScenario": f"During an enterprise financial architecture review for {t_title}, stakeholders request clarification on {t_desc}.",
                "commPrompt": f"Explain the critical SAP FICO configuration principles, business process impacts, and compliance controls of {t_title} with precision.",
                "commVocab": [t_vocab[0], t_vocab[1]],
                "commRule": "Enterprise Financial Presence & ERP Architecture Precision",
                "commWeakResponse": f"We just set up {t_title} using default SAP settings without checking the underlying accounting flow.",
                "commWeakCritique": "Vague, passive, and demonstrates a severe lack of functional consulting rigor and financial accounting depth.",
                "commStrongResponse": f"In our SAP enterprise architecture, {t_title} is configured using {t_vocab[0]} and {t_vocab[1]} to guarantee complete statutory compliance, eliminate reconciliation lag, and provide real-time financial reporting.",
                "commStrongCritique": "Structured, authoritative, and strictly connects technical ERP customizing to executive financial controls.",
                "commCoachTip": f"Always anchor your explanation in financial integrity: explain how {t_vocab[0]} prevents reporting discrepancies.",
                "aptTopic": APT_TOPICS[d_num % len(APT_TOPICS)],
                "aptTitle": f"{t_title} Financial Math",
                "aptQuestion": f"An enterprise SAP financial subsystem processes {rate_base:,} accounting postings per hour. After optimizing {t_title}, posting throughput increases by {delta_pct}%. What is the new hourly transaction volume processed?",
                "aptOptions": [f"{result_val:,} postings/hr", f"{result_val - 60:,} postings/hr", f"{result_val + 85:,} postings/hr", f"{result_val - 90:,} postings/hr"],
                "aptAnswer": 0,
                "aptExplanation": f"Calculation: Increase = {rate_base} * {delta_pct/100:.2f} = {result_val - rate_base}. New volume = {rate_base} + {result_val - rate_base} = {result_val:,} postings per hour.",
                "aptFormula": "New Volume = Base Volume * (1 + Growth Rate)",
                "logicType": LOGIC_TYPES[d_num % len(LOGIC_TYPES)],
                "logicTitle": f"{t_title} ERP Logic",
                "logicQuestion": f"When configuring {t_title}, which accounting or system constraint must be strictly enforced to preserve ledger integrity?",
                "logicOptions": [
                    f"Ensure {t_vocab[0]} is verified and aligned with the Chart of Accounts and Document Splitting rules before posting transactions.",
                    f"Bypass {t_vocab[1]} completely and post unbalanced journal entries directly to the database.",
                    "Allow manual override of sub-ledger reconciliation accounts without audit logging.",
                    "Execute period-end closing runs without verifying the open posting period."
                ],
                "logicAnswer": 0,
                "logicExplanation": f"Correct! In {t_title}, establishing that {t_vocab[0]} aligns with accounting and document splitting rules guarantees a balanced General Ledger and compliant financial reporting.",
            })

    # Day 90: Final Placement Challenge
    days.append({
        "day": 90,
        "commType": "interview-question",
        "commTitle": "FINAL PLACEMENT CHALLENGE: Senior SAP FICO Solution Architect Placement Defense",
        "commScenario": "You are presenting before the Global Finance Transformation Steering Committee and the Chief Financial Officer for a Lead SAP FICO Solution Architect position.",
        "commPrompt": "Deliver an end-to-end global finance architecture defense for a Fortune 500 multinational migrating from disparate legacy ERPs to SAP S/4HANA 2023: detailing Enterprise Structure design across 14 countries, Universal Journal (ACDOCA) multi-GAAP parallel ledgers (IFRS and US GAAP), real-time P2P and O2C logistical integrations, automated Central Finance (CFIN) replication, and a compressed 3-day Fast Close via Financial Closing Cockpit.",
        "commVocab": ["Global Enterprise Structure", "ACDOCA Multi-GAAP Architecture", "S/4HANA Fast Close Transformation"],
        "commRule": "Boardroom Financial Authority, Global ERP Strategy & Transformation Mastery",
        "commWeakResponse": "We will install S/4HANA, configure company codes and charts of accounts, train users on Fiori, and use standard migration tools to move data so finance can close the books faster.",
        "commWeakCritique": "Lacks multi-GAAP architecture depth, fails to explain intercompany reconciliation, and provides no concrete Fast Close methodology.",
        "commStrongResponse": "Our global S/4HANA financial transformation blueprint establishes a unified, compliant, and agile digital core. We architect a centralized Enterprise Structure governing 14 international Company Codes under a single Operational Chart of Accounts with localized country Charts of Accounts for statutory compliance. At the core is the Universal Journal (table ACDOCA), deploying Leading Ledger 0L for IFRS corporate reporting alongside Non-Leading Ledgers for local tax GAAP, completely eliminating month-end FI-CO reconciliation. Supply chain integrations (MM-FI via OBYC and SD-FI via VKOA) enforce automated three-way matching and instant revenue realization. For our disparate acquired subsidiaries, we deploy S/4HANA Central Finance (CFIN) via SLT replication, providing immediate consolidated financial visibility. Finally, orchestrated through the SAP Financial Closing Cockpit, we automate intercompany reconciliations and batch runs, successfully compressing our global month-end close from 9 days down to 3 days with total audit defensibility.",
        "commStrongCritique": "A towering tour de force in enterprise ERP architecture: seamlessly unites global statutory compliance, in-memory database architecture, logistical integration, and CFO-level financial close compression.",
        "commCoachTip": "In the final placement challenge, demonstrate complete command over global enterprise structures, multi-GAAP parallel ledgers, and operational P2P/O2C integration points.",
        "aptTopic": "Data Interpretation & Metrics",
        "aptTitle": "Final Assessment: Multinational Consolidated Financial Working Capital Math",
        "aptQuestion": "A multinational enterprise operating across 4 global subsidiaries records the following Accounts Receivable balances: Sub A: $12,000,000; Sub B: $8,500,000; Sub C: €6,000,000 (Spot EUR/USD: 1.10); Sub D: ₹400,000,000 (Spot USD/INR: 80.0). What is the total consolidated Accounts Receivable balance in USD for the group balance sheet?",
        "aptOptions": ["$32,100,000", "$30,500,000", "$34,200,000", "$29,800,000"],
        "aptAnswer": 0,
        "aptExplanation": "Calculation: Sub A = $12,000,000. Sub B = $8,500,000. Sub C = €6,000,000 * 1.10 = $6,600,000. Sub D = ₹400,000,000 / 80.0 = $5,000,000. Total Consolidated AR = $12,000,000 + $8,500,000 + $6,600,000 + $5,000,000 = $32,100,000.",
        "aptFormula": "Consolidated AR = Sum(Sub AR * Respective Exchange Rate to USD)",
        "logicType": "Decision Architecture",
        "logicTitle": "Final Assessment: End-to-End Enterprise Accounting System Logic",
        "logicQuestion": "During cutover for a global S/4HANA implementation, an automated validation script discovers that the historical legacy asset cumulative acquisition value does not equal the general ledger fixed asset balance in Company Code 3000 by $450,000. According to SAP best practices and statutory auditing rules, what is the mandatory action?",
        "logicOptions": [
            "Halt the financial cutover sign-off immediately, execute reconciliation report ABST2 to identify the specific asset master or depreciation area causing the variance, post correcting reconciliation entries in the legacy system, and re-execute the migration run before opening the period for business transactions.",
            "Ignore the $450,000 variance and force the go-live because leadership wants to meet the announced date.",
            "Delete the asset reconciliation account from the balance sheet and post the variance to office stationery expense.",
            "Disable the General Ledger audit trail permanently in table T001."
        ],
        "logicAnswer": 0,
        "logicExplanation": "Correct! Financial go-live requires zero variance between sub-ledger asset registers and General Ledger control accounts (ABST2 reconciliation). Any imbalance violates statutory balance sheet integrity and must be diagnosed, corrected, and verified prior to opening production periods.",
    })

    return days

print("sap_data module ready.")
