import { Role, Permission, ScopeType } from '../types/auth';

export interface RoleDefinition {
  role: Role;
  title: string;
  category: 'Platform Administration' | 'College CPOS' | 'Learning Operations' | 'Student' | 'Recruiter';
  description: string;
  defaultScopeType: ScopeType;
  permissions: Permission[];
}

export const ROLE_DEFINITIONS: Record<Role, RoleDefinition> = {
  SUPER_ADMIN: {
    role: 'SUPER_ADMIN',
    title: 'SantoGe Super Administrator',
    category: 'Platform Administration',
    description: 'Full global platform control across all colleges, students, batches, mentors, content, finance, and settings.',
    defaultScopeType: 'ALL',
    permissions: [
      'MANAGE_SYSTEM_SETTINGS',
      'MANAGE_PERMISSIONS',
      'VIEW_PLATFORM_ANALYTICS',
      'VIEW_ALL_STUDENTS',
      'CREATE_STUDENTS',
      'BULK_IMPORT_STUDENTS',
      'ACTIVATE_STUDENTS',
      'RESET_STUDENT_CREDENTIALS',
      'CREATE_COLLEGE',
      'MANAGE_ALL_COLLEGES',
      'MANAGE_OWN_COLLEGE',
      'MANAGE_DEPARTMENTS',
      'MANAGE_ALL_CAMPUS_DRIVES',
      'CREATE_CAMPUS_DRIVE',
      'SHORTLIST_STUDENTS',
      'MANAGE_COMPANY_CRM',
      'OUTREACH_RECRUITERS',
      'VIEW_MARKET_INTELLIGENCE',
      'MANAGE_BATCHES',
      'MANAGE_MENTORS',
      'RECORD_INTERVENTIONS',
      'CONDUCT_MOCK_INTERVIEWS',
      'MANAGE_TELEGRAM_COMMUNITY',
      'POST_ANNOUNCEMENTS',
      'VIEW_AT_RISK_STUDENTS',
      'MANAGE_LEARNING_CONTENT',
      'REVIEW_CONTENT',
      'PUBLISH_CONTENT',
      'ACCESS_LEARNING_ENGINE',
      'VIEW_PAYMENTS',
      'VERIFY_PAYMENTS',
      'MANAGE_INVOICES',
      'MANAGE_SUBSCRIPTIONS',
      'SEARCH_TALENT',
      'POST_JOBS',
      'MANAGE_RECRUITER_PIPELINE',
      'DOWNLOAD_RESUME',
    ],
  },
  OPERATIONS_MANAGER: {
    role: 'OPERATIONS_MANAGER',
    title: 'Operations Manager',
    category: 'Platform Administration',
    description: 'Manages operational execution across assigned batches, student progress, mentors, attendance, and at-risk queues.',
    defaultScopeType: 'ALL',
    permissions: [
      'VIEW_PLATFORM_ANALYTICS',
      'VIEW_ALL_STUDENTS',
      'CREATE_STUDENTS',
      'BULK_IMPORT_STUDENTS',
      'ACTIVATE_STUDENTS',
      'MANAGE_BATCHES',
      'MANAGE_MENTORS',
      'RECORD_INTERVENTIONS',
      'VIEW_AT_RISK_STUDENTS',
      'POST_ANNOUNCEMENTS',
      'VIEW_PAYMENTS',
    ],
  },
  FINANCE_ADMIN: {
    role: 'FINANCE_ADMIN',
    title: 'Finance & Payment Administrator',
    category: 'Platform Administration',
    description: 'Oversees student registration payments, verification queues, college invoices, subscriptions, and financial logs.',
    defaultScopeType: 'ALL',
    permissions: [
      'VIEW_PAYMENTS',
      'VERIFY_PAYMENTS',
      'MANAGE_INVOICES',
      'MANAGE_SUBSCRIPTIONS',
      'VIEW_PLATFORM_ANALYTICS',
    ],
  },
  CONTENT_MANAGER: {
    role: 'CONTENT_MANAGER',
    title: 'Curriculum & Content Manager',
    category: 'Platform Administration',
    description: 'Authors, reviews, approves, and publishes learning cards, labs, coding arenas, assignments, and placement questions.',
    defaultScopeType: 'ALL',
    permissions: [
      'MANAGE_LEARNING_CONTENT',
      'REVIEW_CONTENT',
      'PUBLISH_CONTENT',
      'ACCESS_LEARNING_ENGINE',
    ],
  },
  COLLEGE_SUPER_ADMIN: {
    role: 'COLLEGE_SUPER_ADMIN',
    title: 'College Super Admin',
    category: 'College CPOS',
    description: 'Manages college-wide placement readiness, student directory, departments, drives, and institutional intelligence.',
    defaultScopeType: 'COLLEGE',
    permissions: [
      'VIEW_COLLEGE_STUDENTS',
      'CREATE_STUDENTS',
      'BULK_IMPORT_STUDENTS',
      'MANAGE_OWN_COLLEGE',
      'MANAGE_DEPARTMENTS',
      'MANAGE_COLLEGE_CAMPUS_DRIVES',
      'CREATE_CAMPUS_DRIVE',
      'SHORTLIST_STUDENTS',
      'MANAGE_COMPANY_CRM',
      'OUTREACH_RECRUITERS',
      'VIEW_MARKET_INTELLIGENCE',
      'VIEW_AT_RISK_STUDENTS',
      'DOWNLOAD_RESUME',
    ],
  },
  COLLEGE_PLACEMENT_OFFICER: {
    role: 'COLLEGE_PLACEMENT_OFFICER',
    title: 'College Placement Officer (CPO)',
    category: 'College CPOS',
    description: 'Runs campus placement drives, company CRM relationships, recruiter outreach, candidate shortlisting, and offers.',
    defaultScopeType: 'COLLEGE',
    permissions: [
      'VIEW_COLLEGE_STUDENTS',
      'MANAGE_COLLEGE_CAMPUS_DRIVES',
      'CREATE_CAMPUS_DRIVE',
      'SHORTLIST_STUDENTS',
      'MANAGE_COMPANY_CRM',
      'OUTREACH_RECRUITERS',
      'VIEW_MARKET_INTELLIGENCE',
      'VIEW_AT_RISK_STUDENTS',
      'DOWNLOAD_RESUME',
    ],
  },
  DEPARTMENT_COORDINATOR: {
    role: 'DEPARTMENT_COORDINATOR',
    title: 'Department Placement Coordinator',
    category: 'College CPOS',
    description: 'Monitors student technical and placement readiness strictly within assigned academic departments.',
    defaultScopeType: 'COLLEGE_DEPARTMENT',
    permissions: [
      'VIEW_DEPARTMENT_STUDENTS',
      'SHORTLIST_STUDENTS',
      'VIEW_AT_RISK_STUDENTS',
      'VIEW_MARKET_INTELLIGENCE',
      'DOWNLOAD_RESUME',
    ],
  },
  MENTOR: {
    role: 'MENTOR',
    title: 'Technical & Career Mentor',
    category: 'Learning Operations',
    description: 'Guides assigned batches, tracks daily progress, records interventions, conducts mock interviews, and flags at-risk talent.',
    defaultScopeType: 'ASSIGNED_BATCHES',
    permissions: [
      'VIEW_BATCH_STUDENTS',
      'RECORD_INTERVENTIONS',
      'CONDUCT_MOCK_INTERVIEWS',
      'VIEW_AT_RISK_STUDENTS',
      'ACCESS_LEARNING_ENGINE',
    ],
  },
  BATCH_COORDINATOR: {
    role: 'BATCH_COORDINATOR',
    title: 'Batch Coordinator',
    category: 'Learning Operations',
    description: 'Ensures batch synchronization, daily placement cycle attendance, Telegram announcements, and operational pacing.',
    defaultScopeType: 'ASSIGNED_BATCHES',
    permissions: [
      'VIEW_BATCH_STUDENTS',
      'MANAGE_BATCHES',
      'MANAGE_TELEGRAM_COMMUNITY',
      'POST_ANNOUNCEMENTS',
      'VIEW_AT_RISK_STUDENTS',
    ],
  },
  STUDENT: {
    role: 'STUDENT',
    title: 'Student / Talent',
    category: 'Student',
    description: 'Personalized talent operating system: daily technical missions, interactive labs, coding arena, placement accelerator, and career engine.',
    defaultScopeType: 'SELF',
    permissions: [
      'VIEW_SELF_STUDENT',
      'ACCESS_LEARNING_ENGINE',
      'SUBMIT_ASSIGNMENTS',
    ],
  },
  RECRUITER: {
    role: 'RECRUITER',
    title: 'Talent Acquisition Partner',
    category: 'Recruiter',
    description: 'Discovers verified candidates by Talent Score & IRI, posts jobs, manages Kanban pipeline stages, and conducts interviews.',
    defaultScopeType: 'RECRUITER_PERMITTED',
    permissions: [
      'SEARCH_TALENT',
      'POST_JOBS',
      'MANAGE_RECRUITER_PIPELINE',
      'DOWNLOAD_RESUME',
    ],
  },
};
