/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminArchitectureRouteImport } from './routes/admin.architecture'
import { Route as AdminAutomationsRouteImport } from './routes/admin.automations'
import { Route as AdminBatchesRouteImport } from './routes/admin.batches'
import { Route as AdminProvisioningRouteImport } from './routes/admin.provisioning'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentAcceleratorRouteImport } from './routes/student.accelerator'
import { Route as StudentBatchRouteImport } from './routes/student.batch'
import { Route as StudentGatewayRouteImport } from './routes/student.gateway'
import { Route as StudentLabsRouteImport } from './routes/student.labs'
import { Route as StudentLeaderboardRouteImport } from './routes/student.leaderboard'
import { Route as StudentPlacementRouteImport } from './routes/student.placement'
import { Route as StudentSettingsRouteImport } from './routes/student.settings'
import { Route as StudentTechnicalRouteImport } from './routes/student.technical'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArchitectureRoute = AdminArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomationsRoute = AdminAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBatchesRoute = AdminBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvisioningRoute = AdminProvisioningRouteImport.update({
  id: '/provisioning',
  path: '/provisioning',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAcceleratorRoute = StudentAcceleratorRouteImport.update({
  id: '/accelerator',
  path: '/accelerator',
  getParentRoute: () => StudentRoute,
} as any)
const StudentBatchRoute = StudentBatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => StudentRoute,
} as any)
const StudentGatewayRoute = StudentGatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLabsRoute = StudentLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLeaderboardRoute = StudentLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPlacementRoute = StudentPlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTechnicalRoute = StudentTechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/architecture': typeof AdminArchitectureRoute
  '/admin/automations': typeof AdminAutomationsRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/provisioning': typeof AdminProvisioningRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/student/accelerator': typeof StudentAcceleratorRoute
  '/student/batch': typeof StudentBatchRoute
  '/student/gateway': typeof StudentGatewayRoute
  '/student/labs': typeof StudentLabsRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/placement': typeof StudentPlacementRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/technical': typeof StudentTechnicalRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/architecture': typeof AdminArchitectureRoute
  '/admin/automations': typeof AdminAutomationsRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/provisioning': typeof AdminProvisioningRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/student/accelerator': typeof StudentAcceleratorRoute
  '/student/batch': typeof StudentBatchRoute
  '/student/gateway': typeof StudentGatewayRoute
  '/student/labs': typeof StudentLabsRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/placement': typeof StudentPlacementRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/technical': typeof StudentTechnicalRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/architecture': typeof AdminArchitectureRoute
  '/admin/automations': typeof AdminAutomationsRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/provisioning': typeof AdminProvisioningRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/student/accelerator': typeof StudentAcceleratorRoute
  '/student/batch': typeof StudentBatchRoute
  '/student/gateway': typeof StudentGatewayRoute
  '/student/labs': typeof StudentLabsRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/placement': typeof StudentPlacementRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/technical': typeof StudentTechnicalRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/student'
    | '/admin/architecture'
    | '/admin/automations'
    | '/admin/batches'
    | '/admin/provisioning'
    | '/admin/settings'
    | '/student/accelerator'
    | '/student/batch'
    | '/student/gateway'
    | '/student/labs'
    | '/student/leaderboard'
    | '/student/placement'
    | '/student/settings'
    | '/student/technical'
    | '/admin/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/architecture'
    | '/admin/automations'
    | '/admin/batches'
    | '/admin/provisioning'
    | '/admin/settings'
    | '/student/accelerator'
    | '/student/batch'
    | '/student/gateway'
    | '/student/labs'
    | '/student/leaderboard'
    | '/student/placement'
    | '/student/settings'
    | '/student/technical'
    | '/admin'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/student'
    | '/admin/architecture'
    | '/admin/automations'
    | '/admin/batches'
    | '/admin/provisioning'
    | '/admin/settings'
    | '/student/accelerator'
    | '/student/batch'
    | '/student/gateway'
    | '/student/labs'
    | '/student/leaderboard'
    | '/student/placement'
    | '/student/settings'
    | '/student/technical'
    | '/admin/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/architecture': {
      id: '/admin/architecture'
      path: '/architecture'
      fullPath: '/admin/architecture'
      preLoaderRoute: typeof AdminArchitectureRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/automations': {
      id: '/admin/automations'
      path: '/automations'
      fullPath: '/admin/automations'
      preLoaderRoute: typeof AdminAutomationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/batches': {
      id: '/admin/batches'
      path: '/batches'
      fullPath: '/admin/batches'
      preLoaderRoute: typeof AdminBatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/provisioning': {
      id: '/admin/provisioning'
      path: '/provisioning'
      fullPath: '/admin/provisioning'
      preLoaderRoute: typeof AdminProvisioningRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/accelerator': {
      id: '/student/accelerator'
      path: '/accelerator'
      fullPath: '/student/accelerator'
      preLoaderRoute: typeof StudentAcceleratorRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/batch': {
      id: '/student/batch'
      path: '/batch'
      fullPath: '/student/batch'
      preLoaderRoute: typeof StudentBatchRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/gateway': {
      id: '/student/gateway'
      path: '/gateway'
      fullPath: '/student/gateway'
      preLoaderRoute: typeof StudentGatewayRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/labs': {
      id: '/student/labs'
      path: '/labs'
      fullPath: '/student/labs'
      preLoaderRoute: typeof StudentLabsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/leaderboard': {
      id: '/student/leaderboard'
      path: '/leaderboard'
      fullPath: '/student/leaderboard'
      preLoaderRoute: typeof StudentLeaderboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/placement': {
      id: '/student/placement'
      path: '/placement'
      fullPath: '/student/placement'
      preLoaderRoute: typeof StudentPlacementRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/technical': {
      id: '/student/technical'
      path: '/technical'
      fullPath: '/student/technical'
      preLoaderRoute: typeof StudentTechnicalRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArchitectureRoute: typeof AdminArchitectureRoute
  AdminAutomationsRoute: typeof AdminAutomationsRoute
  AdminBatchesRoute: typeof AdminBatchesRoute
  AdminProvisioningRoute: typeof AdminProvisioningRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArchitectureRoute: AdminArchitectureRoute,
  AdminAutomationsRoute: AdminAutomationsRoute,
  AdminBatchesRoute: AdminBatchesRoute,
  AdminProvisioningRoute: AdminProvisioningRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentAcceleratorRoute: typeof StudentAcceleratorRoute
  StudentBatchRoute: typeof StudentBatchRoute
  StudentGatewayRoute: typeof StudentGatewayRoute
  StudentLabsRoute: typeof StudentLabsRoute
  StudentLeaderboardRoute: typeof StudentLeaderboardRoute
  StudentPlacementRoute: typeof StudentPlacementRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentTechnicalRoute: typeof StudentTechnicalRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAcceleratorRoute: StudentAcceleratorRoute,
  StudentBatchRoute: StudentBatchRoute,
  StudentGatewayRoute: StudentGatewayRoute,
  StudentLabsRoute: StudentLabsRoute,
  StudentLeaderboardRoute: StudentLeaderboardRoute,
  StudentPlacementRoute: StudentPlacementRoute,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentTechnicalRoute: StudentTechnicalRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
